### ISSUE TITLE
DNS resolution fails on arm7 based machines due to upstream change to time64

### ISSUE THREAD

**Issue by dabiged** [haugene/docker-transmission-openvpn#1726] opened 2021-02-18 01:06 UTC
**Before creating this issue I have:**
- [x] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [x] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section and FAQ
- [x] Tried to add as much relevant information to the issue as possible

**Describe the problem**
The datetime system on the alpine base image is broken on my raspberry pi4, and probably all arm7 based systems.
I believe this stems from the recent alpine change to the time64 system explained here: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements. Although this is an upstream issue I believe it impacts this project and there may be other affected users.
This manifests on my system as a DNS error, that has nothing to do with networking. 

I think this is also related to the recent activity on #1564 as they have very similar issues.

This is my error log from my base image.
```
Starting container with revision: 9d975aba54f79e4fecc57969e51c780a6f9a97af
One or more OVERRIDE_DNS addresses found. Will use them to overwrite /etc/resolv.conf
WARNING: initial DNS resolution test failed
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.CKNIaf
curl: (6) Could not resolve host: www.privateinternetaccess.com
```

**Logs**
During the trouble shooting we are asked to check if networking is working for the basic alpine linux image. 
It is not working for my raspberry pi arm7 based machine and I believe it isn't because the date-time system is completely borked.

```
pi@raspberrypi4:~/docker $ docker run --rm -it alpine sh
/ # date
Sun Jan  0 00:100:4174038  1900
/ # nslookup google.com
nslookup: clock_gettime(MONOTONIC) failed
```
similarly the base config for this image is not working either

```
pi@raspberrypi4:~/docker $ docker run --rm -it   -e OPENVPN_PROVIDER=PIA   -e OPENVPN_CONFIG=france   -e OPENVPN_USERNAME=donald   -e OPENVPN_PASSWORD=duck   haugene/transmission-openvpn:latest /bin/bash
bash-5.1# date
Sun Jan  0 00:100:4174038  1900
bash-5.1# nslookup google.com
nslookup: clock_gettime(MONOTONIC) failed
```

Note that other base images like ubuntu are not affected.
```
pi@raspberrypi4:~/docker $ docker run --rm -it  ubuntu /bin/bash
root@a8979c202b14:/# date
Thu Feb 26 15:09:47 UTC 1970
```

**Host system:**
I am running on a raspberry pi 4 with raspbian stable.

**Comment by dabiged** [comment] 2021-02-18 01:10
Note that rolling back to the haugene/transmission-openvpn:3.3 image fixes the issue.

**Comment by bbender716** [comment] 2021-02-22 22:09
I'm experiencing a DNS resolution issue with similar logs as well on my Pi4 except with Windscribe, but reverting to 3.3 does not resolve the issue. I'm currently working my way backwards through the versions to check compatibility, but the one I had that was working was the 3.0.2-armhf version.

**Comment by pkishino** [comment] 2021-03-09 01:05
@haugene had a quick look and the release notes mentioned something about being able to rebuild this to continue support..perhaps we can fix this when building?

**Comment by zerofoxfive** [comment] 2021-03-13 05:23
> **Before creating this issue I have:**
> 
> * [x]  Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
> * [x]  [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section and FAQ
> * [x]  Tried to add as much relevant information to the issue as possible
> 
> **Describe the problem**
> The datetime system on the alpine base image is broken on my raspberry pi4, and probably all arm7 based systems.
> I believe this stems from the recent alpine change to the time64 system explained here: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements. Although this is an upstream issue I believe it impacts this project and there may be other affected users.
> This manifests on my system as a DNS error, that has nothing to do with networking.
> 
> I think this is also related to the recent activity on #1564 as they have very similar issues.
> 
> This is my error log from my base image.
> 
> ```
> Starting container with revision: 9d975aba54f79e4fecc57969e51c780a6f9a97af
> One or more OVERRIDE_DNS addresses found. Will use them to overwrite /etc/resolv.conf
> WARNING: initial DNS resolution test failed
> Creating TUN device /dev/net/tun
> mknod: /dev/net/tun: File exists
> Using OpenVPN provider: PIA
> Provider PIA has a custom setup script, executing it
> Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.CKNIaf
> curl: (6) Could not resolve host: www.privateinternetaccess.com
> ```
> 
> **Logs**
> During the trouble shooting we are asked to check if networking is working for the basic alpine linux image.
> It is not working for my raspberry pi arm7 based machine and I believe it isn't because the date-time system is completely borked.
> 
> ```
> pi@raspberrypi4:~/docker $ docker run --rm -it alpine sh
> / # date
> Sun Jan  0 00:100:4174038  1900
> / # nslookup google.com
> nslookup: clock_gettime(MONOTONIC) failed
> ```
> 
> similarly the base config for this image is not working either
> 
> ```
> pi@raspberrypi4:~/docker $ docker run --rm -it   -e OPENVPN_PROVIDER=PIA   -e OPENVPN_CONFIG=france   -e OPENVPN_USERNAME=donald   -e OPENVPN_PASSWORD=duck   haugene/transmission-openvpn:latest /bin/bash
> bash-5.1# date
> Sun Jan  0 00:100:4174038  1900
> bash-5.1# nslookup google.com
> nslookup: clock_gettime(MONOTONIC) failed
> ```
> 
> Note that other base images like ubuntu are not affected.
> 
> ```
> pi@raspberrypi4:~/docker $ docker run --rm -it  ubuntu /bin/bash
> root@a8979c202b14:/# date
> Thu Feb 26 15:09:47 UTC 1970
> ```
> 
> **Host system:**
> I am running on a raspberry pi 4 with raspbian stable.

 I confirmed the same on an Odroid HC 2 with the :latest image. Rolled back to 3.3 as suggested and the issue abated.

**Comment by haugene** [comment] 2021-03-13 22:09
@pkishino So by updating to alpine 3.13 we got OpenVPN 2.5.0 but it broke support for arm7 :thinking: 
We could try to do a fix for the build. But "patchwork" for a bug in the upstream also smells like future maintenance.

I'm unsure what to do here. Downgrade to 3.12 and live with older OpenVPN? Patch it with a rebuild in our build pipeline? Or run two builds and tag an alpine-3.12 version? The latter would require us to have some info on the front page I think. A compatibility matrix of sorts. I actually find it more tempting than a build time fix. Thoughts? The multiarch builds have simplified this drastically, we would still have a much simpler tag scheme than before.

**Comment by zerofoxfive** [comment] 2021-03-14 03:04
@haugene is this an issue that will likely be resolved in a future alpine upstream build? Or is your understanding that 32bit builds will have this issue going forward?

If it's the former then adding a 3.12 alpine or arm32 tag until it's resolved might be an easier way. If it's the latter then I'm not sure what options make for the easiest path to maintain.

**Comment by haugene** [comment] 2021-03-14 14:19
Good point @zerofoxfive. I guess my solution of an 3.12 based image is based on an assumption that this would be fixed in a future upstream.

Another option that I didn't think of. If this is not a problem with an ubuntu base for example, we might consider switching back to Ubuntu. The project started on an ubuntu base, got an alpine alternative, then armhf and arm64 and ata some point we had 3 Dockerfiles where one of them was built for the two arm versions.I don't want to go back to that chaos but if an ubuntu base would be more stable for all platforms I think that could be worth it as well. There is a size benefit for alpine images, but... Anyone running this image can probably spare an extra 100MB.

Anyone up for checking what it would take to patch it at buildtime? It's easy to apply some changes to the dev branch and let you test it...

**Comment by talondnb** [comment] 2021-03-19 23:45
Just wanted to chime in here, I'm running an amd64 image with the same issue.

**Comment by zerofoxfive** [comment] 2021-03-20 23:57
@haugene If we follow the principle of Occam's Razor here, then if we baseline back on Ubuntu and that solves the problems for the foreseeable future than it's probably the best outcome. I did a quick google on the time64 changes in alpine and from what I could see it doesn't look like there is a fix forthcoming as it relies on upstream changes. 100MB of extra space in the image is likely to be a non-issue for most users. Especially if you are pruning your docker images.

Eventually this will be a non-issue as even low power arm boards are 64bit with 32bit being the exception, however that's probably several years out, especially if running on recently purchased 32 bit products (Odroid HC range etc).

The last thing I can posit, however it's not a _suggestion_... What would moving the base to another _small_ base image like CoreOS be an alternative solution? I say this understanding that it may cause more issues than it solves.

**Comment by bijfy** [comment] 2021-03-23 02:54
Same with mine raspberry pi 4. Unable to resolve hostname.  Tried 3.3 and it worked.  Thanks @dbrennand

**Comment by zerofoxfive** [comment] 2021-03-24 03:20
> Same with mine raspberry pi 4. Unable to resolve hostname. Tried 3.3 and it worked. Thanks @dbrennand

@bijfy my understanding of the issue is that it should only affect 32bit operation. My question is, are you running a 32bit os on your pi4? If so, you might be able to run 64bit Raspberry Pi OS and it _should_ resolve your issue.

**Comment by talondnb** [comment] 2021-03-24 22:11
> > Same with mine raspberry pi 4. Unable to resolve hostname. Tried 3.3 and it worked. Thanks @dbrennand
> 
> @bijfy my understanding of the issue is that it should only affect 32bit operation. My question is, are you running a 32bit os on your pi4? If so, you might be able to run 64bit Raspberry Pi OS and it _should_ resolve your issue.

I'm on amd64 as mentioned above and also have the issue (running on an Intel NUC). I've reverted to 3.3 and so far so good.

**Comment by pkishino** [comment] 2021-03-24 22:16
Hmm, I’ve run this on a nuc with amd64 and no such issue with latest

**Comment by talondnb** [comment] 2021-03-24 22:31
After reading the original post again, I think my issue is more aligned with https://github.com/haugene/docker-transmission-openvpn/issues/1787. I've had this for the past few weeks, but reverting to 3.3 seems to resolve my issue.

**Comment by braymullo** [comment] 2021-04-04 15:32
Just wanted to add as of this morning I’m getting same error. 

Rasperry Pi 4 64 bit OS Beta
Tried dev (the Ubuntu base), 3.6, 3.3 and 3.0-arm64 

Been working brilliantly up till this morning so not terribly sure what happened. Also Turned off firewall and put myself into DMZ. My Pi sees the internet just fine, as does my other containers, just not this one. 

Let me know if there’s anything I can test or troubleshoot to help out and thanks for your work on this project.

**Comment by bijfy** [comment] 2021-04-04 15:41
Mine is working good with 3.3 . Everything else has error . Using pi 4 32 bit rasbian

**Comment by bbender716** [comment] 2021-04-04 15:45
For what it's worth, I fixed any pi 4 issues I had by 1) using docker-compose, 2) using DNS: setting in docker compose, and 3) specifying a version of transmission < 3 because of 3's issues with triggering 100% CPU with any download.

**Comment by braymullo** [comment] 2021-04-04 18:14
Thank you for your replies. Here’s my fix for now: 

setting up static dns on raspberry pi (with Google dns for now, and not my pihole, which I will test further this week to see if it’s the culprit). 

Guide: https://pimylifeup.com/raspberry-pi-dns-settings/

**Comment by bijfy** [comment] 2021-04-04 18:27
> Thank you for your replies. Here’s my fix for now:
> 
> setting up static dns on raspberry pi (with Google dns for now, and not my pihole, which I will test further this week to see if it’s the culprit).
> 
> Guide: https://pimylifeup.com/raspberry-pi-dns-settings/

Hi. Which image did you used to get it working? 3.3 or dev ?

**Comment by braymullo** [comment] 2021-04-04 18:34
Latest tag. Which I think is 3.6

**Comment by pkishino** [comment] 2021-04-20 23:34
closing for now as we are aiming to move back to ubuntu base for 4.0 release

**Closed by pkishino** 2021-04-20 23:34 UTC
Labels: bug, documentation update

**Comment by pkishino** [comment] 2021-05-03 07:52
Also there looks like there might be a fix here #1564

**Comment by sokulski** [comment] 2021-05-20 18:04
Is the current status that ARM compatibility stops (temporarily) after 3.3? I'm on an ODROID HC2 and as @zerofoxfive mentioned I rolled back to 3.3 and all is well. Should I stay here until 4.0 is released?

**Comment by waddlefluf** [comment] 2021-05-20 20:10
@sokulski This (the samba comment) fixed the issue for me on my Raspberry Pi 4B, which is 32-bit. https://github.com/haugene/docker-transmission-openvpn/issues/1564#issuecomment-831007756

**Comment by sokulski** [comment] 2021-05-20 20:14
@waddlefluf Awesome, thanks! I'll give that a try.

I wasn't able to get a console open on the new container, but I'll give it another go. Thanks for the reply.

**Comment by sokulski** [comment] 2021-06-21 16:29
@waddlefluf 

Sorry to be coming back to this so late after your last reply. I finally had some time to look this over and it seems my earlier comment was misguided.

This set of commands is being run to update the docker host, and then the container was run as normal. Is that right?

**Comment by bijfy** [comment] 2021-06-21 17:04
hi all, Here is Fix for Raspi-OS 32bit:
run it on ssh these 2 commands

wget
http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.4.4-1~bpo10+1_armhf.deb
sudo dpkg -i libseccomp2_2.4.4-1~bpo10+1_armhf.deb

then restart the container. my raspberry  pi 4 working on latest haugene
transmission openvpn

**Comment by waddlefluf** [comment] 2021-06-21 19:27
@sokulski 

If I'm understanding you correctly, I believe so.

From what I remember, what bijfy posted is exactly what I did.

**Comment by JB09** [comment] 2021-06-22 15:33
@sokulski 
>This set of commands is being run to update the docker host, and then the container was run as normal. Is that right?

I ran the commands on my pi host, and 3.6 was able to load

**Comment by sokulski** [comment] 2021-07-06 02:10
> @sokulski
> 
> > This set of commands is being run to update the docker host, and then the container was run as normal. Is that right?
> 
> I ran the commands on my pi host, and 3.6 was able to load

Thanks! Finally got around to running those commands on my host (not a Pi, but a similar 32-bit ARM system) and it worked great. I'm running the latest image and Magnet links are humming right along.

**Comment by dlshumway** [comment] 2021-07-30 17:39
> For what it's worth, I fixed any pi 4 issues I had by 1) using docker-compose, 2) using DNS: setting in docker compose, and 3) specifying a version of transmission < 3 because of 3's issues with triggering 100% CPU with any download.

Just for clarity, can you post the compose line that specifies transmission version <3?

**Comment by talondnb** [comment] 2021-07-30 22:40
image: haugene/transmission-openvpn:3.3

> > For what it's worth, I fixed any pi 4 issues I had by 1) using docker-compose, 2) using DNS: setting in docker compose, and 3) specifying a version of transmission < 3 because of 3's issues with triggering 100% CPU with any download.
> 
> Just for clarity, can you post the compose line that specifies transmission version <3?

https://github.com/haugene/docker-transmission-openvpn/issues/1726#issuecomment-780963144

  image: haugene/transmission-openvpn

**Comment by optionaltoast** [comment] 2021-11-11 14:49
Latest Bullseye based Raspberry Pi OS, latest 4.0 works!

**Comment by agamotto** [comment] 2022-05-12 13:29
For people still stuck on Buster here's another solution: https://docs.linuxserver.io/faq#libseccomp

(https://github.com/haugene/docker-transmission-openvpn/issues/1726#issuecomment-865199344 not working anymore)
