### ISSUE TITLE
TorGuard is updating stuff. Probably need replacement configs. 

### ISSUE THREAD

**Issue by tralce** [haugene/docker-transmission-openvpn#846] opened 2019-07-04 19:03 UTC
Seems they're updating certificates and whatnot. How can I help?

![2019-07-04-150250_1167x300_escrotum](https://user-images.githubusercontent.com/11371119/60684615-ce852680-9e6c-11e9-928a-60ea50b4c730.png)

**Comment by alescdb** [comment] 2019-07-04 19:44
Same here, TorGuard not working anymore.
I've tried `updateConfigs.sh` but after updating I got this error :

```
transmission-openvpn    | adding route to local network 192.168.0.0/16 via 172.18.0.1 dev eth0
transmission-openvpn    | Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/torguard/default.ovpn:16: block-outside-dns (2.4.7)
transmission-openvpn    | Use --help for more information.
```

Side note : `updateConfigs.sh` is failing (`set -e`) because the command `dos2unix` is not installed in the container

**Comment by alescdb** [comment] 2019-07-04 20:11
So for those looking for a quick fix, exec bash inside the container with :
```
docker exec -it transmission-openvpn bash
```
then install dos2unix and an editor (here vim) :
```
root@f6c3061db22d:/# apt update && apt install -y vim dos2unix
```
Edit  : updateConfigs.sh
```
root@f6c3061db22d:/# cd /etc/openvpn/torguard/
root@f6c3061db22d:/# vi updateConfigs.sh
```
After the sed lines add :
```
sed -i "s/^block-outside-dns/#block-outside-dns/" *.ovpn
sed -i "s/^keepalive/#keepalive/" *.ovpn
```

save with `:wq` then run the script :
```
root@f6c3061db22d:/#  ./updateConfigs.sh
```

restart the container.

**Comment by haugene** [comment] 2019-07-05 07:56
Changes merged, the docker hub builds are sometimes slow but should be able to test and verify it soon @tralce. Thanks @alescdb for providing a fix 🥇 

This probably supersedes #768 by updating all TorGuard configs?

**Comment by alescdb** [comment] 2019-07-05 08:02
> This probably supersedes #768 by updating all TorGuard configs?

It seems so, since new config files use AES-256-GCM

**Comment by alescdb** [comment] 2019-07-05 08:43
@haugene I've disable the `keepalive 5 30` option in the config files because I was getting an error something like "ping is not compatible with keepalive", but I've just realized that my `OPENVPN_OPTS` contains `--inactive 3600 --ping 10 --ping-exit 60`, so maybe we should keep the `keepalive` in default configs, what do you think ?

**Comment by haugene** [comment] 2019-07-05 08:50
I agree that we should remove it. The inactive, ping, ping-exit is the recommended way to handle disconnects and I think close to everyone is using it. Those who would want to have keepalive instead can add that to their OPENVPN_OPTS.

**Comment by tralce** [comment] 2019-07-05 11:46
@haugene Everything appears to be working perfectly. Thanks!

**Comment by jasoncross** [comment] 2019-07-05 14:51
Since the update, I keep getting the following via TorGuard in my logs:

Fri Jul  5 14:13:36 2019 TLS Error: cannot locate HMAC in incoming packet from [AF_INET]38.142.58.58:1194

And then I can no longer connect to Transmission.

**Comment by haugene** [comment] 2019-07-05 15:00
Have you tried different configs, same result?

Should probably leave this issue open for some days to see if it could be resolved after they're done upgrading the servers. @tralce and @alescdb, noticing something similar?

Question is if this is on our side or theirs I guess.

**Comment by jasoncross** [comment] 2019-07-05 15:03
I resolved it.  I had to take the current USA-CHICAGO.ovpn config and make a CUSTOM.ovpn where I switched out:

remote chi.central.usa.torguardvpnaccess.com 1912
remote 167.160.172.106 1912

with a line to remote to my custom IP.  And it then worked.

What's odd is that before I just used the USA-CHICAGO.ovpn and specified my custom IP via the OPENVPN_OPTS by setting --remote <IP> but that no longer seems to work.

**Comment by haugene** [comment] 2019-07-05 15:13
Hmm. Depending on what "before" is, could it be different default behaviour in OpenVPN?
I see that the v2.7 contains `OpenVPN 2.4.7 built on Feb 19 2019`
While v2.6, v2.5, v2.4, v2.3, v2.2, v2.1 is using `OpenVPN 2.4.6 built on Apr 24 2018`
And v2.0 (back in april last year) is using `OpenVPN 2.4.5 built on Mar  1 2018`

Haven't dug into the documentation, but there's not any major changes in that area from my side. So it's tempting to "blame" OpenVPN itself.

**Comment by jasoncross** [comment] 2019-07-05 15:28
"Before" was the latest build on docker hub as of a couple of days ago.  I'm using Watchtower and it updated me to the build pushed out this morning overnight which is when it stopped working.

**Comment by haugene** [comment] 2019-07-05 15:36
Ok. So definitely caused by the configs then. I do see that the .ovpn file you're referencing went from having one remote line to two remotes. I always assumed that adding options to the command line would override the options in the .ovpn file, but for remotes that can be multiple - will it append?

**Comment by alescdb** [comment] 2019-07-05 17:27
I have no problem so far with new configs (but the old ones was not working anymore for me). It seems TorGuard is still in the process of updating.
People should not upgrade (or should downgrade) and wait for old configs to fail with errors : 
```
COMMON SYMPTOMS:

- Auth / Reconnect loop
- Certificate error
```

**Comment by huargovfx** [comment] 2019-07-06 23:21
Good day,
Thank for the amazing work, I am running this container in my OMV in a pi 3, I just updated, and now I can't access the web interface of the transmission-openvpn. The docker information shows it is running normal, and connects properly. I have tried with 2 vpns now and no luck.


`
-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    100
-------------------------------------

STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
STARTING TINYPROXY
Found config file /etc/tinyproxy/tinyproxy.conf, updating settings.
Setting tinyproxy port to 8888
Starting Tinyproxy lightweight HTTP proxy daemon: tinyproxy.
Tinyproxy startup script complete.
Sat Jul  6 19:14:23 2019 /sbin/ip route add xx.xx.x.xxx/32 via 172.18.0.1
Sat Jul  6 19:14:23 2019 /sbin/ip route add 0.0.0.0/1 via 10.8.0.1
Sat Jul  6 19:14:23 2019 /sbin/ip route add 128.0.0.0/1 via 10.8.0.1
Sat Jul  6 19:14:23 2019 Initialization Sequence Completed`

The web interface just times out.

**Comment by haugene** [comment] 2019-07-07 16:26
@huargovfx: Try docker exec into your container and see if transmission is running. That will tell us if it's a network issue or a startup issue.
```
docker exec -it <container id or name> bash
... then:
curl localhost:9091
```

What do you get?

**Closed** 2020-04-12 21:23 UTC
Labels: inactivity
