### ISSUE TITLE
Trying to run on raspberry pi - openvpn error

### ISSUE THREAD

**Issue by ni-ka** [haugene/docker-transmission-openvpn#682] opened 2019-01-15 17:18 UTC
transmission_1  | No VPN configuration provided. Using default.
transmission_1  | Setting OPENVPN credentials...
transmission_1  | adding route to local network 192.168.0.0/24 via xxx.xxx.xxx.xxx dev eth0
transmission_1  | Options error: --keepalive conflicts with --ping, --ping-exit, or --ping-restart.  If you use --keepalive, you don't need any of the other --ping directives.
transmission_1  | Use --help for more information.

Any ideas?

**Comment by haugene** [comment] 2019-03-17 11:37
Did you figure it out? The problem is what it says. You cannot use the keepalive option at the same time as you use the ping directives. Seems like you got it working, because your other issue #683 is from a step after this. Closing this for now. You can follow up in the other issue if this is also still a problem.

**Closed by haugene** 2019-03-17 11:37 UTC
