### ISSUE TITLE
Upload speed seems to hover around 2 MB/s

### ISSUE THREAD

**Issue by humphreyyy** [haugene/docker-transmission-openvpn#737] opened 2019-03-13 11:14 UTC
First of all, amazing container. Thank you so much for this.

I have one problem however. While my download speed goes up to 35 MB/s at times, my upload speed always seems to hover around 2MB/s. This is barely 10% of my internet connection. ![Speedtest from a docker container by humphreyyy](https://i.imgur.com/xaKuK0W.jpg) This is a speedtest from a separate docker container (without VPN). Im not sure how to run a speedtest from within this container.

I use hide.me OpenVPN over UDP (I've tried TCP as well) on a synology 918+ NAS. I have DHT and all that disabled but port forwarding is enabled and working. I don't think it's an issue of too little trackers. 

Back when I used to use a different setup but with the same VPN provider, I got much better upload speeds. I really have no clue why the upload speed seems so slow.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by haugene** [comment] 2019-03-13 21:27
Hey. Glad you like the container, and I support you on your quest to find the bottleneck.
That being said - even if we don't find it I'll close this issue at some point because I don't think it's a critical issue and I think it can be caused by a variety of reasons.

But you say you've handled DHT and port forwarding so I'm intrigued.
You can do a speed test of the container in several ways. One is running the same container as you did above, just add `--network=container:<openvpn-container>`. Then that container networking will run through the openvpn container.

Or you can exec into the openvpn container and run this tool for example:
```
wget -O speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
chmod +x speedtest-cli
./speedtest-cli
```

Then a bit more far fetched maybe, could it be a lack of entropy? I've never really done any of this myself with this container, but I know I had a problem with a webserver at one time. It got really slow and it was because of the encryption of https and a lack of entropy.

You could try to mount `-v /dev/urandom:/dev/random` like this post suggests:
https://stackoverflow.com/questions/26021181/not-enough-entropy-to-support-dev-random-in-docker-containers-running-in-boot2d

Or look more into entropy on your own if you think it could be a factor. Guess that depends on the result of your speed test. Let me know what you find out 😄

**Comment by humphreyyy** [comment] 2019-03-13 22:44
Ok i manged to do the speedtest. Didnt know it was as easy as adding that line to the command. Docker is amazing sometimes.

Anyway, here's the result. I stopped all downloads for it. 
[https://i.imgur.com/JlyKbx6.jpg](url) First the regular speedtest again and then through the docker container. Obviously a lot slower but interesting because my experience has been that download speeds have been fine but this shows both as quite slow.  ([https://i.imgur.com/6C2l2Yj.jpg](url) second speedtest shows upload as even slower)

I have to admit that I have absolutely no clue what entropy means in this context. Are you sure i can just mount dev/urandom to this docker container (rw) ? That won't mess anything up? No clue what dev/urandom even does. I'm guessing it has something to do with random number generators for the encryption?

**Comment by humphreyyy** [comment] 2019-03-13 22:51
also how would I add this to an existing container. I'm kinda used to doing it with the synology UI but it doesnt let me go near /dev/. Whats the full command to do this in terminal?

**Comment by haugene** [comment] 2019-03-14 08:47
Not too steady on the whole entropy thing myself. Just know I've hit it before, in another setting, and then installing haveged solved it. Can't really see where the difference should be otherwise. Encrypting stuff uses CPU, but as long as that's not max'ed out it should be OK. Then the next thing could be entropy. But it's a long shot.

To see if that's it you can try to check the available entropy while you're running the speed test.
Exec into the container and run `cat /proc/sys/kernel/random/entropy_avail` several times before, during and after the speed test. What do you see?

You can install haveged inside the container `apt update && apt install -y haveged` and see if that changes anything. As with the command for running it directly, it's pretty well documented in the README. And then you need to add another volume mount for urandom. That should be totally safe for your host system. Many applications use urandom to get random numbers.

**Comment by humphreyyy** [comment] 2019-03-14 09:57
[https://i.imgur.com/BFfDE8x.jpg](Spammed cat while running the speedtest) Didnt really change much. Basically between 1000 and 1300. Is that good? I'm gonna try and change encryption from 256 to 128 to see if that does anything.

**Comment by haugene** [comment] 2019-03-14 10:22
I think that's good. It's only if it drops closer to 0 or a couple of hundred that it's a problem I think.
Tested different vpn server locations?

**Comment by humphreyyy** [comment] 2019-03-14 10:55
Tested different servers, tested TCP vs UDP, always hovering around 17 Mbit/s. [speedtest](https://i.imgur.com/42YFrth.jpg)

I didnt manage to change the cipher from 256 to 128, hide.me seems to force 256 now or something

**Comment by humphreyyy** [comment] 2019-03-14 11:07
Could it be some issue with the tun device? Right now I have it setup on the host with the script you provided, but maybe I'll try the CREATE_TUN_DEVICE option and have it inside the container. If so, how do I stop it on the host?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by haugene** [comment] 2019-03-14 11:11
You don't need to stop it on the host. If you re-create the container with CREATE_TUN_DEVICE=true and just don't volume map the host device to the container that should do it. The device on the host doesn't matter.

**Comment by h45rd** [comment] 2019-03-14 13:10
Interesting issue. Especially the part about entropy.
Don't have much of substance to add besides that - depending on the circumstances (network topology, ISP routing, current load, QoS, etc.) - all those online speed tests are notoriously unreliable.

E.g. I need a lot more threads and a longer test time to max out my line than most of these tests offer. Mostly because my provider has shit peering, I guess. :)

A tried and true iperf measuring setup would be interesting in your scenario.

Anyway. My first guess would have been: "provider issue". And it still is, even though you claim:
>Back when I used to use a different setup but with the same VPN provider, I got much better upload speeds. 

Sounds like this was a while ago. Circumstances (server load, peering, throttling, IXP quotas, etc.) could have changed.
Any chance you could compare these setups side by side in short succession?

If it turns out that the other setup is indeed still faster, my next guess would be some kind of resource limitation. But I will only drag out my crystal ball if we have to :D
Next step would be to try identifying possible bottlenecks with something like [Glances](https://github.com/nicolargo/glances) (or the respective unix tools).

**Comment by humphreyyy** [comment] 2019-03-14 14:16
Ok, so very interesting stuff. First of all, I am not at home rn so I'm using a openVPN connection to a openVPN server hosted on my synology to do all of this. 

I just tried the following:
- Synology DSM on Docker (DDSM): 
    -> Speedtest without VPN: normal (300/100 or so)
    -> Speedtest with L2TP VPN: the mysterious 17/17 speed
- Synology DSM in a Virtual Machine
     -> Speedtest without VPN: normal (300/100 or so)
    -> Speedtest with L2TP VPN: the mysterious 17/17 speed
- Windows 7 Embedded 
    -> Speedtest without VPN: also normal 130/130 (theres a lot more overhead because its all running on this one celeron CPU)

**Comment by h45rd** [comment] 2019-03-14 16:42
My suggestions above apply to all networks, namely your own, your ISP's and your VPN provider's respectively.
But the speed being exactly 17/17, no matter the protocol (overhead/load) and server is very strange indeed.

Could you describe your previous, fast setup? How did it differ from your current setup?

Things that come to mind:
- Does the speed test throttle / has bad peering with / bad routing to your VPN provider? -> Same issues downloading a large file from various reliable, fast mirrors with multiple chunks each at once? Use e.g. aria2c with different mirrors and -x parameter to test with your favorite Linux ISO.
- Performance penalty for VPNs greatly varies [depending on settings](https://www.cse.wustl.edu/~jain/cse567-08/ftp/ovpn/index.html#sec3.3) and protocols used. [Packet fragmentation](https://blog.hambier.lu/post/solving-openvpn-mtu-issues) can play a vital role in these performance issues, too. -> Make sure your settings are optimized for your line and it is not your hardware that's bottlenecking (Glances during downloads, see above).

Don't think running the VPN on your router would do any good. Unless it is a custom built pfSense box or similar.
Never had very good VPN performance on any general use embedded hardware myself.

My best guess right now: your NAS hardware is bottlenecking.

**Comment by humphreyyy** [comment] 2019-03-15 11:19
My previous, fast setup, was synology DSM in a docker container (DDSM). I had it setup to connect to my VPN (L2TP) and then used download station. I also blocked all other ports on my router so that I would only download through the VPN. 

However, since I moved to this container, I definitely saw download speeds of like 25MBs before. It was only the upload that was always stuck at 2MBs.

It could very well be that my NAS is bottlenecking right now, but it shouldn't be. It has Hardware-decrypting for AES and like I said, previous speeds were much better. 

However, sadly, my NAS appeared to have crashed to the point where it doesn't show up in my router interface and I can't physically restart it until I get back home on the 24th. This is why you shouldn't mess with your hardware remotely 😂. I look forward to doing some more investigating when I get home. Thanks a lot for the help so far 👍



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by h45rd** [comment] 2019-03-15 11:50
Hehe.. I know that feeling exactly.. :D
That's why I went a little overboard and got a managed PDU for my rack at home :joy:

**Comment by humphreyyy** [comment] 2019-03-15 11:53
The thing is, I actually thought about putting a homekit smartplug between my PSU and the NAS. Now I wish I had 🤧

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by humphreyyy** [comment] 2019-03-25 13:40
Ok so I got home yesterday and ran some test. Turns out @h45rd was right. It wasn't my NAS's fault or this container's. Apparently I'm getting 17Mbits on my VPN provider anywhere. Doesn't matter which server, protocol or what connection I'm using. I'm still very confused as too what the hell is happening here because I guess it must have starting with my upload speed taking a hit (that's what I first noticed) and then my download speeds also being limited to 17Mbits. 

In the meantime I made a NordVPN account which so far gives me close to my actual internet connection speed. When I tried to change to NordVPN in this container, I think I introduced some kernel panics which basically made my NAS completely freeze up. I think this is also the reason why it froze up 1,5 weeks ago. I opened a ticket with synology so they can take a look at some debug data and I'll open a separate issue here once I know more. My guess is it has something to do with the TUN device crashing and taking the entire system with it.

So I guess this issue can be closed. I'm sorry for not checking the (now obvious) thing first, but I've never had issues with hide.me-Speeds before so this was quite strange.

**Comment by haugene** [comment] 2019-03-25 14:09
Allright. Thanks for posting back and good luck with the debug. There is a new feature released now which creates the TUN device inside the container. Should probably have been done this way a long time - it seems to work well. So you could try that as well.

And there's a slight hiccup with the NordVPN script in the latest release as well. A separate issue exists so you can follow up there if you experience the same. Closing this now.

**Closed by haugene** 2019-03-25 14:09 UTC
Labels: help wanted

**Comment by haugene** [comment] 2019-03-25 14:15
That's the one. The feature was released yesterday, so you tell me if it works 😄 But I don't see why it wouldn't. Not exactly sure how this all links up, you still need to add the NET_ADMIN capability, but you don't need to mount the tun device anymore so that should mean that it's not using the device from the system, right?

**Comment by humphreyyy** [comment] 2019-03-25 16:43
the thing is, I never explicitly did mount the device 🤔 I'll try it out though
