### ISSUE TITLE
Can't access WebUI

### ISSUE THREAD

**Issue by SyRaza** [haugene/docker-transmission-openvpn#398] opened 2018-01-19 15:46 UTC
I'm trying to run this on my Synology DiskStation that has DSM 6.1.4-15217.

I've port forwarded 9091 both in my DSM router configuration area as well as my router itself. 

My router is set to 192.168.2.1 and my DS is set to 192.168.2.24

I am using TorGuard so I followed the instructions on setting everything up as per the readme. I tried to use the ovpn file generated from the TorGuard website but got this error "Supplied config /volume1/Sy/37.ovpn could not be found." So instead I used the one provided in the image. 

Here is what's in the log. I don't know how to copy the environment variables so if someone would walk me through that. ty. 

Fri Jan 19 14:23:58 2018 Initialization Sequence Completed
--
Transmission startup script complete.
NO PORT UPDATER FOR THIS PROVIDER
STARTING TRANSMISSION
 
-------------------------------------
User gid:    0
User uid:    0
User name:   root
-------------------------------------
Transmission will run as
-------------------------------------
 
Generating transmission settings.json from env variables
Using Combustion UI, overriding TRANSMISSION_WEB_HOME
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.35.0.22
Fri Jan 19 14:23:58 2018 /etc/transmission/start.sh tun0 1500 1553 10.35.0.22 10.35.0.21 init
Fri Jan 19 14:23:58 2018 /sbin/ip addr add dev tun0 local 10.35.0.22 peer 10.35.0.21
Fri Jan 19 14:23:58 2018 /sbin/ip link set dev tun0 up mtu 1500
Fri Jan 19 14:23:58 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Fri Jan 19 14:23:58 2018 TUN/TAP device tun0 opened
Fri Jan 19 14:23:56 2018 [TG-OVPN-CA] Peer Connection Initiated with [AF_INET]184.75.220.210:1912
Fri Jan 19 14:23:56 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Fri Jan 19 14:23:56 2018 UDP link remote: [AF_INET]184.75.220.210:1912
Fri Jan 19 14:23:56 2018 UDP link local: (not bound)
Fri Jan 19 14:23:56 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]184.75.220.210:1912
Fri Jan 19 14:23:56 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Fri Jan 19 14:23:56 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Fri Jan 19 14:23:56 2018 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 26 2017
Fri Jan 19 14:23:56 2018 WARNING: file '/etc/openvpn/torguard/ta.key' is group or others accessible
adding route to local network 192.168.2.0/24 via 172.17.0.1 dev eth0
Setting OPENVPN credentials...
Starting OpenVPN using config Canada.Toronto.ovpn
Using OpenVPN provider: TORGUARD
Fri Jan 19 14:23:25 2018 SIGTERM[hard,] received, process exiting
Fri Jan 19 14:23:25 2018 /etc/transmission/stop.sh tun0 1500 1553 10.35.0.6 10.35.0.5 init
Fri Jan 19 14:23:25 2018 /sbin/ip addr del dev tun0 local 10.35.0.6 peer 10.35.0.5
Fri Jan 19 14:23:25 2018 event_wait : Interrupted system call (code=4)
Fri Jan 19 14:19:02 2018 Initialization Sequence Completed
Transmission startup script complete.
NO PORT UPDATER FOR THIS PROVIDER
STARTING TRANSMISSION
 
-------------------------------------
User gid:    0
User uid:    0
User name:   root
-------------------------------------
Transmission will run as
-------------------------------------
 
Generating transmission settings.json from env variables
Using Combustion UI, overriding TRANSMISSION_WEB_HOME
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.35.0.6
Fri Jan 19 14:19:02 2018 /etc/transmission/start.sh tun0 1500 1553 10.35.0.6 10.35.0.5 init
Fri Jan 19 14:19:02 2018 /sbin/ip addr add dev tun0 local 10.35.0.6 peer 10.35.0.5
Fri Jan 19 14:19:02 2018 /sbin/ip link set dev tun0 up mtu 1500
Fri Jan 19 14:19:02 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Fri Jan 19 14:19:02 2018 TUN/TAP device tun0 opened
Fri Jan 19 14:19:01 2018 [TG-OVPN-CA] Peer Connection Initiated with [AF_INET]85.159.233.23:1912
Fri Jan 19 14:19:00 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Fri Jan 19 14:19:00 2018 UDP link remote: [AF_INET]85.159.233.23:1912
Fri Jan 19 14:19:00 2018 UDP link local: (not bound)
Fri Jan 19 14:19:00 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]85.159.233.23:1912
Fri Jan 19 14:19:00 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Fri Jan 19 14:19:00 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Fri Jan 19 14:19:00 2018 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 26 2017
Fri Jan 19 14:19:00 2018 WARNING: file '/etc/openvpn/torguard/ta.key' is group or others accessible
adding route to local network 192.168.2.0/24 via 172.17.0.1 dev eth0
Setting OPENVPN credentials...
Using default OpenVPN gateway for provider torguard
Supplied config /volume1/Sy/37.ovpn could not be found.
Using OpenVPN provider: TORGUARD

**Comment by haugene** [comment] 2018-01-19 23:58
Something is going wrong during startup and transmission is killed:
```
Fri Jan 19 14:23:25 2018 SIGTERM[hard,] received, process exiting
Fri Jan 19 14:23:25 2018 /etc/transmission/stop.sh tun0 1500 1553 10.35.0.6 10.35.0.5 init
```
You could try an older version of the image? And if you're providing a custom ovpn config you need to follow the approach described in the readme for a custom provider. If that works, please check if the ovpn file you've used have been updated compared to the one in this project. Maybe the config files should be updated.

**Comment by SyRaza** [comment] 2018-01-21 22:02
Got it working thanks to your advice. I deleted the container and image from the disk station and started over. I followed the steps to add a custom vpn file except when I got to the step for creating the docker transmission, I added this step.

> -v /path/to/your/config.ovpn:/etc/openvpn/custom/default.ovpn

between these two steps. 

>     -v /volume1/yourpath/:/data \

>     -e "OPENVPN_PROVIDER=PIA" \

It all worked after that. Thank you. 

Three further questions;
1. How do I check to see that transmission is in fact transferring behind the VPN?
2. Is there a way to automatically start transmission downloads by adding a torrent file to a set folder? Like with Synology's native "Download Station", if I download a torrent file to a mapped folder, it will automatically start downloading the torrent without me having to go into the DSM to upload the file.
3. Is there a way to access the WebUI outside of my LAN. Say I'm at work or out of the country and I'd like to check how things are transferring using the WebUI, How would I go about doing that? (I already have my DS setup for access over the internet.)

**Comment by SyRaza** [comment] 2018-01-21 22:13
Another update:
I answered question #1 myself.

While in DSM, in the terminal for the transmission container, I typed 

> wget -qO - http://wtfismyip.com/text

I compared the ip address I got from this again my public IP address (which I checked by googling, what's my ip address) The two IP addresses were not the same = success.

**Comment by haugene** [comment] 2018-01-22 00:39
Yup, that's one way to check that your traffic is actually going through the vpn. For future readers of this issue, another way is described in #323

Second question. Yes, the container has a watch folder. It's described in the readme. Mount it somewhere an put torrents in it and you should be good to go.

Third. Yes, use the proxy container also described in the readme. This will proxy the traffic making it look like it's from your local network even if you're abroad. Of course you need to forward a port in your router.

Now. Can you check the difference of your custom ovpn file to the one in the container? If it doesn't work with the bundled one it might be outdated.

**Comment by SyRaza** [comment] 2018-01-22 03:56
Thanks for the info Haugene. 

I apologize, I really should have read through the whole readme instead of jumping straight to the setting up on synology. 

I got the watch folder working so that's all good. I'll get to the proxy container in a bit. 

And happy to report that the provided ovpn file for TorGuard work and are still up to date. I'm not sure why they didn't work before, but I changed the OPENVPN_PROVIDER from custom to torguard and entered the config file name and it just worked. Not sure why it didn't work before.

Thanks for all of the work you've done!

**Comment by SyRaza** [comment] 2018-01-23 21:04
Another update.

All issues aside from remote access to webui have been solved. I have ports 9091 and 8080 forwarded in my DSM and on my router.

Interestingly, I was able to access the webui from my laptop just once. 
On windows, I used chrome and I keep getting "This site can’t provide a secure connection"
On Ubuntu, I used Chrome and Firefox and I get the same message.

What's weird is, when I go try an access the remote webui from my cellphone, I can! Figuring it was a fluke, I downloaded different torrents and I could see them all on my cellphone. But I still can't access the remote UI on my laptop.

**Comment by haugene** [comment] 2018-01-24 10:37
Hmm. That's weird. Sounds like a SSL error message, are you trying to access it using http or https? https requires more custom config and setup in the proxy.

**Comment by SyRaza** [comment] 2018-01-24 15:47
That's the ticket. I have the HTTPS Everywhere extension/addon for both chrome and firefox. Now, I did turn the extension off and try to use http instead of https but I still keep getting redirected to https for some reason.

I came about this [#51](https://github.com/haugene/docker-transmission-openvpn/issues/51) where someone else was going through the same issue. Sorry, I'm still a novice at this so I can't figure out how to edit the .conf file for the proxy. 

Thanks.

**Comment by haugene** [comment] 2018-01-24 15:53
You need to write a new config file and mount it into the proxy container in that case. And generate the required ssl certificates.

**Comment by SyRaza** [comment] 2018-01-25 16:50
OK, I give up. 

So I installed the proxy the way it's mentioned in the readme, instead of installing nginx like in #51.

However, I did use his format for the .conf file that I made and then uploaded it to my DS and mounted in the proxy container. Now I can't figure out how to generate the SSL certificates. I know I have to generate the cert through let's encrypt (I think). Any suggestions on what I should read next?

Thanks for all your time Haugene.

**Comment by haugene** [comment] 2018-01-25 17:10
That issue is from before the proxy container existed, so he was trying to create that. And the Transmission WebUI isn't https if you haven't done something fancy to it. I would rather set up the nginx to serve https and expose that through your router. Then you can proxy the traffic to transmission on http, which is ok as you are on the local network or even just between containers.

My nginx.conf looks like this:
```
events {
  worker_connections 1024;
}

http {

  server {
    listen 9090 ssl;
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    location / {
      proxy_pass http://openvpn:9091;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # HTTP 1.1 support
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
  }

}
```

Where it's linked to my openvpn-transmission conatiner called `openvpn` and i've mounted the nginx.crt and nginx.key on the locations you see there.

It's an old config and I'm using self signed certificates (not proud of it). If I was to set it up again today, and hopefully I'll do a new setup soon, I'd use caddyserver and get automatic https through letsencrypt. GL HF 😄

**Comment by SyRaza** [comment] 2018-01-30 04:55
just chiming in, I've been trying to get caddy server up and running and man is it a mess to have run on the diskstation. I'll report back to you once I have it up and running. I have someone in the caddy forums helping me.

**Comment by haugene** [comment] 2018-02-05 22:48
Closing this now as the issue is resolved. Still interested if you make any progress on configuring caddy. Would be nice to have automatic https in a proxy image.

I've been contemplating on such a setup for a while. Think I'll do a new setup of my server when ubuntu server 18.04 LTS is available, maybe I'll get to it then :)

**Closed by haugene** 2018-02-05 22:48 UTC
