### ISSUE TITLE
Escaping special characters in environment options

### ISSUE THREAD

**Issue by haugene** [haugene/docker-transmission-openvpn#245] opened 2017-05-10 13:20 UTC
I'm creating this issue as a follow up of #166 and #241. It seems that the templating solution for Transmission options is not too happy when special characters are used.

For now the fix is to stay clear of non-alphanumerical characters, but it would be nice to add support for escaping them somehow. It needs to be done in a couple of places as the openvpn startup script is the one that reads and persists these values, and that they are then sourced into the transmission startup script.

**Comment by Forage** [comment] 2017-09-04 12:00
I just ran into the same issue. As a work-around when dealing with URLs: Use something like https://tinyurl.com to generate a different URL.

**Comment by nebhead** [comment] 2017-09-06 01:46
Thanks!  This fixed the issue.

**Comment by embedded-crypto** [comment] 2020-03-23 00:10
Hi Haugene,

I faced the same problem that WebUI authentication fails. The problem is that the password can contain special characters, such as, ;!@#$%^&.

information flows from ENV in Dockerfiles , dockerize environment-variables.tmpl:environment-variables.sh, to dockerize settings.tmpl:settings.json. If we fix environment-variables.tmpl, the other flow is no problem.

I think we don't need to escape characters on all environment variables.
So I just fixed this issue modifying environment-variables.tmpl embracing TRANSMISSION_RPC_PASSWORD with a single quote. 

May I request a pull request on this issue?


> I'm creating this issue as a follow up of #166 and #241. It seems that the templating solution for Transmission options is not too happy when special characters are used.
> 
> For now the fix is to stay clear of non-alphanumerical characters, but it would be nice to add support for escaping them somehow. It needs to be done in a couple of places as the openvpn startup script is the one that reads and persists these values, and that they are then sourced into the transmission startup script.

**Comment by haugene** [comment] 2020-03-25 08:40
@embedded-crypto Yes please, that would be great :)

**Comment by jocel1rondeau** [comment] 2020-03-31 07:30
Hello, since this change I had to remove a single quote I had in my password because it would throw an error (unexpected EOF). Do you know how I can escape it?

**Comment by pkishino** [comment] 2020-06-02 04:17
> Hello, since this change I had to remove a single quote I had in my password because it would throw an error (unexpected EOF). Do you know how I can escape it?

try with `\'`

**Comment by jocel1rondeau** [comment] 2020-06-02 09:33
Nope, still
`Transmission startup script complete.

/etc/transmission/environment-variables.sh: line 52: unexpected EOF while looking for matching `''

/etc/transmission/environment-variables.sh: line 102: syntax error: unexpected end of file

[2020-06-02 10:30:58.235] JSON parse failed in /config/transmission-home/settings.json at pos 1649: SPECIAL_EXPECTED -- remaining text "<no value>,

    "`

**Comment by pkishino** [comment] 2020-06-02 09:59
hmm, I tried a new build by setting double quote around RPC password in the settings_template..seems to do the trick , I could use password with single quote, escaped using \

**Comment by jocel1rondeau** [comment] 2020-06-02 10:36
So, I'm using the `TRANSMISSION_RPC_PASSWORD` environment variable. I tried the password wrapped with double quotes, with `\` in front of the single quote, tried without the back slash, with no double quotes, etc. Always the same result. Last I tried was doubling the single quote. This works as in the container starts, but the password ignores the quote completely. 
I mean it's not blocking at the moment. I know I have to avoid single quotes in my password, that's fine.

Thanks for your time 👍

**Comment by pkishino** [comment] 2020-06-02 10:37
you need to checkout my PR and build locally for the fix to work as it has not been merged in yet and no image with this fix yet..

**Comment by jocel1rondeau** [comment] 2020-06-02 10:40
🤦 got it, will checkout

**Closed** 2020-06-02 11:57 UTC
Labels: enhancement

**Comment by haugene** [comment] 2020-06-02 11:59
Merged now, should be available on the :latest tag.

**Comment by jocel1rondeau** [comment] 2020-06-02 13:02
👍 works now, all good
