### ISSUE TITLE
HELP: Stuck in (Temporary failure in name resolution) loop.

### ISSUE THREAD

**Issue by attzonko** [haugene/docker-transmission-openvpn#1322] opened 2020-08-09 02:39 UTC
I just found my container stuck in a restart loop, here is what I see in the log
```
last Thursday at 11:37 PM Thu Aug  6 23:37:30 2020 [us-lax-011.mullvad.net] Inactivity timeout (--ping-restart), restarting
last Thursday at 11:37 PM Thu Aug  6 23:37:30 2020 SIGUSR1[soft,ping-restart] received, process restarting
last Thursday at 11:37 PM Thu Aug  6 23:37:30 2020 Restart pause, 5 second(s)
last Thursday at 11:37 PM Thu Aug  6 23:37:35 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
last Thursday at 11:37 PM Thu Aug  6 23:37:35 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]89.46.114.145:1197
last Thursday at 11:37 PM Thu Aug  6 23:37:35 2020 Socket Buffers: R=[212992->425984] S=[212992->425984]
last Thursday at 11:37 PM Thu Aug  6 23:37:35 2020 NOTE: setsockopt TCP_NODELAY=1 failed
last Thursday at 11:37 PM Thu Aug  6 23:37:35 2020 UDP link local: (not bound)
last Thursday at 11:37 PM Thu Aug  6 23:37:35 2020 UDP link remote: [AF_INET]89.46.114.145:1197
last Thursday at 11:38 PM Thu Aug  6 23:38:35 2020 [UNDEF] Inactivity timeout (--ping-restart), restarting
last Thursday at 11:38 PM Thu Aug  6 23:38:35 2020 SIGUSR1[soft,ping-restart] received, process restarting
last Thursday at 11:38 PM Thu Aug  6 23:38:35 2020 Restart pause, 5 second(s)
last Thursday at 11:38 PM Thu Aug  6 23:38:40 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
last Thursday at 11:38 PM Thu Aug  6 23:38:50 2020 RESOLVE: Cannot resolve host address: us-lax-012.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:39 PM Thu Aug  6 23:39:00 2020 RESOLVE: Cannot resolve host address: us-lax-012.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:39 PM Thu Aug  6 23:39:00 2020 Could not determine IPv4/IPv6 protocol
last Thursday at 11:39 PM Thu Aug  6 23:39:00 2020 SIGUSR1[soft,init_instance] received, process restarting
last Thursday at 11:39 PM Thu Aug  6 23:39:00 2020 Restart pause, 5 second(s)
last Thursday at 11:39 PM Thu Aug  6 23:39:05 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
last Thursday at 11:39 PM Thu Aug  6 23:39:15 2020 RESOLVE: Cannot resolve host address: us-lax-202.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:39 PM Thu Aug  6 23:39:25 2020 RESOLVE: Cannot resolve host address: us-lax-202.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:39 PM Thu Aug  6 23:39:25 2020 Could not determine IPv4/IPv6 protocol
last Thursday at 11:39 PM Thu Aug  6 23:39:25 2020 SIGUSR1[soft,init_instance] received, process restarting
last Thursday at 11:39 PM Thu Aug  6 23:39:25 2020 Restart pause, 5 second(s)
last Thursday at 11:39 PM Thu Aug  6 23:39:30 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
last Thursday at 11:39 PM Thu Aug  6 23:39:40 2020 RESOLVE: Cannot resolve host address: us-lax-016.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:39 PM Thu Aug  6 23:39:50 2020 RESOLVE: Cannot resolve host address: us-lax-016.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:39 PM Thu Aug  6 23:39:50 2020 Could not determine IPv4/IPv6 protocol
last Thursday at 11:39 PM Thu Aug  6 23:39:50 2020 SIGUSR1[soft,init_instance] received, process restarting
last Thursday at 11:39 PM Thu Aug  6 23:39:50 2020 Restart pause, 5 second(s)
last Thursday at 11:39 PM Thu Aug  6 23:39:55 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
last Thursday at 11:40 PM Thu Aug  6 23:40:05 2020 RESOLVE: Cannot resolve host address: us-lax-102.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:40 PM Thu Aug  6 23:40:15 2020 RESOLVE: Cannot resolve host address: us-lax-102.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:40 PM Thu Aug  6 23:40:15 2020 Could not determine IPv4/IPv6 protocol
last Thursday at 11:40 PM Thu Aug  6 23:40:15 2020 SIGUSR1[soft,init_instance] received, process restarting
last Thursday at 11:40 PM Thu Aug  6 23:40:15 2020 Restart pause, 5 second(s)
last Thursday at 11:40 PM Thu Aug  6 23:40:20 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
last Thursday at 11:40 PM Thu Aug  6 23:40:30 2020 RESOLVE: Cannot resolve host address: us-lax-302.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:40 PM Thu Aug  6 23:40:40 2020 RESOLVE: Cannot resolve host address: us-lax-302.mullvad.net:1197 (Temporary failure in name resolution)
```

Pinging any of the addresses from the log file, they seem to be available:
```
$ ping us-lax-102.mullvad.net
PING us-lax-102.mullvad.net (198.54.129.74) 56(84) bytes of data.
64 bytes from static-198-54-129-74.cust.tzulo.com (198.54.129.74): icmp_seq=1 ttl=55 time=26.1 ms
64 bytes from static-198-54-129-74.cust.tzulo.com (198.54.129.74): icmp_seq=2 ttl=55 time=54.8 ms
64 bytes from static-198-54-129-74.cust.tzulo.com (198.54.129.74): icmp_seq=3 ttl=55 time=81.2 ms
```

Any ideas about what could be wrong?

EDIT: By the way, this was working fine for a few days.

**Comment by haugene** [comment] 2020-08-09 17:14
This is a DNS issue. What options are you running the container with? https://haugene.github.io/docker-transmission-openvpn/known-issues/#use_google_dns_servers

Also see my comments in #1306 or search other issues. There has been many of them.

**Comment by attzonko** [comment] 2020-08-09 19:00
I have set the dns to 1.1.1.1 and 8.8.8.8.

**Comment by attzonko** [comment] 2020-08-09 20:11
Here is my full container config:
```
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: always
    healthcheck:
      disable: true
    networks:
      - t2_proxy
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    security_opt:
      - no-new-privileges:true
    ports:
      - "$TRANSMISSION_PORT:9091"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/transmission/data:/data
      - $DOCKERDIR/transmission/config:/config
      - $USERDIR/downloads:/downloads
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ

      OPENVPN_PROVIDER: MULLVAD
      OPENVPN_USERNAME: $MULLVAD_ACCOUNT
      OPENVPN_PASSWORD: m
      OPENVPN_CONFIG: mullvad_us-ca_udp
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60

      LOCAL_NETWORK: "$LOCAL_NETWORK"
      ENABLE_UFW: 'true'

      TRANSMISSION_PEER_PORT_RANDOM_ON_START: 'false'
      TRANSMISSION_PEER_PORT: $MULLVAD_PORT
      TRANSMISSION_RATIO_LIMIT: 0
      TRANSMISSION_RATIO_LIMIT_ENABLED: 'true'
      TRANSMISSION_ENCRYPTION: 2
      TRANSMISSION_UTP_ENABLED: 'false'
      TRANSMISSION_PEER_LIMIT_GLOBAL: 1000
      TRANSMISSION_PEER_LIMIT_PER_TORRENT: 100
      TRANSMISSION_RPC_WHITELIST_ENABLED: 'false'
      TRANSMISSION_RPC_HOST_WHITELIST_ENABLED: 'false'
      TRANSMISSION_UMASK: 2
      TRANSMISSION_INCOMPLETE_DIR: /downloads/incomplete
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: 'true'
      TRANSMISSION_WATCH_DIR: /downloads
      TRANSMISSION_WATCH_DIR_ENABLED: 'true'
      TRANSMISSION_DOWNLOAD_DIR: /downloads/completed
```

**Comment by attzonko** [comment] 2020-08-09 20:15
By the way thanks for responding. Looking at the #1306 issue, I think my best bet will be to restart the container on a daily basis via cron, and hope the timing of that restart does not cause issues with sonarr/radarr/etc.

**Comment by haugene** [comment] 2020-08-09 20:24
Sometimes the "stupid" solution is effective and good enough 😄 

Your config looks good to me, but... You are getting `Inactivity timeout (--ping-restart)` which you should not since you have added the ping-exit flag in your options. The mullvad [config you are using](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/mullvad/mullvad_us-ca_udp.ovpn) has the ping-restart option in it but the command line argument should override it.

Curious if you get any options pushed from Mullvad servers after you connect. They can update the clients. You should see that in your startup connection logs. You could add another option to ignore their update when it comes to ping directives. Add this to your OPENVPN_OPTS: `--pull-filter ignore ping`

Good luck. Let me know how it goes ;)

**Comment by attzonko** [comment] 2020-08-09 21:06
Here is the log from the startup, if it will give you some clues as to what is going on, I redacted my IP addresses and MAC Address
```
today at 2:42 AM Using OpenVPN provider: MULLVAD
today at 2:42 AM Starting OpenVPN using config mullvad_us-ca_udp.ovpn
today at 2:42 AM Setting OPENVPN credentials...
today at 2:42 AM enabling firewall
today at 2:42 AM Firewall is active and enabled on system startup
today at 2:42 AM allowing 21475 through the firewall
today at 2:42 AM Rule added
today at 2:42 AM allowing YYY.YYY.YYY.1 through the firewall to port 9091
today at 2:42 AM Rule added
today at 2:42 AM adding route to local network XXX.XXX.XXX.0/24 via YYY.YYY.YYY.1 dev eth0
today at 2:42 AM allowing XXX.XXX.XXX.0/24 through the firewall to port 9091
today at 2:42 AM Rule added
today at 2:42 AM adding route to local network YYY.YYY.YYY.0/24 via YYY.YYY.YYY.1 dev eth0
today at 2:42 AM allowing YYY.YYY.YYY.YYY/24 through the firewall to port 9091
today at 2:42 AM Rule added
today at 2:42 AM Sun Aug  9 02:42:03 2020 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
today at 2:42 AM Sun Aug  9 02:42:03 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
today at 2:42 AM Sun Aug  9 02:42:03 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
today at 2:42 AM Sun Aug  9 02:42:03 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
today at 2:42 AM Sun Aug  9 02:42:03 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]198.54.129.74:1197
today at 2:42 AM Sun Aug  9 02:42:03 2020 Socket Buffers: R=[212992->425984] S=[212992->425984]
today at 2:42 AM Sun Aug  9 02:42:03 2020 UDP link local: (not bound)
today at 2:42 AM Sun Aug  9 02:42:03 2020 UDP link remote: [AF_INET]198.54.129.74:1197
today at 2:42 AM Sun Aug  9 02:42:03 2020 TLS: Initial packet from [AF_INET]198.54.129.74:1197, sid=496a9b00 d4670b5b
today at 2:42 AM Sun Aug  9 02:42:03 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
today at 2:42 AM Sun Aug  9 02:42:04 2020 VERIFY OK: depth=2, C=SE, ST=Gotaland, L=Gothenburg, O=Amagicom AB, OU=Mullvad, CN=Mullvad Root CA v2, emailAddress=security@mullvad.net
today at 2:42 AM Sun Aug  9 02:42:04 2020 VERIFY OK: depth=1, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=Mullvad Intermediate CA v2, emailAddress=security@mullvad.net
today at 2:42 AM Sun Aug  9 02:42:04 2020 VERIFY KU OK
today at 2:42 AM Sun Aug  9 02:42:04 2020 Validating certificate extended key usage
today at 2:42 AM Sun Aug  9 02:42:04 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
today at 2:42 AM Sun Aug  9 02:42:04 2020 VERIFY EKU OK
today at 2:42 AM Sun Aug  9 02:42:04 2020 VERIFY OK: depth=0, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=us-lax-102.mullvad.net, emailAddress=security@mullvad.net
today at 2:42 AM Sun Aug  9 02:42:04 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1557', remote='link-mtu 1558'
today at 2:42 AM Sun Aug  9 02:42:04 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
today at 2:42 AM Sun Aug  9 02:42:04 2020 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_CHACHA20_POLY1305_SHA256, 4096 bit RSA
today at 2:42 AM Sun Aug  9 02:42:04 2020 [us-lax-102.mullvad.net] Peer Connection Initiated with [AF_INET]198.54.129.74:1197
today at 2:42 AM Sun Aug  9 02:42:05 2020 SENT CONTROL [us-lax-102.mullvad.net]: 'PUSH_REQUEST' (status=1)
today at 2:42 AM Sun Aug  9 02:42:10 2020 SENT CONTROL [us-lax-102.mullvad.net]: 'PUSH_REQUEST' (status=1)
today at 2:42 AM Sun Aug  9 02:42:10 2020 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.11.0.1,redirect-gateway def1 bypass-dhcp,route-ipv6 0000::/2,route-ipv6 4000::/2,route-ipv6 8000::/2,route-ipv6 C000::/2,comp-lzo no,route-gateway 10.11.0.1,topology subnet,socket-flags TCP_NODELAY,ifconfig-ipv6 fdda:d0d0:cafe:1197::100b/64 fdda:d0d0:cafe:1197::,ifconfig 10.11.0.13 255.255.0.0,peer-id 11,cipher AES-256-GCM'
today at 2:42 AM Sun Aug  9 02:42:10 2020 OPTIONS IMPORT: compression parms modified
today at 2:42 AM Sun Aug  9 02:42:10 2020 OPTIONS IMPORT: --socket-flags option modified
today at 2:42 AM Sun Aug  9 02:42:10 2020 NOTE: setsockopt TCP_NODELAY=1 failed
today at 2:42 AM Sun Aug  9 02:42:10 2020 OPTIONS IMPORT: --ifconfig/up options modified
today at 2:42 AM Sun Aug  9 02:42:10 2020 OPTIONS IMPORT: route options modified
today at 2:42 AM Sun Aug  9 02:42:10 2020 OPTIONS IMPORT: route-related options modified
today at 2:42 AM Sun Aug  9 02:42:10 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
today at 2:42 AM Sun Aug  9 02:42:10 2020 OPTIONS IMPORT: peer-id set
today at 2:42 AM Sun Aug  9 02:42:10 2020 OPTIONS IMPORT: adjusting link_mtu to 1624
today at 2:42 AM Sun Aug  9 02:42:10 2020 OPTIONS IMPORT: data channel crypto options modified
today at 2:42 AM Sun Aug  9 02:42:10 2020 Data Channel: using negotiated cipher 'AES-256-GCM'
today at 2:42 AM Sun Aug  9 02:42:10 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
today at 2:42 AM Sun Aug  9 02:42:10 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
today at 2:42 AM Sun Aug  9 02:42:10 2020 ROUTE_GATEWAY YYY.YYY.YYY.1/255.255.0.0 IFACE=eth0 HWADDR=AA:BB:CC:DD:EE:FF
today at 2:42 AM Sun Aug  9 02:42:10 2020 GDG6: remote_host_ipv6=n/a
today at 2:42 AM Sun Aug  9 02:42:10 2020 ROUTE6: default_gateway=UNDEF
today at 2:42 AM Sun Aug  9 02:42:10 2020 TUN/TAP device tun0 opened
today at 2:42 AM Sun Aug  9 02:42:10 2020 TUN/TAP TX queue length set to 100
today at 2:42 AM Sun Aug  9 02:42:10 2020 /sbin/ip link set dev tun0 up mtu 1500
today at 2:42 AM Sun Aug  9 02:42:10 2020 /sbin/ip addr add dev tun0 10.11.0.13/16 broadcast 10.11.255.255
today at 2:42 AM Sun Aug  9 02:42:10 2020 /sbin/ip -6 addr add fdda:d0d0:cafe:1197::100b/64 dev tun0
today at 2:42 AM Sun Aug  9 02:42:10 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1552 10.11.0.13 255.255.0.0 init
today at 2:42 AM Up script executed with tun0 1500 1552 10.11.0.13 255.255.0.0 init
today at 2:42 AM Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.11.0.13
today at 2:42 AM Generating transmission settings.json from env variables
today at 2:42 AM sed'ing True to true
today at 2:42 AM Enforcing ownership on transmission config directories
today at 2:42 AM Applying permissions to transmission config directories
today at 2:42 AM Setting owner for transmission paths to 1000:998
today at 2:42 AM Setting permission for files (644) and directories (755)
today at 2:42 AM Setting permission for watch directory (775) and its files (664)
today at 2:42 AM
today at 2:42 AM -------------------------------------
today at 2:42 AM Transmission will run as
today at 2:42 AM -------------------------------------
today at 2:42 AM User name:   abc
today at 2:42 AM User uid:    1000
today at 2:42 AM User gid:    998
today at 2:42 AM -------------------------------------
today at 2:42 AM
today at 2:42 AM STARTING TRANSMISSION
today at 2:42 AM NO PORT UPDATER FOR THIS PROVIDER
today at 2:42 AM Transmission startup script complete.
today at 2:42 AM Sun Aug  9 02:42:10 2020 /sbin/ip route add 198.54.129.74/32 via YYY.YYY.YYY.1
today at 2:42 AM Sun Aug  9 02:42:10 2020 /sbin/ip route add 0.0.0.0/1 via 10.11.0.1
today at 2:42 AM Sun Aug  9 02:42:10 2020 /sbin/ip route add 128.0.0.0/1 via 10.11.0.1
today at 2:42 AM Sun Aug  9 02:42:10 2020 add_route_ipv6(::/2 -> fdda:d0d0:cafe:1197:: metric -1) dev tun0
today at 2:42 AM Sun Aug  9 02:42:10 2020 /sbin/ip -6 route add ::/2 dev tun0
today at 2:42 AM Sun Aug  9 02:42:10 2020 add_route_ipv6(4000::/2 -> fdda:d0d0:cafe:1197:: metric -1) dev tun0
today at 2:42 AM Sun Aug  9 02:42:10 2020 /sbin/ip -6 route add 4000::/2 dev tun0
today at 2:42 AM Sun Aug  9 02:42:10 2020 add_route_ipv6(8000::/2 -> fdda:d0d0:cafe:1197:: metric -1) dev tun0
today at 2:42 AM Sun Aug  9 02:42:10 2020 /sbin/ip -6 route add 8000::/2 dev tun0
today at 2:42 AM Sun Aug  9 02:42:10 2020 add_route_ipv6(c000::/2 -> fdda:d0d0:cafe:1197:: metric -1) dev tun0
today at 2:42 AM Sun Aug  9 02:42:10 2020 /sbin/ip -6 route add c000::/2 dev tun0
today at 2:42 AM Sun Aug  9 02:42:10 2020 Initialization Sequence Completed
today at 3:42 AM Sun Aug  9 03:42:04 2020 TLS: soft reset sec=0 bytes=2477958/-1 pkts=12277/0
today at 3:42 AM Sun Aug  9 03:42:04 2020 VERIFY OK: depth=2, C=SE, ST=Gotaland, L=Gothenburg, O=Amagicom AB, OU=Mullvad, CN=Mullvad Root CA v2, emailAddress=security@mullvad.net
today at 3:42 AM Sun Aug  9 03:42:04 2020 VERIFY OK: depth=1, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=Mullvad Intermediate CA v2, emailAddress=security@mullvad.net
today at 3:42 AM Sun Aug  9 03:42:04 2020 VERIFY KU OK
today at 3:42 AM Sun Aug  9 03:42:04 2020 Validating certificate extended key usage
today at 3:42 AM Sun Aug  9 03:42:04 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
today at 3:42 AM Sun Aug  9 03:42:04 2020 VERIFY EKU OK
today at 3:42 AM Sun Aug  9 03:42:04 2020 VERIFY OK: depth=0, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=us-lax-102.mullvad.net, emailAddress=security@mullvad.net
today at 3:42 AM Sun Aug  9 03:42:04 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1557', remote='link-mtu 1558'
today at 3:42 AM Sun Aug  9 03:42:04 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
today at 3:42 AM Sun Aug  9 03:42:04 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
today at 3:42 AM Sun Aug  9 03:42:04 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
today at 3:42 AM Sun Aug  9 03:42:04 2020 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_CHACHA20_POLY1305_SHA256, 4096 bit RSA
today at 4:42 AM Sun Aug  9 04:42:04 2020 TLS: soft reset sec=0 bytes=3198206/-1 pkts=15972/0
today at 4:42 AM Sun Aug  9 04:42:04 2020 VERIFY OK: depth=2, C=SE, ST=Gotaland, L=Gothenburg, O=Amagicom AB, OU=Mullvad, CN=Mullvad Root CA v2, emailAddress=security@mullvad.net
today at 4:42 AM Sun Aug  9 04:42:04 2020 VERIFY OK: depth=1, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=Mullvad Intermediate CA v2, emailAddress=security@mullvad.net
today at 4:42 AM Sun Aug  9 04:42:04 2020 VERIFY KU OK
today at 4:42 AM Sun Aug  9 04:42:04 2020 Validating certificate extended key usage
today at 4:42 AM Sun Aug  9 04:42:04 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
today at 4:42 AM Sun Aug  9 04:42:04 2020 VERIFY EKU OK
today at 4:42 AM Sun Aug  9 04:42:04 2020 VERIFY OK: depth=0, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=us-lax-102.mullvad.net, emailAddress=security@mullvad.net
today at 4:42 AM Sun Aug  9 04:42:04 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1557', remote='link-mtu 1558'
today at 4:42 AM Sun Aug  9 04:42:04 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
today at 4:42 AM Sun Aug  9 04:42:04 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
today at 4:42 AM Sun Aug  9 04:42:04 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
today at 4:42 AM Sun Aug  9 04:42:04 2020 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_CHACHA20_POLY1305_SHA256, 4096 bit RSA
```

**Comment by haugene** [comment] 2020-08-10 08:18
Hmm. No definitive answers. But you see that they are pushing some options as I mentioned:

```
today at 2:42 AM Sun Aug  9 02:42:04 2020 [us-lax-102.mullvad.net] Peer Connection Initiated with [AF_INET]198.54.129.74:1197
today at 2:42 AM Sun Aug  9 02:42:05 2020 SENT CONTROL [us-lax-102.mullvad.net]: 'PUSH_REQUEST' (status=1)
today at 2:42 AM Sun Aug  9 02:42:10 2020 SENT CONTROL [us-lax-102.mullvad.net]: 'PUSH_REQUEST' (status=1)
```

Can't see any trace that ping-restart is one of them, but not sure that is necessarily logged either. If you want to get to the bottom of this we can try some debug statements and modify the configs on the dev branch in a couple of days. Just need to make it stable again first, doing larger changes there these days.

**Comment by attzonko** [comment] 2020-08-15 02:59
No worries, whenever you have time. I can confirm that it still gets in this state almost daily. It would be nice to get to the bottom of it. Let me know how I can help when you are ready to debug further.

**Comment by willsy555** [comment] 2020-08-18 21:05
I will be interested to see what the issue is here. I get the same issue with a different VPN provider. It has started happening since I switched to docker compose and thought it was something to do with that. Was using Google DNS but read that using the routers IP for DNS can fix this issue (somewhere - not sure where)... Just trying that out now.

**Comment by willsy555** [comment] 2020-08-27 16:30
Tried with my router IP as the DNS (192.168.1.1) & also tried without a DNS (not even Google) entry in the docker-compose yaml. Still no joy, same problem as above every day or so...

**Comment by RickyXwang** [comment] 2020-08-27 23:08
Hey, I might have found a way to fix this, check out the issue #1306 and let me know if that work for you.

**Closed** 2020-11-03 00:46 UTC
Labels: inactivity

**Comment by haugene** [comment] 2020-11-03 21:49
Hey again @attzonko. I dropped the ball on this and the issue got closed. I have added this option since we last spoke though:
```
OVERRIDE_DNS_1=8.8.8.8
OVERRIDE_DNS_2=8.8.4.4
```
On container startup if these variables are present (and as many as you want, alphabetically ordered) the values will be added (and overwriting) the /etc/resolv.conf

I still don't know why. But there is something happening with DNS in Docker from time to time :thinking:

**Comment by attzonko** [comment] 2020-11-03 22:42
Ok, here some additional data points for you along with some questions.

In thought in the docker-compose file, I already overwrite the DNS, are the override environment variables an additional override needed?
```
dns:
  - 1.1.1.1
  - 8.8.8.8
```

I used a cron job to restart the container when I detected that the container can't reach the DNS servers. The cron job runs every 10 minutes. The script is a simple bash script, I am including it for reference if others wish to take advantage of it:
```
#!/bin/bash

# Make sure we have a working internet connection first on the host
if /usr/bin/ping 1.1.1.1 -c 1 -W 5 > /dev/null; then
        # check if transmission container is in a bad state
        if ! /usr/bin/docker exec transmission ping 1.1.1.1 -c 1 -W 5 > /dev/null; then
            echo "Transmission is dead in the water, restarting"
            /usr/bin/docker restart transmission
        fi
fi
```

The last time I saw the issue was Oct 15. In the screenshot of my cron emails you can see the relative frequency of hitting this:
![image](https://user-images.githubusercontent.com/4975715/98048373-676dde00-1de2-11eb-89b7-696f6406aea8.png)

**Comment by haugene** [comment] 2020-11-03 22:50
I believe that the override environment variables could help. Although I can't say for sure and that's why I want you to test.
You've been running two weeks without issue now, so it could be resolved?

Anyways. The environment variable override will actually rewrite /etc/resolv.conf. If you exec into the container now and look at /etc/resolv.conf it is not set to the servers you provide. So that means (I think) that this is set up in a Docker DNS server somehow. It also makes sense because when you're running Docker in a compose file you will have DNS lookup to other services in the same network. So Docker is doing something and at this point after years of issues with DNS I cannot do anything else than suspect the Docker stuff, maybe in combination with us running a VPN connection somehow fails at times :man_shrugging:

**Comment by attzonko** [comment] 2020-11-03 22:56
I will add the overrides and hope the stability I have seen over the last 2 weeks continues. Another change on my end is I started using watchtower to update the containers automatically whenever there is a new image released. So I saw that this image got updated a few times over the last two weeks, which means it was restarted by watchtower and not my corn job. 

Anyway, thanks for following up and trying to fix this, I totally buy it is a docker problem 👍

**Comment by attzonko** [comment] 2021-04-20 21:01
Just wanted to get back to you on this. I realized my corn job stopped emailing because of an SMTP problem, this issue itself is not fixed. Here is a quick snapshot of the current frequency:
![image](https://user-images.githubusercontent.com/4975715/115463530-c385bc80-a1e0-11eb-9fc3-c00754d759aa.png)

And by the way I am using the override env variables:
```
      OVERRIDE_DNS_1: 1.1.1.1
      OVERRIDE_DNS_2: 8.8.8.8
```
