### ISSUE TITLE
Change download directory?

### ISSUE THREAD

**Issue by realcanadrian** [haugene/docker-transmission-openvpn#1087] opened 2020-03-22 19:57 UTC
Is is possible to change the download directory? I want to download to a volume at a location other than /data, but even when I change it in the Transmission settings, a container restart resets the download location to /data. I know I can mount whatever path I like to /data, but my other docker containers expect a consistent file path between each other, and I don't want to change every other docker container to match this one.

**Comment by pkishino** [comment] 2020-03-22 22:32
You can set both variables as per wiki

**Comment by realcanadrian** [comment] 2020-03-22 22:34
> You can set both variables as per wiki

There's nothing (at all) in [the wiki](https://github.com/haugene/docker-transmission-openvpn/wiki) unless I'm missing something...

**Comment by pkishino** [comment] 2020-03-22 22:44
It mentions your can and how to override transmission configuration
options.. so you can set download directory and then change it from /data
to whatever you want

**Comment by realcanadrian** [comment] 2020-03-22 22:48
![Screen Shot 2020-03-22 at 16 47 20](https://user-images.githubusercontent.com/19540360/77263045-e26ff300-6c5c-11ea-855a-97628c54981b.png)
This is the wiki. I'm looking at it. There's literally nothing here. Are you talking about something else?

**Comment by pkishino** [comment] 2020-03-22 22:50
Sorry, but wiki I mean documentation, linked in read me

**Comment by realcanadrian** [comment] 2020-03-22 23:08
Oh, ok. So it looks like I would add:
```
  -e TRANSMISSION_DOWNLOAD_DIR="/home/username/media/storage/Downloads/complete/torrent/" \
  -e TRANSMISSION_INCOMPLETE_DIR="/home/username/media/storage/Downloads/incomplete/torrent/" \
  -e TRANSMISSION_INCOMPLETE_DIR_ENABLED=true \
```
Just out of curiosity, what is the reason every preference set through the GUI is overwritten on every reboot?

**Comment by scandinave** [comment] 2020-03-25 10:39
I think it's because transmission run inside docker and the config is not export outside of it. So at each restart, a new config is created base on your docker run parameters

**Comment by haugene** [comment] 2020-03-25 11:40
Looks correct @realcanadrian. Given that you mount a volume at /home/username/media etc...

The reason it is regenerated on every restart is a bit of a mix:
- It makes the container easy to move between servers. Easy to reproduce. This was something I liked and prioritised when I built it - although I have a feeling that most people find it annoying these days.
- We are actually changing some properties on every restart. Based on what IP you're assigned by the VPN, we bind to it in order to limit transmission engine to listen only to traffic from VPN.
- It was thought to make it simple in some NAS setups. They list all environment variables in the GUI and then you'd have one place to set it all on setup.

That being said - I am looking at making it optional these days. Developing a new beta branch with many changes where a persistent settings.json is one of them. But making it backward compatible is also a bit of a challenge 😄 

I guess I'll have the new beta out in a week or two. Then we'll see what people think of it and go from there. Check back if you could be interested in testing it.

**Comment by haugene** [comment] 2020-03-29 14:05
Closing for now. Feel free to re-open if there was something else.

**Closed by haugene** 2020-03-29 14:05 UTC
