### ISSUE TITLE
Unraid Docker Paths 

### ISSUE THREAD

**Issue by artkiarmitage** [haugene/docker-transmission-openvpn#1075] opened 2020-03-14 11:03 UTC
Hi,

First of all, I'm a noob, new to UnRaid and even newer to working with Dockers. I'm almost certainly making a silly mistake here. 

I'm trying out this docker on UnRaid which I can't seem to get working. I'm wondering what paths I should put in to the Docker template? 

I want everything this Docker does to fall into a share called 'Torrents'. At the moment this is what I've done: 

Container Path: /data = /mnt/user/Torrents/Transmission

Container Path: /downloads = /mnt/user/Torrents/Transmission/Downloads

Container Path: /watch = /mnt/user/Torrents/Transmission/Watch

Container Variable: TRANSMISSION_DOWNLOAD_DIR = /mnt/user/Torrents/Transmission/Download_Dir

Container Variable: TRANSMISSION_INCOMPLETE_DIR = /mnt/user/Torrents/Transmission/Incomplete

Container Path: /mnt/user/T_Media/Torrent/  = /mnt/user/Torrents/Transmission/Torrent/

Apply permsissions Globally on Transmissions files / Folders = true

I messed around with the above directories before with a small test torrent download. So far the torrent has completed no matter what directories I put in there, but the torrent file never shows up where I expect it to. In fact I can never find where the file ends up on my server...

I've attached the log, which seems to show normal operation? I don't see my files in the folders though... 

Thanks in advance for your help and kindness. 

--

--

[artkiarmitage transmission.log](https://github.com/haugene/docker-transmission-openvpn/files/4332644/artkiarmitage.transmission.log)

**Comment by artkiarmitage** [comment] 2020-03-15 10:12
Nevermind, got it: 

The key was understanding the difference between a 'Path' and a 'Variable' in the UnRaid Docker template. 

'Path' entries refer to actual paths in the array. In this Docker, 'Variables' that ask for a directory are essentially string inputs into Transmission itself. Transmission doesn't know about the existence of other directories, it only knows the ones you gave it. So the correct config should be something like: 

Container Path: /downloads = /mnt/user/Torrents/Transmission/downloads

Container Path: /watch = /mnt/user/Torrents/Transmission/watch

Container Variable: TRANSMISSION_DOWNLOAD_DIR = /download/Download_Dir

Container Variable: TRANSMISSION_INCOMPLETE_DIR = /download/Incomplete

Note that everything is case sensitive. Notice how the variables for the download directory and incomplete directory start from /downloads/.

**Comment by LyhjeHylje** [comment] 2020-04-15 16:12
I also had problems with these. I still cannot understand what the:
"Container Path: /mnt/user/T_Media/Torrent/" -setting is supposed to do. My system started working when I set it same as the "Container Path: /data" but I don't know why the first one even exists.

**Comment by 0mgithub** [comment] 2020-06-01 11:45
Everytime there is an update I manually remove the container path download setting with  /mnt/user/T_Media/Torrent/ because it creates an unnecessary share on Unraid. Maybe @haugene could make it in such a way that it does not automatically get created and is optional?

**Comment by pkishino** [comment] 2020-06-01 17:16
Anyone can create aPR with a fix for this and I’ll review it

**Comment by 0mgithub** [comment] 2020-06-01 17:49
> Anyone can create aPR with a fix for this and I’ll review it

@pkishino thank you for reaching out so quickly. The issue is that several users including me do not know why by default there is always a secondary 'Download' path with both docker and host path the same value where in which it uses this vague **T_Media**. The first 'Download' and 'Watch Folder' make sense and are adjustable, nothing wrong there. But each time @haugene updates his repository with a new version we always get this path back in the template after executing a docker update and it thus creates an empty share over and over even when you manually delete the path and the share. It is just annoying because you have to delete the path and created share each time there is an update. See screenshot for further clarification.

![T_Media_why](https://user-images.githubusercontent.com/66254219/83437819-b2a15080-a440-11ea-9139-dfdd36c44c87.png)

**Comment by pkishino** [comment] 2020-06-01 22:43
I’ll take a look at this today I hope

**Comment by pkishino** [comment] 2020-06-02 04:31
can you please update exactly which docker image you are using and the run command/compose file? I looked at the template and this looks like something unraid specific that is not part of this image..I don't use unraid so not sure

**Comment by 0mgithub** [comment] 2020-06-02 05:05
Dear @pkishino , I found out that when adding Transmission_VPN from haugene through the apps tab you are actually using someone else's xml file as a template on top of the actual docker image that @haugene makes, see screenshot for further clarification. I submitted a pull request in the repository of the creator of this xml file so it stops doing this weird thing for Unraid users. You can find the pull request [here](https://github.com/clowrym/docker-templates/pull/5).
Since haugene has no influence on this proces whatsoever I immediately deleted my comments here to prevent further confusion. I hope this is clear enough for you and thanks again for your efforts.

![transmission_vpn_unraid_apps](https://user-images.githubusercontent.com/66254219/83481908-43a71480-a49f-11ea-8b49-b0bc1bbf4080.png)

**Comment by pkishino** [comment] 2020-06-02 05:21
Ok, thanks for the update, I will close this issue then as it relates to the unraid image, not this repo directly.

**Closed by pkishino** 2020-06-02 05:21 UTC
