### ISSUE TITLE
TLS Errors

### ISSUE THREAD

**Issue by arronb** [haugene/docker-transmission-openvpn#249] opened 2017-05-15 00:53 UTC
I'm getting TLS Errors when trying to connect to nordVPN for some reason. It was working fine for a few days and then not.

`Mon May 15 00:48:40 2017 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)             
Mon May 15 00:48:40 2017 TLS Error: TLS handshake failed                                                                                
Mon May 15 00:48:40 2017 SIGUSR1[soft,tls-error] received, process restarting                                                           
Mon May 15 00:48:40 2017 Restart pause, 2 second(s)                                                                                     
Mon May 15 00:48:42 2017 WARNING: --ping should normally be used with --ping-restart or --ping-exit                                     
Mon May 15 00:48:42 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts          
Mon May 15 00:48:42 2017 Socket Buffers: R=[212992->131072] S=[212992->131072]                                                          
Mon May 15 00:48:42 2017 UDPv4 link local: [undef]                                                                                      
Mon May 15 00:48:42 2017 UDPv4 link remote: [AF_INET]68.235.53.83:1194                                                                  
Mon May 15 00:49:42 2017 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)             
Mon May 15 00:49:42 2017 TLS Error: TLS handshake failed                                                                                
Mon May 15 00:49:42 2017 SIGUSR1[soft,tls-error] received, process restarting                                                           
Mon May 15 00:49:42 2017 Restart pause, 2 second(s)                                 `

I've tried re-creating the container as well as running the providers update script. Any help would be great.

**Comment by rmorais** [comment] 2017-05-24 21:03
I am having the same issue, running on my nas or on my mac.

**Comment by rmorais** [comment] 2017-05-24 21:35
The issue is that ovpn files for NordVpn are outdated. I will try to create a PR in the next couple of days with update config files

**Comment by haugene** [comment] 2017-05-25 17:43
Merged #253 now, can you try again using the `dev` tag @arronb?

**Comment by rmorais** [comment] 2017-05-25 18:53
I pulled the dev tag and I was able to connect to NordVpn.
Using the default config and also using a specific server.

Thanks

**Comment by haugene** [comment] 2017-05-26 11:11
Great. Thanks for providing the fix! Closing this now.

**Closed** 2017-05-26 11:11 UTC
