### ISSUE TITLE
HELP: OVPN.se

### ISSUE THREAD

**Issue by Havrepuff** [haugene/docker-transmission-openvpn#1330] opened 2020-08-15 21:36 UTC
**Which provider?**
 OVPN.se

**Where are the configs?**
Sorry if this is the wrong place to post.

I saw that the configen for sweden.ovpn has been updated but not default one for ovpn has not been updated. I run synology docker and I do not know how to switch to something else. I'm not good at this .thanks for the reply
 

Update default.ovpn Add OVPN.se to providers

Sat Aug 15 21:57:10 2020 us=435908 RESOLVE: Cannot resolve host address: pool.prd.se.ovpn.se:1194 (Name or service not known) | stdout
-- | --

**Comment by schwukas** [comment] 2020-08-19 09:44
_OVPN.se_'s `default.ovpn` ist just a link to `Sweden.ovpn` as far as I can see. I don't quite understand what you are trying to achieve. What exactly is your problem now?

**Comment by Havrepuff** [comment] 2020-08-19 18:20
Im new at this so dont know where to change it ? running docker on a synology. need dom help :)

**Comment by schwukas** [comment] 2020-08-19 18:24
_What_ do you want to change? If you cannot phrase a proper question, you'll have a hard time getting a proper answer. I'm inclined to help if you put some effort in your error description, though.

**Comment by Havrepuff** [comment] 2020-08-19 18:34
I want to change from default to sweden. Where can I make that change? sry for my bad english

**Comment by schwukas** [comment] 2020-08-19 18:38
Well, as far as I can tell the file `default.ovpn` is just a link to the file `Sweden.ovpn`. You can see that if you open the file [here on github](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/ovpn/default.ovpn). It says _symbolic link_ and only has the name to the file `Sweden.ovpn`. So these two files are basically the same. Are you sure, you are not connected to the swedish servers? If you use `default.ovpn` you should be.

**Comment by Havrepuff** [comment] 2020-08-19 18:47
Yes the default sends me to sweden.ovpn. But it is not the right adress. The two first adresses are wrong but the .com is the right ones. How do I change the .se to become .com 

remote pool-1.prd.se.ovpn.se 1194
remote pool-1.prd.se.ovpn.se 1195
remote pool-1.prd.se.ovpn.com 1194
remote pool-1.prd.se.ovpn.com 1195

**Comment by schwukas** [comment] 2020-08-19 18:53
I have never used OVPN. Do you have any other configuration file? Other than the three files that are already available.

In `Sweden.ovpn` it lists only .com addresses so I don't know where the swedish ones come from. Maybe try posting your logs. Just make sure there isn't anything personal or private in there.

**Comment by Havrepuff** [comment] 2020-08-19 19:01
the dufault sends me to the .se adress and not the .com one.

`Using OpenVPN provider: OVPN
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network 192.168.2.0/24 via 172.17.0.1 dev eth0
Wed Aug 19 17:42:52 2020 us=655374 Current Parameter Settings:
Wed Aug 19 17:42:52 2020 us=655457   config = '/etc/openvpn/ovpn/default.ovpn'


Wed Aug 19 17:42:52 2020 us=661841 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Wed Aug 19 17:42:52 2020 us=661872 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Wed Aug 19 17:42:52 2020 us=662216 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Aug 19 17:42:52 2020 us=662712 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Aug 19 17:42:52 2020 us=662746 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Aug 19 17:42:52 2020 us=662771 LZO compression initializing
Wed Aug 19 17:42:52 2020 us=662879 Control Channel MTU parms [ L:1622 D:1184 EF:66 EB:0 ET:0 EL:3 ]
Wed Aug 19 17:42:52 2020 us=768799 RESOLVE: Cannot resolve host address: pool.prd.se.ovpn.se:1194 (Name or service not known)
Wed Aug 19 17:42:52 2020 us=768880 Data Channel MTU parms [ L:1622 D:1450 EF:122 EB:406 ET:0 EL:3 ]
Wed Aug 19 17:42:52 2020 us=768934 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1558,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 1,cipher AES-256-CBC,auth SHA1,keysize 256,tls-auth,key-method 2,tls-client'
Wed Aug 19 17:42:52 2020 us=768957 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1558,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 0,cipher AES-256-CBC,auth SHA1,keysize 256,tls-auth,key-method 2,tls-server'
Wed Aug 19 17:42:52 2020 us=855164 RESOLVE: Cannot resolve host address: pool.prd.se.ovpn.se:1194 (Name or service not known)`

**Comment by Havrepuff** [comment] 2020-08-19 19:09
![setting](https://user-images.githubusercontent.com/69735037/90679271-34df2b00-e260-11ea-8e63-ec3e9219124f.jpg)

**Comment by schwukas** [comment] 2020-08-19 19:11
I'm afraid I cannot help you on this one. I can't find any swedish addresses in the OVPN configs so either you're using some old image or you have somehow mounted another config folder (can you show me the "Volym" tab?) or there is something magical going on, I just don't get.

There is an edit feature if you want to add information. Just click on the three dots above your last answer and add anything there. Double posting becomes messy real quick.

**Comment by schwukas** [comment] 2020-08-19 19:35
Are you actually using the commit from 2016? You should use the latest available image from docker hub.

**Comment by schwukas** [comment] 2020-08-20 06:57
You don't have to put _all_ your answers into the same edited answer. Just don't post two or three times below your original answer. If you just keep on editing, how am I supposed to see, that something has changed.

It's 2020 now. A four year old image will not work properly as you can clearly see. [Here](https://hub.docker.com/r/haugene/transmission-openvpn/tags) you can see, that the latest update has been 8 days ago.

Since this feels more and more like a troll now, I'll leave you to it. Use the latest image and it will work.

**Comment by Havrepuff** [comment] 2020-08-20 10:20
all i need help getting it to read from it defualt to the right ovpn. where do i put config files. how do I go about it? idont use a rls from 2016. thanks for all the help

**Comment by haugene** [comment] 2020-08-20 10:27
This looks like a duplicate of #1282 which was fixed in #1285. The .se remote addresses you refer to are not present in the current version of the project: https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/ovpn/Sweden.ovpn

If you still get errors with .se addresses it should be because you are running on an older version of the image. Remember that just because you run `haugene/transmission-openvpn:latest` does not mean that you actually have the latest version. You will only have the latest version at the time that you first grabbed it. That's just how Docker works.

To upgrade your image you need to pull the update. `docker pull haugene/transmission-openvpn` and then recreate the container. Doing this should solve your issue.

**Comment by haugene** [comment] 2020-08-20 10:28
As for how to pull new version of the image on Synology, I don't know since I don't use it. But Synology Docker documentation or forum should have the answer.

**Comment by Havrepuff** [comment] 2020-08-20 12:06
I did update and it works !!! thx to all your help

**Closed** 2020-08-20 13:10 UTC
