### ISSUE TITLE
Ivacy OpenVPN only default config connects to trackers

### ISSUE THREAD

**Issue by AndrewPetrides** [haugene/docker-transmission-openvpn#829] opened 2019-06-08 09:02 UTC
I have everything working and running perfectly, however, the only time I can connect to torrents (private & public) is through the default Ivacy config file. 

**Describe the problem**
Only the default Ivacy OpenVPN config file allows me to connect to any trackers for both public and private torrents. 

**Logs**

Default below connects to trackers;

> 2019-06-08 08:51:25 | stdout | Sat Jun  8 08:51:25 2019 SIGTERM[hard,] received, process exiting
> -- | -- | --
> 2019-06-08 08:51:25 | stdout | Sat Jun  8 08:51:25 2019 /etc/openvpn/tunnelDown.sh tun0 1500 1560 172.94.21.143 255.255.255.192 init
> 2019-06-08 08:51:25 | stdout | Sat Jun  8 08:51:25 2019 /sbin/ip addr del dev tun0 172.94.21.143/26
> 2019-06-08 08:51:25 | stdout | Sat Jun  8 08:51:25 2019 event_wait : Interrupted system call (code=4)
> 2019-06-08 08:21:04 | stdout | Sat Jun  8 08:21:04 2019 Initialization Sequence Completed
> 2019-06-08 08:21:04 | stdout | Sat Jun  8 08:21:04 2019 ERROR: Linux route add command failed: external program exited with error status: 2
> 2019-06-08 08:21:04 | stdout | RTNETLINK answers: File exists
> 2019-06-08 08:21:02 | stdout | Transmission startup script complete.
> 2019-06-08 08:21:02 | stdout | NO PORT UPDATER FOR THIS PROVIDER
> 2019-06-08 08:21:02 | stdout | STARTING TRANSMISSION
> 2019-06-08 08:21:02 | stdout |  
> 2019-06-08 08:21:02 | stdout | -------------------------------------
> 2019-06-08 08:21:02 | stdout | User gid:    0
> 2019-06-08 08:21:02 | stdout | User uid:    0
> 2019-06-08 08:21:02 | stdout | User name:   root
> 2019-06-08 08:21:02 | stdout | -------------------------------------
> 2019-06-08 08:21:02 | stdout | Transmission will run as
> 2019-06-08 08:21:02 | stdout | -------------------------------------
> 2019-06-08 08:21:02 | stdout |  
> 2019-06-08 08:21:02 | stdout | sed'ing True to true
> 2019-06-08 08:21:02 | stdout | Generating transmission settings.json from env variables
> 2019-06-08 08:21:02 | stdout | Using Transmission Web Control  UI, overriding TRANSMISSION_WEB_HOME
> 2019-06-08 08:21:02 | stdout | Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 172.94.21.143
> 2019-06-08 08:21:02 | stdout | Up script executed with tun0 1500 1560 172.94.21.143 255.255.255.192 init
> 2019-06-08 08:21:02 | stdout | Sat Jun  8 08:21:02 2019 /etc/openvpn/tunnelUp.sh tun0 1500 1560 172.94.21.143 255.255.255.192 init
> 2019-06-08 08:21:02 | stdout | Sat Jun  8 08:21:02 2019 /sbin/ip addr add dev tun0 172.94.21.143/26 broadcast 172.94.21.191
> 2019-06-08 08:21:02 | stdout | Sat Jun  8 08:21:02 2019 /sbin/ip link set dev tun0 up mtu 1500
> 2019-06-08 08:21:02 | stdout | Sat Jun  8 08:21:02 2019 TUN/TAP device tun0 opened
> 2019-06-08 08:21:00 | stdout | Sat Jun  8 08:21:00 2019 [Secure-Server] Peer Connection Initiated with [AF_INET]172.94.21.2:80
> 2019-06-08 08:20:57 | stdout | Sat Jun  8 08:20:57 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> 2019-06-08 08:20:57 | stdout | Sat Jun  8 08:20:57 2019 TCP_CLIENT link remote: [AF_INET]172.94.21.2:80
> 2019-06-08 08:20:57 | stdout | Sat Jun  8 08:20:57 2019 TCP_CLIENT link local: (not bound)
> 2019-06-08 08:20:57 | stdout | Sat Jun  8 08:20:57 2019 TCP connection established with [AF_INET]172.94.21.2:80
> 2019-06-08 08:20:56 | stdout | Sat Jun  8 08:20:56 2019 Attempting to establish TCP connection with [AF_INET]172.94.21.2:80 [nonblock]
> 2019-06-08 08:20:56 | stdout | Sat Jun  8 08:20:56 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]172.94.21.2:80
> 2019-06-08 08:20:51 | stdout | Sat Jun  8 08:20:51 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> 2019-06-08 08:20:51 | stdout | Sat Jun  8 08:20:51 2019 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
> 2019-06-08 08:20:51 | stdout | Sat Jun  8 08:20:51 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
> 2019-06-08 08:20:51 | stdout | Sat Jun  8 08:20:51 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
> 2019-06-08 08:20:51 | stdout | Sat Jun  8 08:20:51 2019 WARNING: file '/etc/openvpn/ivacy/Wdc.key' is group or others accessible
> 2019-06-08 08:20:51 | stdout | adding route to local network 10.0.0.0/24 via 172.17.0.1 dev eth0
> 2019-06-08 08:20:51 | stdout | Setting OPENVPN credentials...
> 2019-06-08 08:20:51 | stdout | No VPN configuration provided. Using default.
> 2019-06-08 08:20:51 | stdout | Using OpenVPN provider: ivacy

This doesn't connect to trackers;
> 
> 2019-06-08 07:22:44 | stdout | Sat Jun  8 07:22:44 2019 SIGTERM[hard,] received, process exiting
> -- | -- | --
> 2019-06-08 07:22:44 | stdout | Sat Jun  8 07:22:44 2019 /etc/openvpn/tunnelDown.sh tun0 1500 1560 172.111.161.200 255.255.255.224 init
> 2019-06-08 07:22:44 | stdout | Sat Jun  8 07:22:44 2019 /sbin/ip addr del dev tun0 172.111.161.200/27
> 2019-06-08 07:22:44 | stdout | Sat Jun  8 07:22:44 2019 event_wait : Interrupted system call (code=4)
> 2019-06-08 07:18:31 | stdout | Sat Jun  8 07:18:31 2019 Initialization Sequence Completed
> 2019-06-08 07:18:31 | stdout | Sat Jun  8 07:18:31 2019 ERROR: Linux route add command failed: external program exited with error status: 2
> 2019-06-08 07:18:31 | stdout | RTNETLINK answers: File exists
> 2019-06-08 07:18:29 | stdout | Transmission startup script complete.
> 2019-06-08 07:18:29 | stdout | NO PORT UPDATER FOR THIS PROVIDER
> 2019-06-08 07:18:29 | stdout | STARTING TRANSMISSION
> 2019-06-08 07:18:29 | stdout |  
> 2019-06-08 07:18:29 | stdout | -------------------------------------
> 2019-06-08 07:18:29 | stdout | User gid:    0
> 2019-06-08 07:18:29 | stdout | User uid:    0
> 2019-06-08 07:18:29 | stdout | User name:   root
> 2019-06-08 07:18:29 | stdout | -------------------------------------
> 2019-06-08 07:18:29 | stdout | Transmission will run as
> 2019-06-08 07:18:29 | stdout | -------------------------------------
> 2019-06-08 07:18:29 | stdout |  
> 2019-06-08 07:18:29 | stdout | sed'ing True to true
> 2019-06-08 07:18:29 | stdout | Generating transmission settings.json from env variables
> 2019-06-08 07:18:29 | stdout | Using Transmission Web Control  UI, overriding TRANSMISSION_WEB_HOME
> 2019-06-08 07:18:29 | stdout | Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 172.111.161.200
> 2019-06-08 07:18:29 | stdout | Up script executed with tun0 1500 1560 172.111.161.200 255.255.255.224 init
> 2019-06-08 07:18:29 | stdout | Sat Jun  8 07:18:29 2019 /etc/openvpn/tunnelUp.sh tun0 1500 1560 172.111.161.200 255.255.255.224 init
> 2019-06-08 07:18:29 | stdout | Sat Jun  8 07:18:29 2019 /sbin/ip addr add dev tun0 172.111.161.200/27 broadcast 172.111.161.223
> 2019-06-08 07:18:29 | stdout | Sat Jun  8 07:18:29 2019 /sbin/ip link set dev tun0 up mtu 1500
> 2019-06-08 07:18:29 | stdout | Sat Jun  8 07:18:29 2019 TUN/TAP device tun0 opened
> 2019-06-08 07:18:27 | stdout | Sat Jun  8 07:18:27 2019 [Secure-Server] Peer Connection Initiated with [AF_INET]172.111.161.130:80
> 2019-06-08 07:18:26 | stdout | Sat Jun  8 07:18:26 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> 2019-06-08 07:18:26 | stdout | Sat Jun  8 07:18:26 2019 TCP_CLIENT link remote: [AF_INET]172.111.161.130:80
> 2019-06-08 07:18:26 | stdout | Sat Jun  8 07:18:26 2019 TCP_CLIENT link local: (not bound)
> 2019-06-08 07:18:26 | stdout | Sat Jun  8 07:18:26 2019 TCP connection established with [AF_INET]172.111.161.130:80
> 2019-06-08 07:18:25 | stdout | Sat Jun  8 07:18:25 2019 Attempting to establish TCP connection with [AF_INET]172.111.161.130:80 [nonblock]
> 2019-06-08 07:18:25 | stdout | Sat Jun  8 07:18:25 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]172.111.161.130:80
> 2019-06-08 07:18:20 | stdout | Sat Jun  8 07:18:20 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> 2019-06-08 07:18:20 | stdout | Sat Jun  8 07:18:20 2019 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
> 2019-06-08 07:18:20 | stdout | Sat Jun  8 07:18:20 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
> 2019-06-08 07:18:20 | stdout | Sat Jun  8 07:18:20 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
> 2019-06-08 07:18:20 | stdout | Sat Jun  8 07:18:20 2019 WARNING: file '/etc/openvpn/ivacy/Wdc.key' is group or others accessible
> 2019-06-08 07:18:20 | stdout | Setting OPENVPN credentials...
> 2019-06-08 07:18:20 | stdout | Starting OpenVPN using config AustraliaMelbourneTCP.ovpn
> 2019-06-08 07:18:20 | stdout | Using OpenVPN provider: ivacy

**Host system:**
This is running on a Synology NAS

Any help is massively appreciated, however, I believe this is an IVACY problem and we may need to upload the config files?

**Comment by bruvv** [comment] 2019-06-12 12:45
duplicated:
https://github.com/haugene/docker-transmission-openvpn/issues/798

**Comment by haugene** [comment] 2019-11-11 10:45
Closing as a duplicate of #798

**Closed by haugene** 2019-11-11 10:45 UTC
