### ISSUE TITLE
Make note that Mullvad requires ipv6 to be disabled (or should it be enabled? See inside)

### ISSUE THREAD

**Issue by mhbates** [haugene/docker-transmission-openvpn#1355] opened 2020-09-10 04:25 UTC
**Is your feature request related to a problem? Please describe.**
The container wouldn't start with Mullvad, same error as shown in issue #396, "RTNETLINK answers: Permission denied" after ipv6 portion. The solution in that issue fixed it: Disabled ipv6 with --sysctl net.ipv6.conf.all.disable_ipv6=0

**Describe the solution you'd like**
Make a note about this in the documentation for Mullvad.

**Comment by balogan** [comment] 2020-09-11 19:40
@mhbates Shouldn't it be

`sysctl -w net.ipv6.conf.all.disable_ipv6=1` 

I still receive an error with ipv6 disabled.

Using OpenVPN provider: MULLVAD,
Starting OpenVPN using config mullvad_nl_udp.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.0.0/16 via 172.18.0.1 dev eth0,
Fri Sep 11 15:35:22 2020 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.,
Fri Sep 11 15:35:22 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 27 2020,
Fri Sep 11 15:35:22 2020 library versions: OpenSSL 1.1.1c 28 May 2019, LZO 2.10,
Fri Sep 11 15:35:22 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Fri Sep 11 15:35:22 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.65.134.132:1197,
Fri Sep 11 15:35:22 2020 Socket Buffers: R=[212992->1048576] S=[212992->1048576],
Fri Sep 11 15:35:22 2020 UDP link local: (not bound),
Fri Sep 11 15:35:22 2020 UDP link remote: [AF_INET]185.65.134.132:1197,
Fri Sep 11 15:35:22 2020 TLS: Initial packet from [AF_INET]185.65.134.132:1197, sid=47c8c638 a818ef0e,
Fri Sep 11 15:35:22 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Fri Sep 11 15:35:22 2020 VERIFY OK: depth=2, C=SE, ST=Gotaland, L=Gothenburg, O=Amagicom AB, OU=Mullvad, CN=Mullvad Root CA v2, emailAddress=security@mullvad.net,
Fri Sep 11 15:35:22 2020 VERIFY OK: depth=1, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=Mullvad Intermediate CA v2, emailAddress=security@mullvad.net,
Fri Sep 11 15:35:22 2020 VERIFY KU OK,
Fri Sep 11 15:35:22 2020 Validating certificate extended key usage,
Fri Sep 11 15:35:22 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Fri Sep 11 15:35:22 2020 VERIFY EKU OK,
Fri Sep 11 15:35:22 2020 VERIFY OK: depth=0, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=nl-ams-002.mullvad.net, emailAddress=security@mullvad.net,
Fri Sep 11 15:35:22 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1557', remote='link-mtu 1558',
Fri Sep 11 15:35:22 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo',
Fri Sep 11 15:35:22 2020 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_CHACHA20_POLY1305_SHA256, 4096 bit RSA,
Fri Sep 11 15:35:22 2020 [nl-ams-002.mullvad.net] Peer Connection Initiated with [AF_INET]185.65.134.132:1197,
Fri Sep 11 15:35:24 2020 SENT CONTROL [nl-ams-002.mullvad.net]: 'PUSH_REQUEST' (status=1),
Fri Sep 11 15:35:24 2020 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.11.0.1,redirect-gateway def1 bypass-dhcp,route-ipv6 0000::/2,route-ipv6 4000::/2,route-ipv6 8000::/2,route-ipv6 C000::/2,comp-lzo no,route-gateway 10.11.0.1,topology subnet,socket-flags TCP_NODELAY,ifconfig-ipv6 fdda:d0d0:cafe:1197::1002/64 fdda:d0d0:cafe:1197::,ifconfig 10.11.0.4 255.255.0.0,peer-id 1,cipher AES-256-GCM',
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: compression parms modified,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: --socket-flags option modified,
Fri Sep 11 15:35:24 2020 NOTE: setsockopt TCP_NODELAY=1 failed,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: --ifconfig/up options modified,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: route options modified,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: route-related options modified,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: peer-id set,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: adjusting link_mtu to 1624,
Fri Sep 11 15:35:24 2020 OPTIONS IMPORT: data channel crypto options modified,
Fri Sep 11 15:35:24 2020 Data Channel: using negotiated cipher 'AES-256-GCM',
Fri Sep 11 15:35:24 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Fri Sep 11 15:35:24 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Fri Sep 11 15:35:24 2020 ROUTE_GATEWAY 172.18.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:12:00:05,
Fri Sep 11 15:35:24 2020 GDG6: remote_host_ipv6=n/a,
Fri Sep 11 15:35:24 2020 ROUTE6: default_gateway=UNDEF,
Fri Sep 11 15:35:24 2020 TUN/TAP device tun0 opened,
Fri Sep 11 15:35:24 2020 TUN/TAP TX queue length set to 100,
Fri Sep 11 15:35:24 2020 /sbin/ip link set dev tun0 up mtu 1500,
Fri Sep 11 15:35:24 2020 /sbin/ip addr add dev tun0 10.11.0.4/16 broadcast 10.11.255.255,
Fri Sep 11 15:35:24 2020 /sbin/ip -6 addr add fdda:d0d0:cafe:1197::1002/64 dev tun0,
RTNETLINK answers: Permission denied,
Fri Sep 11 15:35:24 2020 Linux ip -6 addr add failed: external program exited with error status: 2,
Fri Sep 11 15:35:24 2020 Exiting due to fatal error,

**Comment by mhbates** [comment] 2020-09-11 19:45
> @mhbates Shouldn't it be
> 
> `sysctl -w net.ipv6.conf.all.disable_ipv6=1`
> 
> I still receive an error with ipv6 disabled.
> 

Regarding syntax, the "--sysctl net.ipv6.conf.all.disable_ipv6=0" I mentioned is an environment variable that I just added to the docker run, based on the other issue I linked. I guess if you go inside the container you would run the command you mentioned, sysctl -w ...

I guess you're right, the disable=1 should disable it, so maybe I got it backwards? Not sure. Either way, when I set it to disable=0, it starts to work. Have you tried that?

**Comment by balogan** [comment] 2020-09-12 14:03
@mhbates So I tried with 

`sysctl -w net.ipv6.conf.all.disable_ipv6=0`

and still got an ipv6 error

Using OpenVPN provider: MULLVAD,
Starting OpenVPN using config mullvad_nl_udp.ovpn,
Setting OPENVPN credentials...,
adding route to local network 192.168.0.0/16 via 172.18.0.1 dev eth0,
Sat Sep 12 03:09:12 2020 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.,
Sat Sep 12 03:09:12 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 27 2020,
Sat Sep 12 03:09:12 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10,
Sat Sep 12 03:09:12 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Sat Sep 12 03:09:12 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.65.134.132:1197,
Sat Sep 12 03:09:12 2020 Socket Buffers: R=[212992->1048576] S=[212992->1048576],
Sat Sep 12 03:09:12 2020 UDP link local: (not bound),
Sat Sep 12 03:09:12 2020 UDP link remote: [AF_INET]185.65.134.132:1197,
Sat Sep 12 03:09:12 2020 TLS: Initial packet from [AF_INET]185.65.134.132:1197, sid=1e2f788c dc865427,
Sat Sep 12 03:09:12 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Sat Sep 12 03:09:12 2020 VERIFY OK: depth=2, C=SE, ST=Gotaland, L=Gothenburg, O=Amagicom AB, OU=Mullvad, CN=Mullvad Root CA v2, emailAddress=security@mullvad.net,
Sat Sep 12 03:09:12 2020 VERIFY OK: depth=1, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=Mullvad Intermediate CA v2, emailAddress=security@mullvad.net,
Sat Sep 12 03:09:12 2020 VERIFY KU OK,
Sat Sep 12 03:09:12 2020 Validating certificate extended key usage,
Sat Sep 12 03:09:12 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sat Sep 12 03:09:12 2020 VERIFY EKU OK,
Sat Sep 12 03:09:12 2020 VERIFY OK: depth=0, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=nl-ams-002.mullvad.net, emailAddress=security@mullvad.net,
Sat Sep 12 03:09:12 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1557', remote='link-mtu 1558',
Sat Sep 12 03:09:12 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo',
Sat Sep 12 03:09:12 2020 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_CHACHA20_POLY1305_SHA256, 4096 bit RSA,
Sat Sep 12 03:09:12 2020 [nl-ams-002.mullvad.net] Peer Connection Initiated with [AF_INET]185.65.134.132:1197,
Sat Sep 12 03:09:13 2020 SENT CONTROL [nl-ams-002.mullvad.net]: 'PUSH_REQUEST' (status=1),
Sat Sep 12 03:09:13 2020 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.11.0.1,redirect-gateway def1 bypass-dhcp,route-ipv6 0000::/2,route-ipv6 4000::/2,route-ipv6 8000::/2,route-ipv6 C000::/2,comp-lzo no,route-gateway 10.11.0.1,topology subnet,socket-flags TCP_NODELAY,ifconfig-ipv6 fdda:d0d0:cafe:1197::1002/64 fdda:d0d0:cafe:1197::,ifconfig 10.11.0.4 255.255.0.0,peer-id 2,cipher AES-256-GCM',
Sat Sep 12 03:09:13 2020 OPTIONS IMPORT: compression parms modified,
Sat Sep 12 03:09:13 2020 OPTIONS IMPORT: --socket-flags option modified,
Sat Sep 12 03:09:13 2020 NOTE: setsockopt TCP_NODELAY=1 failed,
Sat Sep 12 03:09:13 2020 OPTIONS IMPORT: --ifconfig/up options modified,
Sat Sep 12 03:09:13 2020 OPTIONS IMPORT: route options modified,
Sat Sep 12 03:09:13 2020 OPTIONS IMPORT: route-related options modified,
Sat Sep 12 03:09:13 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified,
Sat Sep 12 03:09:13 2020 OPTIONS IMPORT: peer-id set,
Sat Sep 12 03:09:13 2020 OPTIONS IMPORT: adjusting link_mtu to 1624,
Sat Sep 12 03:09:13 2020 OPTIONS IMPORT: data channel crypto options modified,
Sat Sep 12 03:09:13 2020 Data Channel: using negotiated cipher 'AES-256-GCM',
Sat Sep 12 03:09:13 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Sep 12 03:09:13 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Sep 12 03:09:13 2020 ROUTE_GATEWAY 172.18.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:12:00:0c,
Sat Sep 12 03:09:13 2020 GDG6: remote_host_ipv6=n/a,
Sat Sep 12 03:09:13 2020 ROUTE6: default_gateway=UNDEF,
Sat Sep 12 03:09:13 2020 TUN/TAP device tun0 opened,
Sat Sep 12 03:09:13 2020 TUN/TAP TX queue length set to 100,
Sat Sep 12 03:09:13 2020 /sbin/ip link set dev tun0 up mtu 1500,
Sat Sep 12 03:09:13 2020 /sbin/ip addr add dev tun0 10.11.0.4/16 broadcast 10.11.255.255,
Sat Sep 12 03:09:13 2020 /sbin/ip -6 addr add fdda:d0d0:cafe:1197::1002/64 dev tun0,
RTNETLINK answers: Permission denied,
Sat Sep 12 03:09:13 2020 Linux ip -6 addr add failed: external program exited with error status: 2,
Sat Sep 12 03:09:13 2020 Exiting due to fatal error,

**Comment by mhbates** [comment] 2020-09-12 23:56
Are you passing it as an environmental variable in your docker command like I mentioned? That worked for me. Not sure if you’re trying to set it directly in the container.

**Comment by balogan** [comment] 2020-09-13 20:31
@mhbates I was setting it at the host OS level instead of at the container level, my mistake. Once I made the change everything began working. I agree there needs to be an update to the documentation for Mullvad to mention this.

**Comment by haugene** [comment] 2020-11-12 22:14
#1433

**Comment by garret** [comment] 2020-11-18 08:13
With the new version 3.2 the Mullvad profiles were updated. However, I still experience the ```RTNETLINK answers: Permission denied```. To solve the issue I have to use the custom provider option and modify the mullvad ovpn file as mentioned in https://github.com/haugene/docker-transmission-openvpn/issues/847#issuecomment-508707104 

Is it only me having still this issue?

**Comment by mhbates** [comment] 2020-11-18 15:53
Same here. Started working again once I put `--sysctl net.ipv6.conf.all.disable_ipv6=0` back into the run command.

**Comment by garret** [comment] 2020-11-19 19:07
@mhbates I added `--sysctl net.ipv6.conf.all.disable_ipv6=0` when I run my container. The container starts but it kind of freezes at this point and thus it is unusable: 
```
-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------


STARTING TRANSMISSION
Transmission startup script complete.
Thu Nov 19 20:04:14 2020 /sbin/ip route add 185.65.135.143/32 via 172.17.0.1
Thu Nov 19 20:04:14 2020 /sbin/ip route add 0.0.0.0/1 via 10.16.0.1
Thu Nov 19 20:04:14 2020 /sbin/ip route add 128.0.0.0/1 via 10.16.0.1
Thu Nov 19 20:04:14 2020 add_route_ipv6(::/2 -> fdda:d0d0:cafe:1302:: metric -1) dev tun0
Thu Nov 19 20:04:14 2020 /sbin/ip -6 route add ::/2 dev tun0
Thu Nov 19 20:04:14 2020 add_route_ipv6(4000::/2 -> fdda:d0d0:cafe:1302:: metric -1) dev tun0
Thu Nov 19 20:04:14 2020 /sbin/ip -6 route add 4000::/2 dev tun0
Thu Nov 19 20:04:14 2020 add_route_ipv6(8000::/2 -> fdda:d0d0:cafe:1302:: metric -1) dev tun0
Thu Nov 19 20:04:14 2020 /sbin/ip -6 route add 8000::/2 dev tun0
Thu Nov 19 20:04:14 2020 add_route_ipv6(c000::/2 -> fdda:d0d0:cafe:1302:: metric -1) dev tun0
Thu Nov 19 20:04:14 2020 /sbin/ip -6 route add c000::/2 dev tun0
Thu Nov 19 20:04:14 2020 Initialization Sequence Completed
```
Do you know what could be the reason and how to resolve?

**Comment by mhbates** [comment] 2020-11-19 23:34
My log stops there as well, but it's working fine at that point. Are you able to load the web interface? I would try using the default Mullvad config files, that might be the issue. For example, I have my OPENVPN_CONFIG variable set to "us_all".

There might be something else in your log that could help point to the problem.

**Comment by garret** [comment] 2020-11-21 09:16
@mhbates you are right. After waiting for some more time, I can see that the container now starts. I still think this option should be included in the mullvad provider documentation (or eventually having the option already inside the ovpn profiles). Thank you for this other solution.

**Comment by AKDub** [comment] 2020-12-20 13:40
Is there any way to add the temporary fix to a docker-compose file?

**Comment by pkishino** [comment] 2021-01-19 04:43
feel free to update the documentation with this

**Comment by chrisyuska** [comment] 2021-02-09 22:50
Just to keep this thread alive, I also have this issue with Mullvad.  I unfortunately have a scenario where running `--sysctl` options in the command line is non-trivial so I'd love to see support added for it instead of the workaround.

**Comment by pkishino** [comment] 2021-03-09 01:52
someone using mullvad could either update the ovpn configs..or update/create a provider script that sets this options

**Comment by hawkinspaul** [comment] 2021-03-15 05:58
Agreed, it's a headache right now to set up everything with Mullvad.

**Comment by HiiiiiHa** [comment] 2021-03-21 17:29
real nightmare to configure Mullvad, if someone can help, facing the famous "RTNETLINK answers: Permission denied" even with --sysctl net.ipv6.conf.all.disable_ipv6=0

**Comment by garret** [comment] 2021-03-22 07:42
> real nightmare to configure Mullvad, if someone can help. I tried [#1640 (comment)](https://github.com/haugene/docker-transmission-openvpn/issues/1640#issuecomment-752941723) with no luck(container no more crashing but no UI)

@HiiiiiHa I agree that it is annoying but for the moment me, like others, are resolving as explained here some posts above https://github.com/haugene/docker-transmission-openvpn/issues/1355#issuecomment-729771321

**Comment by HiiiiiHa** [comment] 2021-03-22 08:01
> @HiiiiiHa I agree that it is annoying but for the moment me, like others, are resolving as explained here some posts above [#1355 (comment)](https://github.com/haugene/docker-transmission-openvpn/issues/1355#issuecomment-729771321)

Tried this also, but does not help(could be because I'm on synology NAS) , is this the way?
![Untitled](https://user-images.githubusercontent.com/81105552/111958086-1e969780-8aed-11eb-9f22-27a3de53e618.jpg)

**Comment by garret** [comment] 2021-03-22 08:46
@HiiiiiHa I think is not working for you because you are giving `--sysctl net.ipv6.conf.all.disable_ipv6=0` as `variable` while it is an `option` as I have understood (I am not very technical).  
I don't know the synology but how do you create the container? with docker-compose or just running from command line? 

For docker-compose you should add the line like in this way: 
```
version: '3'
services:
    transmission:
        container_name: transmission
        environment:
            - TZ=Europe/Paris
        ports:
            - 9091:9091 #Transmission
[..]
# ipv6 must be disabled for Mullvad to work
        sysctls:
            - "net.ipv6.conf.all.disable_ipv6=0"
        restart: unless-stopped
        image: haugene/transmission-openvpn
```

This is instead if you run via cli: 
```
docker run --name=transmission \
-v /config/transmission/:/data/transmission-home \
-e TZ=Europe/Paris \
[...]
--sysctl net.ipv6.conf.all.disable_ipv6=0 \
--restart=unless-stopped \
haugene/transmission-openvpn
```

**Comment by HiiiiiHa** [comment] 2021-03-22 09:53
thanks for your support, i'm not very thecnical neither. I'm using the Docker synology App to download\configure\run the container. I

**Comment by caffeinePlease** [comment] 2021-04-20 12:30
> @HiiiiiHa I think is not working for you because you are giving `--sysctl net.ipv6.conf.all.disable_ipv6=0` as `variable` while it is an `option` as I have understood (I am not very technical).
> I don't know the synology but how do you create the container? with docker-compose or just running from command line?
> 
> For docker-compose you should add the line like in this way:
> 
> ```
> version: '3'
> services:
>     transmission:
>         container_name: transmission
>         environment:
>             - TZ=Europe/Paris
>         ports:
>             - 9091:9091 #Transmission
> [..]
> # ipv6 must be disabled for Mullvad to work
>         sysctls:
>             - "net.ipv6.conf.all.disable_ipv6=0"
>         restart: unless-stopped
>         image: haugene/transmission-openvpn
> ```
> 
> This is instead if you run via cli:
> 
> ```
> docker run --name=transmission \
> -v /config/transmission/:/data/transmission-home \
> -e TZ=Europe/Paris \
> [...]
> --sysctl net.ipv6.conf.all.disable_ipv6=0 \
> --restart=unless-stopped \
> haugene/transmission-openvpn
> ```

I can get this working through Synology with other providers with very few issues (PIA specifically) but I don't believe we "simpler" users have access to either of these methods using this container from the "Synology Docker Packer Installer." It's essentially an appstore for Synology NAS devices. 

@HiiiiiHa posted a screenshot of the areas where we can make edits--I don't think this line required for Mullvad to work is available anywhere else, unless someone has insight into working with Synology's DSM OS specifically.

**Comment by HiiiiiHa** [comment] 2021-04-20 15:06
yes you are absolutely correct, I was finaly able to have it working by runing the command line, thanks!

**Comment by fang64** [comment] 2021-04-25 01:36
I'm not sure if anyone has tried to do a PR for this yet, I've noticed haugene seems to be splitting the VPN configuration off, and I've included some updates for this. Apparently tun-ipv6 doesn't appear to work, I can at least confirm on my end it's not working. They never seem to issue a IPv6 address even though my network has support for it, which shouldn't matter as it's being tunneled anyway. 

tun-ipv6 seems to be the culprit for most, just removing that line from the VPN files for now is a fix. To add the port changes over commit history, is actually wrong, they randomize the ports when you request a configuration file and they have like 6~7 ports they use, those could be added to the configuration files, I went through and did a bunch but didn't feel like doing a ton of editing to resolve it. Maybe someone would like to go in and resolve this:
They use ports, 1194,1195,1196,1197,1300,1301, and 1302.

I would just like the container to function with Mullvad at least reliably. Maybe at some point they'll get this issue fixed, I am not sure why the OpenVPN wont issue IPv6 reliably. 

For the current main repository:
https://github.com/haugene/docker-transmission-openvpn/pull/1818

For the new vpn configuration repo:
https://github.com/haugene/vpn-configs-contrib/pull/7

I wasn't exactly sure which one would get us this change in the container, also it seems this has gone on for awhile.

**Comment by nebulight** [comment] 2021-05-17 04:39
I'm still having this issue. I also have a Synology NAS so my options are limited. I'm trying to run those commands, but the docker will stop/restart before I can do anything with it.

![image](https://user-images.githubusercontent.com/49211351/118433092-14c58680-b68f-11eb-9091-59e06409c3d3.png)

**Comment by fang64** [comment] 2021-05-21 10:05
@nebulight I don't think he has pushed those up to docker repositories till yesterday. Can you try it again? Make sure you are on, haugene/transmission-openvpn:latest docker container if you are pulling from docker repository. 

If you built your container from git it should just work whether or not you disable IPv6 since the issue is Mullvad configurations were still trying to create the IPv6 tunnel regardless.

**Comment by slovenec88** [comment] 2021-05-21 16:32
My solution to this problem was to comment out `#tun-ipv6` line in nl_all.ovpn for example and then I `docker cp nl_all.ovpn transmissionvpn:/etc/openvpn/mullvad/` This solution doesn't seem to work in the latest update anymore.

In logs I see 

`
2021-05-21 18:22:04 GDG6: remote_host_ipv6=n/a


2021-05-21 18:22:04 net_route_v6_best_gw query: dst ::


2021-05-21 18:22:04 sitnl_send: rtnl: generic error (-101): Network unreachable


2021-05-21 18:22:04 ROUTE6: default_gateway=UNDEF


2021-05-21 18:22:04 TUN/TAP device tun0 opened


2021-05-21 18:22:04 /sbin/ip link set dev tun0 up mtu 1500


2021-05-21 18:22:04 /sbin/ip link set dev tun0 up


2021-05-21 18:22:04 /sbin/ip addr add dev tun0 10.9.0.26/16


2021-05-21 18:22:04 /sbin/ip link set dev tun0 up mtu 1500


2021-05-21 18:22:04 /sbin/ip link set dev tun0 up


2021-05-21 18:22:04 /sbin/ip -6 addr add fdda:d0d0:cafe:1195::1018/64 dev tun0


RTNETLINK answers: Permission denied


2021-05-21 18:22:04 Linux ip -6 addr add failed: external program exited with error status: 2


2021-05-21 18:22:04 Exiting due to fatal error

`

I see that config file has now been altered a bit and this tun-ipv6 is no longer present in the file.

Can someone please help? 

Thank you

**Comment by slovenec88** [comment] 2021-05-22 00:05
My tmp solution now was reverting to older version. Still not sure what changed in the new version? I understood as this commit would fix the ipv6 problem?

**Comment by pkishino** [comment] 2021-05-22 06:23
It has according to some others.. if you are having problems I suggest opening an issue with all the details requested in the template

**Comment by fang64** [comment] 2021-05-22 09:21
@slovenec88 yes I did exactly that, I striped it from all the vpn files because it just wasn't working even with IPv6, I think it's been broken for some time.

**Comment by lupin42** [comment] 2021-05-24 10:56
I'm pleased to finally have the container working with Mullvad on my Synology box (running DSM 6.2.4).

**@fang64:** thanks for removing ipv6 from the openvpn configs - that seems to have done the trick.

**@nebulight:** as others have mentioned, you do still need the sysctl option, which can't be done from the Synology docker GUI. From a SSH session, docker run and docker-compose both work fine.  Afterwards, provided you don't mess with the options in the GUI, you can still start and stop the container from there. But docker-compose is actually easier to manage and it's certainly more portable.

I can recommend following the "Debug your setup" guide if you have problems - it helped me a lot.

**Comment by slovenec88** [comment] 2021-05-24 19:46
Adding sysctl option like @garret kindly explained to docker-compose fixed the issue for me as well! 

```
# ipv6 must be disabled for Mullvad to work
        sysctls:
            - "net.ipv6.conf.all.disable_ipv6=0"
```

Thank you!

**Closed** 2021-05-25 04:56 UTC
Labels: Needs PR, documentation update

**Comment by ilike2burnthing** [comment] 2021-05-25 09:06
I'm fairly certain it should be `net.ipv6.conf.all.disable_ipv6=1`, basically `disable(ipv6)=true`.

If you google `net.ipv6.conf.all.disable_ipv6` you'll get a lot of Linux guides which all say `=1` to disable. Looking for Docker specific results gets you a confusing mixed bag like we've seen here, but they seem to mostly come down on the side of `=1` to disable.

**Comment by pkishino** [comment] 2021-05-25 09:36
lol, yeah, you are right.. but tired today and wasn’t paying attention
haha.. will update documentation

**Comment by garret** [comment] 2021-05-25 09:57
Ok, I have not checked on docker documentation but I am quite sure that, as written before and tested by other people, to get Mullvad working I have `--sysctl net.ipv6.conf.all.disable_ipv6=0`.

**Comment by ilike2burnthing** [comment] 2021-05-25 11:09
It seems IPv6 needs to be enabled then, not disabled. So an edit is still needed, but just for the two `disabled` > `enabled`.

**Comment by pkishino** [comment] 2021-05-25 11:28
Yeah, ok

**Comment by slovenec88** [comment] 2021-05-25 11:31
@ilike2burnthing I decided to test your theory and tested all combinations `true/false/0/1`, only this works `--sysctl net.ipv6.conf.all.disable_ipv6=0`

**Comment by pkishino** [comment] 2021-05-25 11:36
Ok, that means it needs to be enable then..

**Comment by pkishino** [comment] 2021-05-25 11:37
Fixed documentation

**Comment by MattWaller** [comment] 2021-06-24 02:59
This is also an issue on Tunnelbear.

**Comment by BasixKOR** [comment] 2022-01-06 21:22
For those of you who are unable to set sysctl options (read: Synology), you can add this environment variable [(idea from here)](https://www.synoforum.com/threads/seeking-remedy-for-rtnetlink-answers-permission-denied.2470/post-29482)

```env
OPENVPN_OPTS=--pull-filter ignore ifconfig-ipv6
```

**Comment by mrafayaleem** [comment] 2023-06-14 03:41
> For those of you who are unable to set sysctl options (read: Synology), you can add this environment variable [(idea from here)](https://www.synoforum.com/threads/seeking-remedy-for-rtnetlink-answers-permission-denied.2470/post-29482)
> 
> ```dotenv
> OPENVPN_OPTS=--pull-filter ignore ifconfig-ipv6
> ```

This worked on Synology DS220+! Thank you!
