### ISSUE TITLE
/data vs /config? Fallback not working.

### ISSUE THREAD

**Issue by glassbase** [haugene/docker-transmission-openvpn#2409] opened 2022-11-14 16:32 UTC
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

**not working**
docker run -d --name='transmission' --net='nginx' -e TZ="America/New_York" -e HOST_OS="Unraid" -p '9091:9091/tcp' -p '8888:8888/tcp' -v '/mnt/user/appdata/transmission':'**/data**':'rw' -v '/mnt/disks/transmission/':'/transmission':'rw,slave' -v '/mnt/user/appdata/jackett_downloads':'/watch':'rw' --restart unless-stopped --dns 8.8.8.8 --dns 8.8.4.4 --cap-add=NET_ADMIN --env-file=/mnt/user/appdata/transmission/transmission.env 'haugene/transmission-openvpn:latest'

**working**
docker run -d --name='transmission' --net='nginx' -e TZ="America/New_York" -e HOST_OS="Unraid" -p '9091:9091/tcp' -p '8888:8888/tcp' -v '/mnt/user/appdata/transmission':'**/config**':'rw' -v '/mnt/disks/transmission/':'/transmission':'rw,slave' -v '/mnt/user/appdata/jackett_downloads':'/watch':'rw' --restart unless-stopped --dns 8.8.8.8 --dns 8.8.4.4 --cap-add=NET_ADMIN --env-file=/mnt/user/appdata/transmission/transmission.env 'haugene/transmission-openvpn:latest'

### Current Behavior

`We're changing the default location of TRANSMISSION_HOME from the /data mount to the /config mount. This is primarily going to affect new setups, as we will fallback to /data as long as we see the transmission-home folder there. Might consider more breaking measures in the future but for now we just log a hint to move the folder.`

I had my age-old docker config set to /data and wondered why things were screwy (resume list disappeared). I edit docker config to /config and everything back to normal. 

**_Are we sure this fallback works?_**

### Expected Behavior

See above.

### How have you tried to solve the problem?

Changed /data to /config and it works.

### Log output

n/a

### HW/SW Environment

```markdown
- OS: Unraid
- Docker: y
```

### Anything else?

n/a

**Comment by jmrushing** [comment] 2022-11-15 01:36
Adding a related note to your issue in case anyone runs into similar problem as me:

After following the suggested switch to '/config', I also had to update the in-app settings for radarr & sonarr, specifically Settings -> Download Clients -> Remote Path Mappings. I needed to change the Remote Path '/data/...' to '/config/...'. Otherwise, sonarr/radarr throws a status error and is unable to move the completed download. (Caution: If you don't use remote path mapping or move completed downloads elsewhere like my setup, this suggestion may not be relevant to you.)

Side note: whatever was updated sometime last week broke my long-running setup, resulting in several cascading issues that needed to be resolved. I was able to get back to a working setup (using some of the most recent suggestions floating around under Issues here) and update my docker mount to reflect the preferred '/config' usage, but I'm still worried that there is some breakage happening somewhere. I'll try to write up an issue in the next few days detailing what I've done and what I'm seeing in case that helps anyone.

**Comment by svloosbroek** [comment] 2022-11-15 12:18
Same issue here, does not fall back to /data when using a shared volume in docker compose:

```
        volumes:
            - '/mnt/video:/data'
```

Results in the following console error:

```
Updating Transmission settings.json with values from env variables
Attempting to use existing settings.json for Transmission
Could not read existing settings.json. Generating settings.json for Transmission from environment and defaults /etc/transmission/default-settings.json
```

**Comment by pkishino** [comment] 2022-11-15 21:33
Guys, nowhere does it say to remove /data.. only that container config etc is moved it /config.. 
so in a normal setup you would mount BOTH /data AND /config ..
It just logically separates things that shouldn’t be together.

**Comment by glassbase** [comment] 2022-11-16 14:06
There is too much conflicting info. The disclaimer mentions it should only affect new setups, yet the the readme says to use `/data`. That should be updated.

**Comment by glassbase** [comment] 2022-11-16 14:09
To add further details, my container was not working with my config folder mounted as /data (where transmission-home is found), had to mount it to /config. Hence why I think the fallback does not work.

(Not talking about where my download are set to.)

**Comment by glassbase** [comment] 2022-11-16 14:14
Logs - w my config folder mounted as `/data`:
```
Updating Transmission settings.json with values from env variables
Attempting to use existing settings.json for Transmission
Could not read existing settings.json. Generating settings.json for Transmission from environment and defaults /etc/transmission/default-settings.json
```

Logs - w my config folder mounted as `/config`:
```
Updating Transmission settings.json with values from env variables
Attempting to use existing settings.json for Transmission
Successfully used existing settings.json /config/transmission-home/settings.json
```

**Comment by xPoP** [comment] 2022-11-18 01:35
Just got this working again thanks to utilizing the suggestion by @pkishino

> Guys, nowhere does it say to remove /data.. only that container config etc is moved it /config.. so in a normal setup you would mount BOTH /data AND /config ..

So before the latest 4.+ upgrades I had this in my docker-compose:
```
volumes:
            - '/home/user/transmission-daemon:/data'
```

After the upgrades, due to the warning on the 4.2 tag, I had changed to this:
```
volumes:
            - '/home/user/transmission-daemon:/config'
```
but it was broken, and my transmission settings.json would continually revert back to /data/downloads rather than the set /config/downloads which was frustrating.

I now have the following, and moved my "completed", "incomplete", and "watch" folders into /home/user/transmission-daemon/data and all is working well again.
```
 volumes:
            - '/home/rdp/transmission-daemon/data:/data'
            - '/home/rdp/transmission-daemon:/config'
```

With all that said, I'd have to agree with @glassbase here:
> There is too much conflicting info. The disclaimer mentions it should only affect new setups, yet the the readme says to use `/data`. That should be updated.

**Comment by Moraziel** [comment] 2022-11-22 08:47
In my case, the issue I had was an error 403 Too many failed authentication attemps after a short while after rebooting the container, and it was due to this issue since I only had /data mounted.
Now that I added /config, it works, and I can tell what the fall back is, per the logs : 
`sh[1156337]: TRANSMISSION_HOME is currently set to: /config/transmission-home
sh[1156337]: WARNING: Deprecated. Found old default transmission-home folder at /data/transmission-home, setting this as TRANSMISSION_HOME. This might break in future versions.
sh[1156337]: We will fallback to this directory as long as the folder exists. Please consider moving it to /config/<transmission-home>`
So as long as you have both /data and /config mounted, the code can fallback on /data/transmission-home for settings, if found, but you need to have config mounted, else it can't find settings.json and issues arise

**Comment by haugene** [comment] 2022-12-03 23:46
Hey. Had a look at this now, but have to continue searching for the bug later.

**What I did:**
- Booted the image with version `3.7.1` and only `/data` mounted
- Downloaded a couple of torrents
- Upgraded the image to version `4.3` still only with `/data` mounted

**What I found:**
- Once booted into `4.3` I could still see my torrents and progress
- An error log about the settings.json file:
```
openvpn  | 2022-12-03 23:18:03 Initialization Sequence Completed
openvpn  | Running functions for token based port fowarding
openvpn  | Reserved Port: 40686  Sat Dec  3 23:18:08 UTC 2022
openvpn  | grep: /config/transmission-home/settings.json: No such file or directory
```

**What failed:**
We're persisting the environment variables in the openvpn/start.sh script. This is so that we can read them and set them again when transmission should start. The Transmission start script is the one running the userSetup.sh script and having a look at TRANSMISSION_HOME and doing the fallback. The problem is that `export TRANSMISSION_HOME=/config/transmission-home` is in the persisted values and all other scripts running after userSetup.sh will still see that TRANSMISSION_HOME value even if we've decided to use the fallback. This should be fixed.

**What didn't fail, and require more looking into:**
Transmission itself is started with knowledge about the fallback so it should see its old files. And that works for me. So... Does this ring a bell? Anyone having a good theory here?

@DuvelCorp you also reported this in the discussions, what config parameters are you running with. Anything that can help me narrow this down?

@glassbase You refer to a `transmission.env` file that use use for environment variables. What's in it? Kind of a missing piece based on the docker run statements you posted.

**Comment by haugene** [comment] 2022-12-20 23:22
Ok, so I think I found the bug. Didn't notice it earlier but you are running the container without specifying a PUID/PGID making Transmission run as root within the container. This is fine and should be supported, so it was indeed a bug. But the fallback logic was run in userSetup.sh and was only invoked if a user id for Transmission is provided.

I moved the logic now and if you pull and run the dev tag of the image now it should work. Can you confirm @glassbase?

**Closed** 2023-04-02 10:41 UTC
Labels: inactivity
