### ISSUE TITLE
Debian/Ubuntu: Upgrading docker to 17.06 causes startup to fail (Permission denied)

### ISSUE THREAD

**Issue by grOGH** [haugene/docker-transmission-openvpn#279] opened 2017-07-18 14:38 UTC
Running Debian Jessie:

3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux

Upgrading docker_ce from 17.03 to version 17.06.0~ce-0~debian causes startup to fail with the following error message:
```

Tue Jul 18 16:27:33 2017 /sbin/ip -6 addr add <ipv6> dev tun0
RTNETLINK answers: Permission denied
Tue Jul 18 16:27:33 2017 Linux ip -6 addr add failed: external program exited with error status: 2
Tue Jul 18 16:27:33 2017 Exiting due to fatal error
```
Downgrading to 17.03 allows the container to start again.

**Comment by packruler** [comment] 2017-07-30 19:49
Duplicate of #268

**Comment by grOGH** [comment] 2017-09-21 07:26
Temporary workaround: raise your docker-compose version to >= 2.1 and add the following to the container config:

```  
sysctls:
    - net.ipv6.conf.all.disable_ipv6=0
```

**Comment by haugene** [comment] 2017-10-15 19:18
The base image has now been upgraded and I'm running on 17.09.0-ce without issues. Can you check if you still have this problem (without the ipv6 disable flag)?

**Comment by grOGH** [comment] 2017-10-15 20:19
Just tested again on Debian 9 Stretch and Docker 17.09, same issue. Container won't start without the flag.

Have you tested it on Debian? It's running Kernel 4.9.0.

**Comment by haugene** [comment] 2017-10-15 22:12
I'm running Debian Jessie with kernel 3.16.0-4-amd64, working fine. I'll see if I have time to set up a debian 9 vm one day, but as long as there's a workaround I guess it "works" for now.

**Comment by CyberSardinha** [comment] 2017-11-17 22:12
I have this problem and I can't seem to go around it. I've tried sysctls sugestion but either I don't know how to do it or it didn't work :S

**Comment by rwaesely** [comment] 2017-11-20 19:16
Same here, haugene, I noticed it today ^^
I'd rather not to modify the source code... Thanks for your time :)

**Comment by clarkent86** [comment] 2018-03-03 01:58
@rwaesely you brilliant wizard, thanks for this!

**Comment by haugene** [comment] 2018-04-08 19:58
Seems this is solved. If someone feels like adding it to the README, submit a PR. Otherwise I guess google will take people who experience it here.

**Closed by haugene** 2018-04-08 19:58 UTC

**Comment by billd100** [comment] 2019-10-19 16:53
In case you're adding this to a docker-compose.yml file, update the file version to `>=2.1` and add the `sysctls` option, for example:
```
version: '2.1'
services:
    transmission:
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=1
```
