### ISSUE TITLE
TRANSMISSION_PEER_PORT_RANDOM_ON_START: unbound variable

### ISSUE THREAD

**Issue by yongbi85** [haugene/docker-transmission-openvpn#2404] opened 2022-11-13 10:31 UTC
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

version: '3'
services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    networks:
      - mesdockers
    command: "dumb-init /etc/openvpn/start.sh"
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      OPENVPN_USERNAME: "****"
      OPENVPN_PASSWORD: "****"
      OPENVPN_PROVIDER: "NORDVPN"
      GLOBAL_APPLY_PERMISSIONS: "true"
      TRANSMISSION_HOME: "/data/transmission-home"
      TRANSMISSION_RPC_PORT: "9091"
      TRANSMISSION_DOWNLOAD_DIR: "/transmissiondl/Complete"
      TRANSMISSION_INCOMPLETE_DIR: "/transmissiondl/Incomplete"
      TRANSMISSION_WATCH_DIR: "/transmissiondl/Torrents"
      CREATE_TUN_DEVICE: "true"
      ENABLE_UFW: "true"
      UFW_ALLOW_GW_NET: "true"
      UFW_EXTRA_PORTS: "5299,9091,51413"
      UFW_DISABLE_IPTABLES_REJECT: "true"
      PGID: "100"
      PUID: "1030"
      TZ: "Europe/Paris"
      DROP_DEFAULT_ROUTE: "true"
      WEBPROXY_ENABLED: "false"
      WEBPROXY_PORT: "8888"
      WEBPROXY_USERNAME: ""
      WEBPROXY_PASSWORD: ""
      LOG_TO_STDOUT: "false"
      HEALTH_CHECK_HOST: "google.com"
      TRANSMISSION_CACHE_SIZE_MB: "32"
      TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "8"
      TRANSMISSION_IDLE_SEEDING_LIMIT: "120"
      TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED: "true"
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
      TRANSMISSION_LPD_ENABLED: "true"
      TRANSMISSION_MAX_PEERS_GLOBAL: "500"
      TRANSMISSION_PEER_LIMIT_GLOBAL: "500"
      TRANSMISSION_PORT_FORWARDING_ENABLED: "true"
      TRANSMISSION_PEER_PORT: "51413"
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
      TRANSMISSION_RPC_PASSWORD: "*****"
      TRANSMISSION_RPC_USERNAME: "*****"
      TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED: "true"
      TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME: "/config/Unrar.sh"
      TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES: "true"
      NORDVPN_COUNTRY: "Fr"
      NORDVPN_CATEGORY: "legacy_p2p"
      NORDVPN_PROTOCOL: "udp"
      LOCAL_NETWORK: "192.168.1.0/24"
      OPENVPN_OPTS: "--inactive 3600 --ping 10 --ping-exit 60"
    ports:
      - 9091:9091
      - 51413:51413
      - 5299:5299
    volumes:
      - /volume1/docker/transmission/resolv.conf:/etc/resolv.conf
      - /volume1/Downloads/transmission:/transmissiondl
      - /volume1/docker/transmission/config:/config
      - /volume1/docker/transmission/data:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped

### Current Behavior

Docker constantly crashing on start.

### Expected Behavior

I was expecting it to start as usual and no permanent crash with the /etc/openvpn/start.sh: line 262: TRANSMISSION_PEER_PORT_RANDOM_ON_START: unbound variable error
This used to work perfectly weel until yesterday.

### How have you tried to solve the problem?

Tried dev branch but encountered a whole lot of different error
I deleted entirely the data and config folders
Redownloaded the image and recreated the stack completely
Deleted some the country config option, deleted all nordvpn specific config option, ...
Always the same error

Only thing solving the issue is to disable ufw (which obviously isn't ideal...)

### Log output

Starting container with revision: bf4c4e8e147978c0ffd700c64648491c317c17ee
Creating TUN device /dev/net/tun
Using OpenVPN provider: NORDVPN
Running with VPN_CONFIG_SOURCE auto
Provider NORDVPN has a bundled setup script. Defaulting to internal config
Executing setup script for NORDVPN
INFO: OVPN: Checking curl installation
INFO: OVPN: DNS resolution ok
INFO: OVPN: ok, configurations download site reachable
INFO: OVPN: Removing existing configs in /etc/openvpn/nordvpn
Checking NORDPVN API responses
INFO: OVPN:Selecting the best server...
INFO: OVPN: Searching for country : Fr (74)
INFO: OVPN: Searching for group: legacy_p2p
INFO: OVPN:Searching for technology: openvpn_udp
INFO: OVPN: Best server : fr662.nordvpn.com, load: 7
INFO: OVPN: Downloading config: fr662.nordvpn.com.ovpn
INFO: OVPN: Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/fr662.nordvpn.com.udp.ovpn
Starting OpenVPN using config fr662.nordvpn.com.ovpn
Modifying /etc/openvpn/nordvpn/fr662.nordvpn.com.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Modification: Updating status for config failure detection
Setting OpenVPN credentials...
Disable and blank firewall
Firewall stopped and disabled on system startup
enabling firewall
Firewall is active and enabled on system startup
/etc/openvpn/start.sh: line 262: TRANSMISSION_PEER_PORT_RANDOM_ON_START: unbound variable

### HW/SW Environment

```markdown
- OS: DSM Synology 6.2
- Docker: Docker version 20.10.3, build b35e731
```

### Anything else?

Just for information, on latest commit : works only if UFW is disabled, else i get the mentioned error
And when I try dev branch, i get another error which is also related to UFW too : ERROR: Couldn't determine iptables version
Reverting to 3.7.1 also solves the issue and permit to enable ufw, so I'm back on this for now.

**Comment by haugene** [comment] 2022-11-13 15:55
Hmm, this is another instance of https://github.com/haugene/docker-transmission-openvpn/discussions/2395 where references to unset variables are failing with NordVPN because the nordvpn configuration script specifies the `-u` option.

Setting `TRANSMISSION_PEER_PORT_RANDOM_ON_START=` in your environment variables should fix it, but another might show up. Would you mind testing it and let me know if there are more? Then I can add some defaults to it in this scenario, seems it's only related to the UFW part of the scripts then.

Not sure whats the best way forward here, maybe we should just drop the `-u` checking.

**Comment by yongbi85** [comment] 2022-11-13 18:00
It works with this additional environment variable (i set it to false)

**Comment by tmknight** [comment] 2022-11-14 22:28
>Not sure whats the best way forward here, maybe we should just drop the `-u` checking.

Seems prudent to remove from production until all variables are accounted for and 'set' in the image to a default... though I can see even that becoming a burden to the end user having to understand each and every variable and how it may impact them.

**Comment by karpana** [comment] 2022-11-16 03:42
Hi There,
I'm having the same issue with my installation; seem to have been happening since about 2 or 3 days ago (which seems to coincide with the last upate).

I've tried setting `TRANSMISSION_PEER_PORT_RANDOM_ON_START=` as well as `TRANSMISSION_PEER_PORT_RANDOM_ON_START=false` and neither seems to resolve the issue for me.

**Comment by haugene** [comment] 2022-11-16 08:33
Hello again. I just did some testing locally and I got an error for more of the variables and decided to do a middle ground solution and disable the checking from the UFW part of the script and out. This has only been hitting NordVPN users and such has a smaller blast radius (although I understand it's not fun to be in it). Running with -u for the rest shows that we might not be too far away from turning it on everywhere. I think that should be the end game here, optionally I've also considered migrating it to Python. Bash gets chaotic at a certain size and I think we're getting closer.

Anyways. I have pushed a fix to the master and dev branches so that should be available on `edge` and `dev` tags in a few minutes. Note that `latest` will be the latest tagged release going forward - instead of being the latest commit on master.

**Comment by haugene** [comment] 2022-11-16 13:52
I assume this can be closed now @yongbi85? The issue is fixed and is included in the `4.3` release. Is also available with the `latest` tag now.

**Comment by yongbi85** [comment] 2022-11-16 16:36
Hello,
This particular issue can be closed, however as said when I was testing out dev branch and confirmed with latest commit pull now I have another error...
"Cannot determine iptables version"

Reverted to 3.7.1 for the moment

**Comment by edgd1er** [comment] 2022-11-16 20:28
to fix unbound variable one may define a default value:
`portNum=${1:-''}`

**Comment by haugene** [comment] 2022-12-03 00:05
I'm closing this then, and making a note that there might be issues with UFW in the new image :+1:

**Closed by haugene** 2022-12-03 00:05 UTC

**Comment by michaelfedell** [comment] 2023-07-03 01:52
Also got an issue with `TRANSMISSION_RPC_USERNAME: unbound variable` in version 5.0.2 with NordVPN provider
