### ISSUE TITLE
NordVPN Script not downloading ovpn file

### ISSUE THREAD

**Issue by timjlowe** [haugene/docker-transmission-openvpn#1020] opened 2020-01-22 15:18 UTC
**Describe the problem**
The container is unable to connect to NordVPN as it fails whilst trying to download the ovpn file from NordVPN.  I have tried as many differernt NORDVPN config values as I can think of.

I tried running the updateConfigs.sh script outside of the container and it seemed to work, so it could just be that my NORDVPN env variables are not being passed (or formatted correctly) when run from docker-compose.

**Add your docker run command**
version: "2"
services:
  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 45.90.28.29
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - ${USERDIR}/Downloads:/data/watch
      - ${USERDIR}/Downloads/completed:/data/completed
      - ${USERDIR}/Downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=***
      - OPENVPN_PASSWORD=***
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - NORDVPN_COUNTRY=gb
      - NORDVPN_PROTOCOL=tcp
      - NORDVPN_CATEGORY=p2p
      - LOCAL_NETWORK=10.0.0.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,10.0.0.*.*"
      - TRANSMISSION_RPC_PASSWORD=webui_password
      - TRANSMISSION_RPC_USERNAME=webui_username
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true

**Logs**
Using OpenVPN provider: NORDVPN
2020-01-22 15:12:32 Checking curl installation
2020-01-22 15:12:32 Removing existing configs
2020-01-22 15:12:32 Selecting the best server...
2020-01-22 15:12:32 Searching for technology: openvpn_tcp
2020-01-22 15:12:32 Unable to find a server with the specified parameters, using any recommended server
2020-01-22 15:12:32 Best server :
2020-01-22 15:12:32 Downloading config: default.ovpn
2020-01-22 15:12:32 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    698      0 --:--:-- --:--:-- --:--:--   701
2020-01-22 15:12:32 Selecting the best server...
2020-01-22 15:12:32 Searching for technology: openvpn_tcp
2020-01-22 15:12:32 Unable to find a server with the specified parameters, using any recommended server
2020-01-22 15:12:32 Best server :
2020-01-22 15:12:32 Downloading config: .ovpn
2020-01-22 15:12:32 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    789      0 --:--:-- --:--:-- --:--:--   790
2020-01-22 15:12:32 Checking line endings
2020-01-22 15:12:32 Updating configs for docker-transmission-openvpn
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network 10.0.0.0/24 via 172.19.0.1 dev eth0
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/default.ovpn:1: html (2.4.7)
Use --help for more information.

**Host system:**
Ubuntu Server 18.04
Docker version 19.03.5, build 633a0ea838

**Comment by ditisjordy** [comment] 2020-01-22 18:16
Exactly the same problem here, for a while now... :(

**Comment by starrbuck68** [comment] 2020-01-22 23:46
I believe the fix for this is to remove the OPENVPN_OPTS from the config. It's not needed for NordVPN and it causes this error.

**Comment by ditisjordy** [comment] 2020-01-23 09:27
> I believe the fix for this is to remove the OPENVPN_OPTS from the config. It's not needed for NordVPN and it causes this error.

Same error without OPENVPN_OPTS env, unfortunately

**Comment by starrbuck68** [comment] 2020-01-23 15:49
I’m so sorry, that’s definitely what fixed it for me. I’ll take a closer look at my config this evening and get back to you!

**Comment by ditisjordy** [comment] 2020-01-23 16:25
No problem. If you need any additional information, please let me know!

**Comment by jayesh100** [comment] 2020-01-24 07:55
Had a similar issue recently, my container wasn't able to perform DNS resolution. Might be worth confirming with `docker run busybox nslookup google.com` from your host

**Comment by starrbuck68** [comment] 2020-01-25 01:11
Sorry, it was removing OPENVPN_CONFIG that fixed it for me, and as I see you don't have that, the issue must be something else.

**Comment by fboterblom** [comment] 2020-01-29 19:40
I have the same problem, removing OPENVPN_CONFIG dit not help. Did run the docker for testing DNS and it failed, why is that?

**Comment by joshmello** [comment] 2020-01-30 17:26
Same

**Comment by deimosian** [comment] 2020-02-16 18:16
I had this issue. Solved by doing the following: 

docker exec -it transmission-vpn bash
apt-get update
apt-get install dos2unix
/etc/openvpn/nordvpn/updateConfigs.sh

**Comment by jsloan117** [comment] 2020-03-17 23:25
I don't use NordVPN so I can't test, but wondering if removing the '}' from L54 in openvpn/start.sh fixes this? I see it was added [here](https://github.com/haugene/docker-transmission-openvpn/blame/c87fc1c067cc36ec2c5cd858c40d39f4b810aed5/openvpn/start.sh#L54). I utilize VSCode and have multiple linters and it flagged this. I don't see the start of this bracket and looks like a typo to me. Unless it's used for something special to NordVPN's related update script?

**Comment by deimosian** [comment] 2020-03-18 03:27
Seems likely, since running the script that line calls manually is what fixed it for me, I will test it when I get a chance.

**Comment by haugene** [comment] 2020-03-19 20:33
A possible fix from #1079 is merged to dev and available on the :dev tag. Can anyone test and see if this solves the issue?

**Comment by deimosian** [comment] 2020-03-19 23:27
Appears to be fixed.

**Comment by jsloan117** [comment] 2020-03-22 01:07
Good deal that it appears to be fixed. 👍

**Comment by ditisjordy** [comment] 2020-03-23 15:45
Finally got the time to check if the issue is resolved. The root cause however was that the synology firewall was blocking traffic, including DNS-requests (as suggested by jayes100 thanks for that). Therefore the updateConfigs script tried to download a file it simply could not find. I feel stupid for not thinking of this earlier... but happy to have everything working again.

**Comment by jsloan117** [comment] 2020-03-24 03:32
@timjlowe @starrbuck68 @joshmello  -- can you test this and see if this is fixed for you now and if this can be closed?

@fboterblom -- Your issue sounds different than what is being reported here I believe if you're still facing the issue?

**Comment by edgd1er** [comment] 2020-03-24 07:00
Hi,

In the log, the script cannot find the bedt server, hence cannot define a proper filename to download. at 15h22, filename is set as .ovpn which doesnot exists. You can check you parameters, through the api. Here i replaced gb by the coutry code 227, others values are the same (tcp, p2p).
`https://api.nordvpn.com/v1/servers/recommendations?filters[country_id]=227&filters[servers_technologies][identifier]=openvpn_tcp&filters[servers_group][identifier]=legacy_group_category&limit=1`

Insert your values, to check api responses. If a wrong parameter is set, api sends back an empty json array. The script define then a file without basename. If you still have a problem, you may share your log and your parameters. I hope you can use soon this great tool.

**Comment by hbh3** [comment] 2020-03-24 23:57
> @timjlowe @starrbuck68 @joshmello -- can you test this and see if this is fixed for you now and if this can be closed?

No issues for me with NordVPN.

**Comment by lennvilardi** [comment] 2020-03-27 18:52
> 
> 
> Finally got the time to check if the issue is resolved. The root cause however was that the synology firewall was blocking traffic, including DNS-requests (as suggested by jayes100 thanks for that). Therefore the updateConfigs script tried to download a file it simply could not find. I feel stupid for not thinking of this earlier... but happy to have everything working again.

How did you set the synology firewall to accept incoming from the docker image ?

**Comment by BradNut** [comment] 2020-03-28 23:45
@ditisjordy How did you go about stopping Synology Firewall from blocking both transmission ports (9091, 8888) and the DNS requests that are made from the docker image?

**Comment by ditisjordy** [comment] 2020-03-28 23:53
@BradNut I turned off the firewall on my Synology completely. I did not really need it as my NAS is in my home network And only accessible via VPN.

**Closed** 2020-05-26 01:23 UTC
