### ISSUE TITLE
Ownership Issues - Couldn't (re)open log file "/data/transmission-home/transmission.log": Permission denied

### ISSUE THREAD

**Issue by deten** [haugene/docker-transmission-openvpn#411] opened 2018-01-26 07:39 UTC
Alright, I am having an issue that I am trying to solve.  Sonarr is not able to handle files created by Transmission.  Transmission works when I use no PUID or PGID but Sonarr cannot take control over files owned by ROOT.  So I made sure Transmission was using the same PUID/PGID as Sonarr.  I deleted all config files for BOTH Transmission and Sonarr and recreated.  Sonarr seems to work fine but Transmission can't get past this step in the first startup when I use a PUID and PGID.

Here's my docker run command:
```
docker run \
    --cap-add=NET_ADMIN \
    --device=/dev/net/tun \
    -d \
    -v /volume2/Transmission/tun/resolv.conf:/etc/resolv.conf \
    -v /volume2/Transmission/:/data \
    -v /volume2/video/downloads/:/media \
    -e "PUID=1026" \
    -e "PGID=100" \
    -e "OPENVPN_PROVIDER=NORDVPN" \
    -e "OPENVPN_CONFIG=ca158.nordvpn.com.udp" \
    -e "OPENVPN_USERNAME=XXXXXXX" \
    -e "OPENVPN_PASSWORD=XXXXXXX" \
    -e "LOCAL_NETWORK=192.168.29.0/24" \
    -e "TRANSMISSION_DOWNLOAD_DIR=/media" \
    -e "TRANSMISSION_PORT_FORWARDING_ENABLED=true" \
    -e "TRANSMISSION_SPEED_LIMIT_UP=10" \
    -e "TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true" \
    -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
    -p 9091:9091 \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    --name "transmission-openvpn-syno" \
    haugene/transmission-openvpn:latest
```

Here's the log.  Note that it says "transmission.log" permission denied.  But the file isn't getting created unless I start the container with PUID/PGID blank.
```
date | stream | content
-- | -- | --
2018-01-26 07:37:38 | stderr | Couldn't (re)open log file "/data/transmission-home/transmission.log": Permission denied
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 Initialization Sequence Completed
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 /sbin/ip route add 128.0.0.0/1 via 10.8.8.1
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 /sbin/ip route add 0.0.0.0/1 via 10.8.8.1
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 /sbin/ip route add 185.44.76.155/32 via 172.17.0.1
2018-01-26 07:37:36 | stdout | Transmission startup script complete.
2018-01-26 07:37:36 | stdout | NO PORT UPDATER FOR THIS PROVIDER
2018-01-26 07:37:36 | stdout | STARTING TRANSMISSION
2018-01-26 07:37:36 | stdout |  
2018-01-26 07:37:36 | stdout | -------------------------------------
2018-01-26 07:37:36 | stdout | User gid:    100
2018-01-26 07:37:36 | stdout | User uid:    1026
2018-01-26 07:37:36 | stdout | User name:   abc
2018-01-26 07:37:36 | stdout | -------------------------------------
2018-01-26 07:37:36 | stdout | Transmission will run as
2018-01-26 07:37:36 | stdout | -------------------------------------
2018-01-26 07:37:36 | stdout |  
2018-01-26 07:37:36 | stderr | chown: cannot access '/data/watch': No such file or directory
2018-01-26 07:37:36 | stderr | chown: cannot access '/data/incomplete': No such file or directory
2018-01-26 07:37:36 | stdout | Setting owner for transmission paths to 1026:100
2018-01-26 07:37:36 | stdout | Generating transmission settings.json from env variables
2018-01-26 07:37:36 | stdout | Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.8.8.67
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 /etc/transmission/start.sh tun0 1500 1585 10.8.8.67 255.255.255.0 init
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 /sbin/ip addr add dev tun0 10.8.8.67/24 broadcast 10.8.8.255
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 /sbin/ip link set dev tun0 up mtu 1500
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 TUN/TAP TX queue length set to 100
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 TUN/TAP device tun0 opened
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:03
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 Data Channel: using negotiated cipher 'AES-256-GCM'
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 OPTIONS IMPORT: data channel crypto options modified
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 OPTIONS IMPORT: adjusting link_mtu to 1657
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 OPTIONS IMPORT: peer-id set
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 OPTIONS IMPORT: route-related options modified
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 OPTIONS IMPORT: route options modified
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 OPTIONS IMPORT: --ifconfig/up options modified
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 Socket Buffers: R=[212992->425984] S=[212992->425984]
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 OPTIONS IMPORT: timers and/or timeouts modified
2018-01-26 07:37:36 | stdout | Fri Jan 26 07:37:36 2018 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,sndbuf 524288,rcvbuf 524288,dhcp-option DNS 78.46.223.24,dhcp-option DNS 162.242.211.137,route-gateway 10.8.8.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.8.67 255.255.255.0,peer-id 45,cipher AES-256-GCM'
2018-01-26 07:37:35 | stdout | Fri Jan 26 07:37:35 2018 SENT CONTROL [uk50.nordvpn.com]: 'PUSH_REQUEST' (status=1)
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 [uk50.nordvpn.com] Peer Connection Initiated with [AF_INET]185.44.76.155:1194
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 VERIFY OK: depth=0, C=PA, ST=PA, L=Panama, O=NordVPN, OU=NordVPN, CN=uk50.nordvpn.com, name=NordVPN, emailAddress=cert@nordvpn.com
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 VERIFY EKU OK
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 Validating certificate extended key usage
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 VERIFY KU OK
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 VERIFY OK: depth=1, C=PA, ST=PA, L=Panama, O=NordVPN, OU=NordVPN, CN=uk50.nordvpn.com, name=NordVPN, emailAddress=cert@nordvpn.com
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 TLS: Initial packet from [AF_INET]185.44.76.155:1194, sid=ef276462 718bafd6
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 UDP link remote: [AF_INET]185.44.76.155:1194
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 UDP link local: (not bound)
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 Socket Buffers: R=[212992->212992] S=[212992->212992]
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]185.44.76.155:1194
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
2018-01-26 07:37:34 | stdout | Fri Jan 26 07:37:34 2018 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 26 2017
2018-01-26 07:37:33 | stdout | adding route to local network 192.168.29.0/24 via 172.17.0.1 dev eth0
2018-01-26 07:37:33 | stdout | Setting OPENVPN credentials...
2018-01-26 07:37:33 | stdout | Using default OpenVPN gateway for provider nordvpn
2018-01-26 07:37:33 | stdout | Supplied config ca158.nordvpn.com.udp.ovpn could not be found.
2018-01-26 07:37:33 | stdout | Using OpenVPN provider: NORDVPN


```

**Comment by haugene** [comment] 2018-01-26 10:30
Closing this as a duplicate of #361, follow up there.

**Closed by haugene** 2018-01-26 10:30 UTC
