### ISSUE TITLE
DEV container fails to start with PATH issue

### ISSUE THREAD

**Issue by PalasX** [haugene/docker-transmission-openvpn#1916] opened 2021-08-24 01:27 UTC
## Before creating this issue I have:

**REQUIRED**
- [X] Read through the pinned issues for related problems
- [X] Searched for similar [provider issues][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible
- [X] Verified I have tried using newest release as well
- [X] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release

**Required, problem occurs in : DEV** 
 
```DEV```

*If possible, last working version:* 
 
```3.7 60498d2fcb0c```

### Describe the problem

**REQUIRED**
```I tried to switch to the DEV container because i have been plagued by DNS issues (DNS not respected) and connection issues on :latest (3.7). I was using a CUSTOM provider (manual setup of SLICKVPN) and got the same results. Container fails to start with:
Options error: --ca fails with '/etc/openvpn/slickvpn//etc/openvpn/slickvpn/ca.crt': No such file or directory (errno=2)
```
### Describe the steps you have tried to solve the problem

**REQUIRED**
```version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/home/pi/Docker/transmission-openvpn/data/:/data'
        environment:
            - OPENVPN_PROVIDER=SLICKVPN
            - OPENVPN_CONFIG=United-States-Charlotte,United-States-New-York,United-States-Chicago
            - OPENVPN_USERNAME=USERNAMEUSERNAMEUSRENAME
            - OPENVPN_PASSWORD=PASSWORDPASSWORDPASSWORD
            - LOCAL_NETWORK=192.168.1.0/24
            - TZ=America/New_York
            - TR_CURL_SSL_NO_VERIFY=1
            - OVERRIDE_DNS_1=8.8.8.8
            - OVERRIDE_DNS_2=8.8.4.4
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 1.1.1.1
        image: haugene/transmission-openvpn:dev
```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```
        environment:
            - OPENVPN_PROVIDER=SLICKVPN
            - OPENVPN_CONFIG=United-States-Charlotte,United-States-New-York,United-States-Chicago
            - OPENVPN_USERNAME=USERNAMEUSERNAMEUSRENAME
            - OPENVPN_PASSWORD=PASSWORDPASSWORDPASSWORD
            - LOCAL_NETWORK=192.168.1.0/24
            - TZ=America/New_York
            - TR_CURL_SSL_NO_VERIFY=1
            - OVERRIDE_DNS_1=8.8.8.8
            - OVERRIDE_DNS_2=8.8.4.4
```

### Logs

 

**REQUIRED**
```
Starting container with revision: 0bd47cb67bf0d106096f844cc5b9fe1b4f444c09

One or more OVERRIDE_DNS addresses found. Will use them to overwrite /etc/resolv.conf

Creating TUN device /dev/net/tun

Using OpenVPN provider: SLICKVPN

Running with VPN_CONFIG_SOURCE auto

No bundled config script found for SLICKVPN. Defaulting to external config

Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.4C14xK6ZST

Extracting configs to /tmp/tmp.LIwqF3XSVM

Found configs for SLICKVPN in /tmp/tmp.LIwqF3XSVM/vpn-configs-contrib-main/openvpn/slickvpn, will replace current content in /etc/openvpn/slickvpn

Cleanup: deleting /tmp/tmp.4C14xK6ZST and /tmp/tmp.LIwqF3XSVM

3 servers found in OPENVPN_CONFIG, United-States-Chicago chosen randomly

Starting OpenVPN using config United-States-Chicago.ovpn

Modifying /etc/openvpn/slickvpn/United-States-Chicago.ovpn for best behaviour in this container

Modification: Point auth-user-pass option to the username/password file

Modification: Change ca certificate path

Modification: Change ping options

Setting OpenVPN credentials...

adding route to local network 192.168.1.0/24 via 172.27.0.1 dev eth0

Options error: --ca fails with '/etc/openvpn/slickvpn//etc/openvpn/slickvpn/ca.crt': No such file or directory (errno=2)

Options error: Please correct these errors.

Use --help for more information.
```

### Host system

**REQUIRED**
```
Raspberry Pi 4
Docker version 20.10.7, build f0df350
```

**Comment by pkishino** [comment] 2021-08-24 04:06
could you post the contents of the 
/etc/openvpn/slickvpn/United-States-Chicago.ovpn
file here please?
I think I know what the problem is..

**Comment by pkishino** [comment] 2021-08-24 04:08
you can also fix it for now by replacing:
/etc/openvpn/slickvpn//etc/openvpn/slickvpn/ca.crt
in the above file to 
/etc/openvpn/slickvpn/ca.crt

**Comment by pkishino** [comment] 2021-08-24 04:16
should be fixed now

**Comment by PalasX** [comment] 2021-08-24 12:22
Good morning!

Content of the requested file was:

``
remote gw1.ord1.slickvpn.com 443 udp
remote gw1.ord2.slickvpn.com 443 udp
remote gw1.ord3.slickvpn.com 443 udp
remote gw2.ord1.slickvpn.com 443 udp
remote gw2.ord2.slickvpn.com 443 udp
remote gw2.ord3.slickvpn.com 443 udp
remote gw3.ord1.slickvpn.com 443 udp
remote gw3.ord2.slickvpn.com 443 udp
remote gw3.ord3.slickvpn.com 443 udp
auth-user-pass /config/openvpn-credentials.txt
client
redirect-gateway
remote-cert-tls server
cipher AES-256-CBC
proto udp
dev tun
nobind
ca /etc/openvpn/slickvpn/ca.crt
``

**Comment by PalasX** [comment] 2021-08-24 12:27
Pulled latest DEV. Container now fails to start with:

```
Tue Aug 24 08:26:18 2021 Cannot load CA certificate file /etc/openvpn/slickvpn/ (no entries were read)
Tue Aug 24 08:26:18 2021 Exiting due to fatal error
```

**Comment by pkishino** [comment] 2021-08-24 12:50
can you post the content of the same file now with latest please?

**Comment by PalasX** [comment] 2021-08-24 12:55
relevant parts of docker-compose:
```
        volumes:
            - '/home/pi/Docker/transmission-openvpn/slickvpn/:/etc/openvpn/custom/'
            - '/home/pi/Docker/transmission-openvpn/data/:/data'
        environment:
            - OPENVPN_PROVIDER=CUSTOM
#            - OPENVPN_CONFIG=United-States-Charlotte,United-States-New-York,United-States-Chicago
            - OPENVPN_CONFIG=chicago

```

chicago.ovpn
```

# host/port of vpn server
remote gw1.ord4.slickvpn.com 443 udp

# prompt for authentication
auth-user-pass /config/openvpn-credentials.txt

# equivalent to pull, tls-client
client

# redirect all outgoing traffic to the vpn gateway
redirect-gateway

# verify the server certificate for authenticity
remote-cert-tls server

cipher AES-256-CBC

proto udp
dev tun
keepalive 10 120
nobind

persist-key
persist-tun

# ssl certificate / key used for tls
ca /etc/openvpn/custom/ca.slickvpn.com.crt
```

contents of that path
```
pi@RasPi4:~/Docker/transmission-openvpn/slickvpn $ ls -al
total 36
drwxrwxrwx 2 pi pi 4096 Aug 24 08:53 .
drwxr-xr-x 4 pi pi 4096 Aug 24 08:53 ..
-rwxrwxrwx 1 pi pi 1206 Aug 19 14:22 ca.slickvpn.com.crt
-rwxrwxrwx 1 pi pi  459 Aug 19 14:27 charlotte.ovpn
-rwxrwxrwx 1 pi pi  491 Aug 24 08:50 chicago.ovpn
-rwxrwxrwx 1 pi pi  491 Aug 19 14:29 france.ovpn
-rwxrwxrwx 1 pi pi  491 Aug 19 14:29 miami.ovpn
-rwxrwxrwx 1 pi pi  491 Aug 19 14:29 newyork.ovpn
-rwxrwxrwx 1 pi pi  491 Aug 19 14:29 stockholm.ovpn
```

I'm using CUSTOM as shown in docker-compose.yml, but same things happens with SLICKVPN as provider. How do i get the contents of the .ovpn file you requested without the container running? im still a bit of a docker noob.

**Comment by PalasX** [comment] 2021-08-24 13:52
used docker cp container:local to get what docker sees for my custom copy of slickvpn, and it looks like its modifying the .ovpn files incorrectly?

```
# host/port of vpn server
remote gw1.ord4.slickvpn.com 443 udp

# prompt for authentication
auth-user-pass /config/openvpn-credentials.txt

# equivalent to pull, tls-client
client

# redirect all outgoing traffic to the vpn gateway
redirect-gateway

# verify the server certificate for authenticity
remote-cert-tls server

cipher AES-256-CBC

proto udp
dev tun
nobind

persist-key
persist-tun

# ssl certificate / key used for tls
ca /etc/openvpn/custom/
inactive 3600
ping 10
ping-exit 60
```
it appears to have broken the 'ca' line from the original, somehow?

**Comment by PalasX** [comment] 2021-08-24 16:53
workaround was to set it read only, and then set it immutable so that even root could not alter it:
```
sudo chattr +i file
```

Obviously, not the right fix, but after this, DEV seems to be running ok. doesn't seem to have fixed the initial problem i was having getting connected to trackers and peers, but it IS erspecting my DNS settings now, at least.

**Comment by pkishino** [comment] 2021-08-24 23:34
hmm, 
yeah, I see my mistake..
anyway, you can try to add this env. variable
CONFIG_MOD_CA_CERTS false
this will avoid modifying the ovpn regarding ca cert.. 
but I will fix this soon

**Comment by pkishino** [comment] 2021-08-24 23:44
I made a small adjustment, feel free to try it

**Comment by PalasX** [comment] 2021-08-25 00:05
Can confirm that latest pull of :DEV works correctly, and does not overwrite/blankout cert file, runs as expected with a clean .ovpn file.

Thanks for the fix!

**Closed** 2021-08-25 00:07 UTC
Labels: bug
