### ISSUE TITLE
Transmission rep-orts VPN unreachable

### ISSUE THREAD

**Issue by TheMightyZarquon** [haugene/docker-transmission-openvpn#1886] opened 2021-07-24 04:06 UTC
## Before creating this issue I have:

**REQUIRED**
- [x] Read through the pinned issues for related problems
- [x] Searched for similar [provider issues][pi] and [container issues][ci]
- [x] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [x] Tried to add as much relevant information to the issue as possible
- [x] Verified I have tried using newest release as well
- [x] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release

**Required, problem occurs in :** 
 
```<5:20.10.7~3-0~debian-buster>```

*If possible, last working version:* 
 
```<Leave empty if not known>```

### Describe the problem

**REQUIRED**
```txt
<Transmission will no longer connect to PrivateInternetAccess as of yesterday. 
The host was set up on Jun 3 and the containers were set up Jun , running since then without issue.>
```
### Describe the steps you have tried to solve the problem

**REQUIRED**
```txt
<I have tried recreating the container multiple times with different DNS settings
such as using the standard environment variable DNS= and tried the DNS override variable even though I do not 
believe the issue is a DNS issue.
I have tried the example run command on the Running the container page on the website.
The host has been restarted.
Tried telnetting to the specified VPN host on the specified port on the host machine and a different machine
successfully on both machines.>
```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```txt
<transmission-openvpn:
    volumes:
        - /srv/dev-disk-by-uuid-2fb96017-5a49-4450-8526-f318538ef6f2/media/downloads:/media/downloads
        - /srv/dev-disk-by-uuid-2fb96017-5a49-4450-8526-f318538ef6f2/data:/data
        - /etc/localtime:/etc/localtime:ro
    environment:
        - PUID=1000
        - PGID=100
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=PIA
        - OPENVPN_CONFIG=new_zealand
        - OPENVPN_USERNAME=redacted
        - OPENVPN_PASSWORD=redacted
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --dhcp-option DNS 8.8.8.8
        - WEBPROXY_ENABLED=false
        - LOCAL_NETWORK=10.210.0.0/24
        - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        - TRANSMISSION_DOWNLOAD_DIR=/media/downloads
        #- DNS=8.8.8.8,8.8.4.4
        #- OVERRIDE_DNS_1=8.8.8.8
        #- OVERRIDE_DNS_2=8.8.4.4
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - 9091:9091
        - 9117:9117
        - 7878:7878
        - 8989:8989
        - 8686:8686
        - 5299:5299
    restart: always
    image: haugene/transmission-openvpn>
```

### Logs

 

**REQUIRED**
```txt
<Starting container with revision: 9a9d30f95281ff8361f30db26b336de97d43fac5
Creating TUN device /dev/net/tun
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.PCAGAl
curl: (7) Failed to connect to www.privateinternetaccess.com port 443: Host is unreachable
Starting container with revision: 9a9d30f95281ff8361f30db26b336de97d43fac5
Creating TUN device /dev/net/tun
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.ebAEaL
curl: (7) Failed to connect to www.privateinternetaccess.com port 443: Host is unreachable>
```

### Host system

**REQUIRED**
```txt
<Host: OpenMediaVault 5.6.12-1 (Usul) fully updated
Docker: 5:20.10.7~3-0~debian-buster>
```

**Comment by pkishino** [comment] 2021-07-24 13:58
Checked #1866 ??

**Comment by pkishino** [comment] 2021-08-01 23:54
suspected duplicate of #1866

**Closed by pkishino** 2021-08-01 23:54 UTC
Labels: bug
