### ISSUE TITLE
NordVPN startup script failing: "Supplied config ... could not be found"

### ISSUE THREAD

**Issue by No4cc3ss** [haugene/docker-transmission-openvpn#1451] opened 2020-11-01 20:17 UTC
Hello,

 

Having Unraid installed on my DIY NAS for 4 months, I faced very little problem but here I admit that I am a bit stuck.

I just updated the "haugene / transmission-openvpn" docker and now it no longer wants this to connect to my NordVPN account.

I reluctantly remove my container and reinstall it! but still the mm thing.

I spent 2 days doing the forum and I went to see the dev side but I didn't really understand everything! Anyone have any info on the subject or manip?

 

Thank you in advance for your kindness :) 

```
Provider NORDVPN has a custom startup script, executing it
Downloading user specified config. NORDVPN_PROTOCOL is set to: UDP
2020-10-31 11:09:17 Checking curl installation
2020-10-31 11:09:17 Removing existing configs
2020-10-31 11:09:17 Selecting the best server...
2020-10-31 11:09:17 Searching for group: legacy_p2p
2020-10-31 11:09:17 Searching for technology: openvpn_udp
2020-10-31 11:09:17 Best server : fr617.nordvpn.com
2020-10-31 11:09:17 Downloading config: default.ovpn
2020-10-31 11:09:17 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/fr617.nordvpn.com.udp.ovpn
2020-10-31 11:09:17 Using OpenVPN CONFIG :: norway
2020-10-31 11:09:17 Downloading config: norway.ovpn
2020-10-31 11:09:17 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/norway.udp.ovpn
2020-10-31 11:09:17 Checking line endings
2020-10-31 11:09:17 Updating configs for docker-transmission-openvpn
Supplied config Norway.ovpn could not be found.
mknod: /dev/net/tun: File exists
Using OpenVPN provider: NORDVPN
Provider NORDVPN has a custom startup script, executing it
Downloading user specified config. NORDVPN_PROTOCOL is set to: UDP
2020-10-31 11:09:33 Checking curl installation
2020-10-31 11:09:33 Removing existing configs
2020-10-31 11:09:33 Selecting the best server...
2020-10-31 11:09:33 Searching for group: legacy_p2p
2020-10-31 11:09:33 Searching for technology: openvpn_udp
2020-10-31 11:09:33 Searching for group: legacy_p2p
2020-10-31 11:09:33 Searching for technology: openvpn_udp
2020-10-31 11:09:33 Best server : fr617.nordvpn.com
2020-10-31 11:09:33 Downloading config: default.ovpn
2020-10-31 11:09:33 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/fr617.nordvpn.com.udp.ovpn
2020-10-31 11:09:33 Using OpenVPN CONFIG :: norway
2020-10-31 11:09:33 Downloading config: norway.ovpn
2020-10-31 11:09:33 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/norway.udp.ovpn
2020-10-31 11:09:33 Checking line endings
2020-10-31 11:09:33 Updating configs for docker-transmission-openvpn
Supplied config Norway.ovpn could not be found.
```

**Comment by Kmanxx** [comment] 2020-11-01 21:19
Having the same issue but with PIA

**Comment by haugene** [comment] 2020-11-02 00:55
@No4cc3ss Can you please share your setup as well. I.e the docker run command or docker compose file you are using?

**Comment by No4cc3ss** [comment] 2020-11-02 06:20
Hello @haugene ,

Here is my dockerfiles details:

`

CMD | dumb-init /etc/openvpn/start.sh
-- | --
EXPOSE | 9091/tcp
VOLUME | /config                                    /data
ENV | PATH                     /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                        OPENVPN_USERNAME                     **None**                                        OPENVPN_PASSWORD                     **None**                                        OPENVPN_PROVIDER                     **None**                                        GLOBAL_APPLY_PERMISSIONS                     true                                        TRANSMISSION_HOME                     /data/transmission-home                                        TRANSMISSION_RPC_PORT                     9091                                        TRANSMISSION_DOWNLOAD_DIR                     /data/completed                                        TRANSMISSION_INCOMPLETE_DIR                     /data/incomplete                                        TRANSMISSION_WATCH_DIR                     /data/watch                                        CREATE_TUN_DEVICE                     true                                        ENABLE_UFW                     false                                        UFW_ALLOW_GW_NET                     false                                        UFW_EXTRA_PORTS                                                             UFW_DISABLE_IPTABLES_REJECT                     false                                        PUID                                                             PGID                                                             DROP_DEFAULT_ROUTE                                                             WEBPROXY_ENABLED                     false                                        WEBPROXY_PORT                     8888                                        WEBPROXY_USERNAME                                                             WEBPROXY_PASSWORD                                                             LOG_TO_STDOUT                     false                                        HEALTH_CHECK_HOST                     google.com | PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin | OPENVPN_USERNAME | **None** | OPENVPN_PASSWORD | **None** | OPENVPN_PROVIDER | **None** | GLOBAL_APPLY_PERMISSIONS | true | TRANSMISSION_HOME | /data/transmission-home | TRANSMISSION_RPC_PORT | 9091 | TRANSMISSION_DOWNLOAD_DIR | /data/completed | TRANSMISSION_INCOMPLETE_DIR | /data/incomplete | TRANSMISSION_WATCH_DIR | /data/watch | CREATE_TUN_DEVICE | true | ENABLE_UFW | false | UFW_ALLOW_GW_NET | false | UFW_EXTRA_PORTS |   | UFW_DISABLE_IPTABLES_REJECT | false | PUID |   | PGID |   | DROP_DEFAULT_ROUTE |   | WEBPROXY_ENABLED | false | WEBPROXY_PORT | 8888 | WEBPROXY_USERNAME |   | WEBPROXY_PASSWORD |   | LOG_TO_STDOUT | false | HEALTH_CHECK_HOST | google.com
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
OPENVPN_USERNAME | **None**
OPENVPN_PASSWORD | **None**
OPENVPN_PROVIDER | **None**
GLOBAL_APPLY_PERMISSIONS | true
TRANSMISSION_HOME | /data/transmission-home
TRANSMISSION_RPC_PORT | 9091
TRANSMISSION_DOWNLOAD_DIR | /data/completed
TRANSMISSION_INCOMPLETE_DIR | /data/incomplete
TRANSMISSION_WATCH_DIR | /data/watch
CREATE_TUN_DEVICE | true
ENABLE_UFW | false
UFW_ALLOW_GW_NET | false
UFW_EXTRA_PORTS |  
UFW_DISABLE_IPTABLES_REJECT | false
PUID |  
PGID |  
DROP_DEFAULT_ROUTE |  
WEBPROXY_ENABLED | false
WEBPROXY_PORT | 8888
WEBPROXY_USERNAME |  
WEBPROXY_PASSWORD |  
LOG_TO_STDOUT | false
HEALTH_CHECK_HOST | google.com

`

**Comment by andsoitgoes** [comment] 2020-11-02 08:21
Same issue but canada

**Comment by No4cc3ss** [comment] 2020-11-02 18:44
hello,

should these two files be added to the Transmission-VPN folder?
updateConfigs.sh, configure-openvpn.sh

Thx

**Comment by cfdojan** [comment] 2020-11-02 20:37
Same issue but PIA

**Comment by johnRambo2k14** [comment] 2020-11-02 23:13
Same here, I'm using PIA too.

**Comment by cfdojan** [comment] 2020-11-03 03:34
#1446 also fixed my problem. Thanks for the help!

**Comment by eroji** [comment] 2020-11-03 06:24
I'm not sure I get what in #1446 is the fix. I can see that /etc/openvpn/pia is populated. It seems like `CA Vancouver.ovpn` is now gone. I tried changing to using `CA Toronto.ovpn` which exists, but it still says it couldn't find it.

```
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom startup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.mOjCck
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Modify configs for this container
Supplied config "CA Toronto".ovpn could not be found.
```

**Comment by haugene** [comment] 2020-11-03 08:55
@eroji Look at the config it tries to use. You need to remove the quotation.
> Supplied config "CA Toronto".ovpn could not be found.

**Comment by haugene** [comment] 2020-11-03 08:57
The Nordvpn issue is a more peculiar one. I will have a look at it, but in the meantime I would suggest that you use the 2.14 tag version of the image where I guess this is not an issue. This might have to do with us now running busybox versions of a lot of tools and they don't always behave the same way. Will have a look later :monocle_face:

**Comment by eroji** [comment] 2020-11-03 09:04
> @eroji Look at the config it tries to use. You need to remove the quotation.
> 
> > Supplied config "CA Toronto".ovpn could not be found.

That's strange. It always worked with quotes before. Removing it got it further, however still won't start. It seems to be related to UFW

```
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom startup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.aomDKj
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Modify configs for this container
Starting OpenVPN using config CA Toronto.ovpn
Setting OpenVPN credentials...
enabling firewall
Firewall is active and enabled on system startup
allowing 49152:65535 through the firewall
ERROR: Must specify 'tcp' or 'udp' with multiple ports
```

If I turn off UFW it seems to attempt to connect, but it fails at authentication. I verified that my PIA login information is correct.

```
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom startup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.mFOjgG
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Modify configs for this container
Starting OpenVPN using config CA Toronto.ovpn
Setting OpenVPN credentials...
adding route to local network 10.64.0.0/16 via 172.18.0.1 dev eth0
adding route to local network 172.20.0.0/16 via 172.18.0.1 dev eth0
Tue Nov  3 01:00:15 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Tue Nov  3 01:00:15 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Tue Nov  3 01:00:15 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Nov  3 01:00:15 2020 CRL: loaded 1 CRLs from file [[INLINE]]
Tue Nov  3 01:00:15 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]154.3.42.92:1198
Tue Nov  3 01:00:15 2020 UDP link local: (not bound)
Tue Nov  3 01:00:15 2020 UDP link remote: [AF_INET]154.3.42.92:1198
Tue Nov  3 01:00:15 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue Nov  3 01:00:15 2020 [toronto424] Peer Connection Initiated with [AF_INET]154.3.42.92:1198
Tue Nov  3 01:00:16 2020 AUTH: Received control message: AUTH_FAILED
Tue Nov  3 01:00:16 2020 SIGTERM[soft,auth-failure] received, process exiting
```

**Comment by haugene** [comment] 2020-11-03 09:20
@eroji Yeah. But see #1334. 2.14 will not work for PIA for long. They are shutting down the old servers and switching to the new: https://www.privateinternetaccess.com/blog/private-internet-access-legacy-vpn-network-sunset-announcement-30-september

With the new servers the username/password is now your main PIA credentials with a username looking like p[seven digits] instead of the openvpn specific password from the old servers where the username was x[some digits].

There seems to be an issue with UFW with your combination of settings though. Can you share your docker run command, or docker-compose file?

**Comment by eroji** [comment] 2020-11-03 09:25
> @eroji Yeah. But see #1334. 2.14 will not work for PIA for long. They are shutting down the old servers and switching to the new: https://www.privateinternetaccess.com/blog/private-internet-access-legacy-vpn-network-sunset-announcement-30-september
> 
> With the new servers the username/password is now your main PIA credentials with a username looking like p[seven digits] instead of the openvpn specific password from the old servers where the username was x[some digits].
> 
> There seems to be an issue with UFW with your combination of settings though. Can you share your docker run command, or docker-compose file?

That's interesting. This is honestly the first I've heard of the news. As for the password and login, I am not clear on what you mean. I've always had a username of `p` and some number. The password has always been a random string.

Here is the portion of docker-compose that pertains to Transmission.

```
  transmission:
    cap_add:
      - NET_ADMIN
    container_name: transmission
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - PUID=0
      - PGID=1513
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=p123456
      - OPENVPN_PASSWORD=somePassword123
      - OPENVPN_CONFIG=CA Vancouver
      - ENABLE_UFW=true
      - UFW_ALLOW_GW_NET=true
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - 'LOCAL_NETWORK=10.64.0.0/16,172.20.0.0/16'
      - TRANSMISSION_BLOCKLIST_ENABLED=true
      - 'TRANSMISSION_BLOCKLIST_URL=http://john.bitsurge.net/public/biglist.p2p.gz'
      - TRANSMISSION_DOWNLOAD_DIR=/downloads
      - TRANSMISSION_ENCRYPTION=0
      - TRANSMISSION_LPD_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
      - TRANSMISSION_PEER_LIMIT_GLOBAL=250
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=50
      - TRANSMISSION_RATIO_LIMIT=5
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=20
      - TRANSMISSION_PEER_PORT_RANDOM_HIGH=65535
      - TRANSMISSION_PEER_PORT_RANDOM_LOW=49152
      - TRANSMISSION_PEER_PORT_RANDOM_ON_START=true
      - TRANSMISSION_PORT_FORWARDING_ENABLED=true
      - TRANSMISSION_UMASK=7
    image: haugene/transmission-openvpn:2.14
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './config/transmission:/data/transmission-home'
      - ...
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    restart: always

**Comment by No4cc3ss** [comment] 2020-11-03 09:26
> 
> 
> The Nordvpn issue is a more peculiar one. I will have a look at it, but in the meantime I would suggest that you use the 2.14 tag version of the image where I guess this is not an issue. This might have to do with us now running busybox versions of a lot of tools and they don't always behave the same way. Will have a look later 🧐

Merci à toi, effectivement je suis repassé sous la version 2.14 et tout refonctionne correctement. En tout cas merci pour ton travail.

**Comment by haugene** [comment] 2020-11-03 11:58
@eroji Looking at your compose file I just want to say that if you don't want to specify Transmission settings as environment variables, but rather do it in the UI, you can do that now. The changes will be persistent between container restarts. There are a couple of exceptions to the rule, and those are the ones that are set in the Dockerfile. They are needed by various scripts.
You should also drop the `devices:` mounting. That is no longer needed in version 3.

About the AUTH_FAILED. I have not seen a case yet where this does not mean that your credentials are wrong.
On the old servers (that are due to shut down) there is a separate username/password pair that you can find in your control panel after logging in to PIA. It is listed under "PPTP/L2TP/SOCKS Username and Password" and username typically starts with an x. And for the nextgen servers they have changed this and are now using the same credentials for the ovpn connections as you use to sign in to the client control panel: https://www.privateinternetaccess.com/pages/client-sign-in

If you still have issues, it might be that the values you pass in are not persisted correctly and the wrong values are used by the container. In that case I want to know so that we can fix it. Have a look in /config/openvpn-credentials.txt inside the container and see if it matches what you set in the variables.

**Comment by eroji** [comment] 2020-11-03 19:10
@haugene It seems to be an issue with `CA Toronto`. When I try another location such as `CA Montreal` it works. Has the list of locations that supports port-forwarding changed?

```
Using OpenVPN provider: PIA
Provider PIA has a custom startup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.aJFaod
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Modify configs for this container
Starting OpenVPN using config CA Montreal.ovpn
Setting OpenVPN credentials...
enabling firewall
Firewall is active and enabled on system startup
allowing 172.18.0.0/16 through the firewall to port 9091
Rule added
adding route to local network 10.64.0.0/16 via 172.18.0.1 dev eth0
allowing 10.64.0.0/16 through the firewall to port 9091
Rule added
adding route to local network 172.20.0.0/16 via 172.18.0.1 dev eth0
allowing 172.20.0.0/16 through the firewall to port 9091
Rule added
Tue Nov  3 11:04:48 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Tue Nov  3 11:04:48 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Tue Nov  3 11:04:48 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Nov  3 11:04:48 2020 CRL: loaded 1 CRLs from file [[INLINE]]
Tue Nov  3 11:04:48 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.71.71:1198
Tue Nov  3 11:04:48 2020 UDP link local: (not bound)
Tue Nov  3 11:04:48 2020 UDP link remote: [AF_INET]172.98.71.71:1198
Tue Nov  3 11:04:48 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue Nov  3 11:04:48 2020 [montreal402] Peer Connection Initiated with [AF_INET]172.98.71.71:1198
Tue Nov  3 11:04:49 2020 TUN/TAP device tun0 opened
Tue Nov  3 11:04:49 2020 /sbin/ip link set dev tun0 up mtu 1500
Tue Nov  3 11:04:49 2020 /sbin/ip addr add dev tun0 10.5.112.25/24 broadcast 10.5.112.255
Tue Nov  3 11:04:49 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.5.112.25 255.255.255.0 init
Up script executed with tun0 1500 1558 10.5.112.25 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.5.112.25
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.5.112.25
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding umask because TRANSMISSION_UMASK is set to 7
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
sed'ing True to true

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

STARTING TRANSMISSION
Provider PIA has a script for automatic port forwarding. Will run it now.
If you want to disable this, set environment variable DISABLE_PORT_UPDATER=yes
Transmission startup script complete.
Tue Nov  3 11:04:50 2020 Initialization Sequence Completed
yes: Broken pipe



port is 46152
the port has been bound to 46152  Tue Nov  3 11:04:56 PST 2020
transmission auth not required
waiting for transmission to become responsive
transmission became responsive
    24   100%    1.45 GB  Done         0.0     0.0    0.0  Idle         [SubsPlease] One Piece - 944 (1080p) [84D09F06].mkv
Sum:            228.6 GB               0.0     0.0
Update UFW rules before changing port in Transmission
denying access to 53864
Rule added
allowing 46152 through the firewall
Rule added
setting transmission port to 46152
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Port is open: Yes

initial setup complete!

waiting for rebind loop.................
token expiry 1609858502
remaining = 5428193
```

Just for sanity check, my docker-compose looks like this now. I assume this is correct for version 3.x and up?

```
  transmission:
    cap_add:
      - NET_ADMIN
    container_name: transmission
    #devices:
    #  - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - PUID=0
      - PGID=1513
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=p123456
      - OPENVPN_PASSWORD=somePassword123
      - OPENVPN_CONFIG=CA Montreal
      - ENABLE_UFW=true
      - UFW_ALLOW_GW_NET=true
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - 'LOCAL_NETWORK=10.64.0.0/16,172.20.0.0/16'
      - TRANSMISSION_UMASK=7
    image: haugene/transmission-openvpn
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './config/watch:/data/watch'
      - './config/transmission:/data/transmission-home'
      - ...
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
```

**Comment by haugene** [comment] 2020-11-03 20:22
@eroji :+1: Glad you got it working. About the port-forwarding regions/servers I don't know. I think I've read that they all should support it but you'd have to ask PIA themselves.

Renaming this issue to address the NordVPN configs directly. All other problems should be addressed in other issues (please look for similar issues before creating a new one).

**Comment by haugene** [comment] 2020-11-03 21:20
@No4cc3ss @andsoitgoes I can't seem to reproduce this. If I run the container it downloads a config and tries to connect but gets auth_failed as expected. What happens if you run this command?
```
$ docker run --rm -it -e OPENVPN_PROVIDER=NORDVPN -e OPENVPN_USERNAME=user -e OPENVPN_PASSWORD=pass haugene/transmission-openvpn
Using OpenVPN provider: NORDVPN
Provider NORDVPN has a custom startup script, executing it
2020-11-03 21:18:02 Checking curl installation
2020-11-03 21:18:02 Removing existing configs
2020-11-03 21:18:02 Selecting the best server...
2020-11-03 21:18:02 Searching for group: legacy_p2p
2020-11-03 21:18:02 Searching for technology: openvpn_udp
2020-11-03 21:18:02 Best server : no184.nordvpn.com
2020-11-03 21:18:02 Downloading config: default.ovpn
2020-11-03 21:18:02 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/no184.nordvpn.com.udp.ovpn
2020-11-03 21:18:02 Checking line endings
2020-11-03 21:18:02 Updating configs for docker-transmission-openvpn
Starting OpenVPN using config default.ovpn
Setting OpenVPN credentials...
Tue Nov  3 21:18:03 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Tue Nov  3 21:18:03 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Tue Nov  3 21:18:03 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Nov  3 21:18:03 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Nov  3 21:18:03 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Nov  3 21:18:03 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]37.120.149.42:1194
Tue Nov  3 21:18:03 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]
Tue Nov  3 21:18:03 2020 UDP link local: (not bound)
Tue Nov  3 21:18:03 2020 UDP link remote: [AF_INET]37.120.149.42:1194
Tue Nov  3 21:18:03 2020 TLS: Initial packet from [AF_INET]37.120.149.42:1194, sid=4d750fd1 bf1d90f7
Tue Nov  3 21:18:03 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue Nov  3 21:18:03 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Tue Nov  3 21:18:03 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA5
Tue Nov  3 21:18:03 2020 VERIFY KU OK
Tue Nov  3 21:18:03 2020 Validating certificate extended key usage
Tue Nov  3 21:18:03 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Tue Nov  3 21:18:03 2020 VERIFY EKU OK
Tue Nov  3 21:18:03 2020 VERIFY OK: depth=0, CN=no184.nordvpn.com
Tue Nov  3 21:18:05 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Tue Nov  3 21:18:05 2020 [no184.nordvpn.com] Peer Connection Initiated with [AF_INET]37.120.149.42:1194
Tue Nov  3 21:18:06 2020 SENT CONTROL [no184.nordvpn.com]: 'PUSH_REQUEST' (status=1)
Tue Nov  3 21:18:06 2020 AUTH: Received control message: AUTH_FAILED
Tue Nov  3 21:18:06 2020 SIGTERM[soft,auth-failure] received, process exiting
```

Have you recently done a `docker pull haugene/transmission-openvpn`? What do you get if you run `docker image inspect haugene/transmission-openvpn --format '{{ .RepoDigests }}'`?

**Comment by JohnAustin16** [comment] 2020-11-08 01:25
I just pushed a code to hopefully fix this issue. In the meantime, for anyone having this issue with Nord VPN the problem lines with a faulty url in updateConfigs.sh for Nord VPN, the quick fix is to use ch283.nordvpn.com for your OPENVPN_CONFIG. ch283 is the server I chose you can choose what server you want from Nord VPN but the whole string needs to be inputted in your docker compose file ie:
'''OPENVPN_CONFIG=ch283.nordvpn.com'''

**Closed** 2021-01-15 14:56 UTC
Labels: enhancement, inactivity
