### ISSUE TITLE
Support for ProtonVPN (Newer thread)

### ISSUE THREAD

**Issue by bfayers** [haugene/docker-transmission-openvpn#378] opened 2018-01-02 11:28 UTC
Add VPN support for [protonvpn](https://protonvpn.com/)

**Comment by fabienheureux** [comment] 2018-01-04 09:27
It seems that it had already been discussed here: https://github.com/haugene/docker-transmission-openvpn/issues/271

**Comment by haugene** [comment] 2018-02-05 22:58
Yup, this issue is a duplicate of #271. It's higher up the list. Maybe someone will see it if I tag it. And maybe I'll have the time to add it myself as well. Are the links to the other issue still good?

**Comment by coolboiime** [comment] 2018-07-09 14:01
Closing this for merging into issue #554! Please have all issues and updates directed towards that issue. Closing this for now, thanks!

**Closed by coolboiime** 2018-07-09 14:01 UTC
Labels: enhancement, help wanted

**Comment by haugene** [comment] 2019-02-09 23:28
#704 now merged
