### ISSUE TITLE
Container not initialising properly when launched as part of a Portainer stack

### ISSUE THREAD

**Issue by Rand404** [haugene/docker-transmission-openvpn#2606] opened 2023-05-06 13:34 UTC
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

version: "3.7"
services:
  transmission-openvpn_test:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-openvpn_test
    restart: always
    ports:
      - "9091:9091"
    environment:
      - Tz=Europe/London
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - NORDVPN_PROTOCOL=UDP
      - NORDVPN_CATEGORY=P2P
      - NORDVPN_COUNTRY=GB
      - TRANSMISSION_RPC_PORT=9091
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_DOWNLOAD_DIR=/media/downloads
      - TRANSMISSION_INCOMPLETE_DIR=/media/incomplete
      - TRANSMISSION_WATCH_DIR=/media/watch
      - CREATE_TUN_DEVICE=true
      - TRANSMISSION_WEB_UI=flood-for-transmission
    volumes:
      - /volume1/media/downloads:/media/downloads
      - /volume1/media/incomplete:/media/incomplete
      - /volume1/media/box:/media/watch
      - /volume1/docker/transmission-openvpn:/config
      - /volume1/docker/transmission-openvpn/resolv.conf:/etc/resolv.conf:ro

### Current Behavior

When generating the container as part of a stack the container will not access its bind-mounts on the host system and will instead get stuck in a DNS resolution failed loop.

I have tested this in a stack with other containers, all of whom launched correctly and had proper access to their bind-mounts apart from this one. I have also run the container through Portainer normally outside of a stack without any issues.

### Expected Behavior

For the container to launch in the same way as a non-stack container

### How have you tried to solve the problem?

I have tested this in a stack with other containers, all of whom launched correctly and had proper access to their bind-mounts apart from this one. I have also run the container through Portainer normally outside of a stack without any issues.

I've also removed all of my set ENV variables and used only the ones set out as required in the documentation.

### Log output

Starting container with revision: 1103172c3288b7de681e2fb7f1378314f17f66cf
TRANSMISSION_HOME is currently set to: /config/transmission-home
WARNING: initial DNS resolution test failed
Creating TUN device /dev/net/tun
Using OpenVPN provider: NORDVPN
Running with VPN_CONFIG_SOURCE auto
Provider NORDVPN has a bundled setup script. Defaulting to internal config
Executing setup script for NORDVPN
/etc/openvpn/nordvpn/..
Starting container with revision: 1103172c3288b7de681e2fb7f1378314f17f66cf
TRANSMISSION_HOME is currently set to: /config/transmission-home

### HW/SW Environment

```markdown
- OS: Synology NAS (DSM 7.1.1-42962 Update 5)
- Docker: Docker version 20.10.3, build 55f0773
```

**Comment by hobbes444** [comment] 2023-05-06 20:01
I have the same symptoms and I'm using a stack (in portainer) as well, also on DSM 7.1.1-42962 Update 5. It used to work a month ago I would say.

I do not see the above error in the container logs I can get in portainer though, but Transmission is unable to find any data from previously downloaded torrents, so it sounds very similar.

**Comment by pkishino** [comment] 2023-05-07 05:48
I use several transmission containers in stacks through portioner, but NOT on DSM and without any issues..

**Comment by hobbes444** [comment] 2023-05-07 07:36
Seeing DSM 7.1.1-42962 Update 5 was released end of april, maybe it is the culprit. The strange thing is, it only affects this container. I have influxdb and it's working fine.

**Comment by hobbes444** [comment] 2023-05-10 16:35
So it's very weird in my case.

It can see the torrents, but it cannot access the data somehow. Also I do not have any errors in the container log.

```
2023-05-10T16:31:01.153985595Z Starting container with revision: 1103172c3288b7de681e2fb7f1378314f17f66cf
2023-05-10T16:31:01.154042002Z TRANSMISSION_HOME is currently set to: /config/transmission-home
2023-05-10T16:31:01.154171813Z WARNING: Deprecated. Found old default transmission-home folder at /data/transmission-home, setting this as TRANSMISSION_HOME. This might break in future versions.
2023-05-10T16:31:01.154205313Z We will fallback to this directory as long as the folder exists. Please consider moving it to /config/transmission-home
2023-05-10T16:31:01.156466465Z One or more OVERRIDE_DNS addresses found. Will use them to overwrite /etc/resolv.conf
2023-05-10T16:31:01.374286699Z Creating TUN device /dev/net/tun
2023-05-10T16:31:01.382250437Z Using OpenVPN provider: PROTONVPN
2023-05-10T16:31:01.382409457Z Running with VPN_CONFIG_SOURCE auto
2023-05-10T16:31:01.382532301Z No bundled config script found for PROTONVPN. Defaulting to external config
2023-05-10T16:31:01.389471953Z Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.Bd162LyE48
2023-05-10T16:31:10.325356721Z Extracting configs to /tmp/tmp.Bijt74IMOX
2023-05-10T16:31:11.701531570Z Found configs for PROTONVPN in /tmp/tmp.Bijt74IMOX/vpn-configs-contrib-main/openvpn/protonvpn, will replace current content in /etc/openvpn/protonvpn
2023-05-10T16:31:11.707000840Z Cleanup: deleting /tmp/tmp.Bd162LyE48 and /tmp/tmp.Bijt74IMOX
2023-05-10T16:31:12.155309979Z Starting OpenVPN using config cz.protonvpn.net.udp.ovpn
2023-05-10T16:31:12.159936583Z Modifying /etc/openvpn/protonvpn/cz.protonvpn.net.udp.ovpn for best behaviour in this container
2023-05-10T16:31:12.160066136Z Modification: Point auth-user-pass option to the username/password file
2023-05-10T16:31:12.162853210Z Modification: Change ca certificate path
2023-05-10T16:31:12.166690200Z Modification: Change ping options
2023-05-10T16:31:12.198179418Z Modification: Update/set resolv-retry to 15 seconds
2023-05-10T16:31:12.203335052Z Modification: Change tls-crypt keyfile path
2023-05-10T16:31:12.207422413Z Modification: Set output verbosity to 3
2023-05-10T16:31:12.225517196Z Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
2023-05-10T16:31:12.242623713Z Modification: Updating status for config failure detection
2023-05-10T16:31:12.251790108Z Found existing OPENVPN credentials at /config/openvpn-credentials.txt
2023-05-10T16:31:12.320878043Z adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0
2023-05-10T16:31:12.328220272Z 2023-05-10 16:31:12 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
2023-05-10T16:31:12.331054765Z 2023-05-10 16:31:12 WARNING: file '/config/openvpn-credentials.txt' is group or others accessible
2023-05-10T16:31:12.331071704Z 2023-05-10 16:31:12 OpenVPN 2.5.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 14 2022
2023-05-10T16:31:12.331087207Z 2023-05-10 16:31:12 library versions: OpenSSL 3.0.2 15 Mar 2022, LZO 2.10
2023-05-10T16:31:12.332831195Z 2023-05-10 16:31:12 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2023-05-10T16:31:12.335694468Z 2023-05-10 16:31:12 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
2023-05-10T16:31:12.335710405Z 2023-05-10 16:31:12 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
2023-05-10T16:31:12.335947899Z 2023-05-10 16:31:12 TCP/UDP: Preserving recently used remote address: [AF_INET]217.138.220.194:5060
2023-05-10T16:31:12.335974609Z 2023-05-10 16:31:12 Socket Buffers: R=[212992->212992] S=[212992->212992]
2023-05-10T16:31:12.335987424Z 2023-05-10 16:31:12 UDP link local: (not bound)
2023-05-10T16:31:12.336032862Z 2023-05-10 16:31:12 UDP link remote: [AF_INET]217.138.220.194:5060
2023-05-10T16:31:12.378535073Z 2023-05-10 16:31:12 TLS: Initial packet from [AF_INET]217.138.220.194:5060, sid=52ea3935 db2553cb
2023-05-10T16:31:12.591855503Z 2023-05-10 16:31:12 VERIFY OK: depth=2, C=CH, O=ProtonVPN AG, CN=ProtonVPN Root CA
2023-05-10T16:31:12.592402772Z 2023-05-10 16:31:12 VERIFY OK: depth=1, C=CH, O=ProtonVPN AG, CN=ProtonVPN Intermediate CA 1
2023-05-10T16:31:12.592970551Z 2023-05-10 16:31:12 VERIFY KU OK
2023-05-10T16:31:12.592994503Z 2023-05-10 16:31:12 Validating certificate extended key usage
2023-05-10T16:31:12.593065891Z 2023-05-10 16:31:12 ++ Certificate has EKU (str) 1.3.6.1.5.5.8.2.2, expects TLS Web Server Authentication
2023-05-10T16:31:12.593079901Z 2023-05-10 16:31:12 ++ Certificate has EKU (oid) 1.3.6.1.5.5.8.2.2, expects TLS Web Server Authentication
2023-05-10T16:31:12.593089953Z 2023-05-10 16:31:12 ++ Certificate has EKU (str) TLS Web Client Authentication, expects TLS Web Server Authentication
2023-05-10T16:31:12.593099895Z 2023-05-10 16:31:12 ++ Certificate has EKU (oid) 1.3.6.1.5.5.7.3.2, expects TLS Web Server Authentication
2023-05-10T16:31:12.593109756Z 2023-05-10 16:31:12 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2023-05-10T16:31:12.593124901Z 2023-05-10 16:31:12 VERIFY EKU OK
2023-05-10T16:31:12.593134858Z 2023-05-10 16:31:12 VERIFY OK: depth=0, CN=node-cz-03.protonvpn.net
2023-05-10T16:31:12.651957835Z 2023-05-10 16:31:12 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1633', remote='link-mtu 1634'
2023-05-10T16:31:12.652013734Z 2023-05-10 16:31:12 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
2023-05-10T16:31:12.652093723Z 2023-05-10 16:31:12 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 4096 bit RSA, signature: RSA-SHA256
2023-05-10T16:31:12.652120794Z 2023-05-10 16:31:12 [node-cz-03.protonvpn.net] Peer Connection Initiated with [AF_INET]217.138.220.194:5060
2023-05-10T16:31:13.669877451Z 2023-05-10 16:31:13 SENT CONTROL [node-cz-03.protonvpn.net]: 'PUSH_REQUEST' (status=1)
2023-05-10T16:31:13.669938150Z 2023-05-10 16:31:13 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.28.0.1,sndbuf 524288,rcvbuf 524288,redirect-gateway def1,explicit-exit-notify,comp-lzo no,route-gateway 10.28.0.1,topology subnet,ping 10,ping-restart 60,socket-flags TCP_NODELAY,ifconfig 10.28.0.4 255.255.0.0,peer-id 786434,cipher AES-256-GCM'
2023-05-10T16:31:13.670055419Z 2023-05-10 16:31:13 OPTIONS IMPORT: timers and/or timeouts modified
2023-05-10T16:31:13.670114166Z 2023-05-10 16:31:13 OPTIONS IMPORT: explicit notify parm(s) modified
2023-05-10T16:31:13.670141911Z 2023-05-10 16:31:13 OPTIONS IMPORT: compression parms modified
2023-05-10T16:31:13.670196450Z 2023-05-10 16:31:13 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
2023-05-10T16:31:13.670273776Z 2023-05-10 16:31:13 Socket Buffers: R=[212992->425984] S=[212992->425984]
2023-05-10T16:31:13.670337132Z 2023-05-10 16:31:13 OPTIONS IMPORT: --socket-flags option modified
2023-05-10T16:31:13.670360319Z 2023-05-10 16:31:13 NOTE: setsockopt TCP_NODELAY=1 failed
2023-05-10T16:31:13.670423181Z 2023-05-10 16:31:13 OPTIONS IMPORT: --ifconfig/up options modified
2023-05-10T16:31:13.670499228Z 2023-05-10 16:31:13 OPTIONS IMPORT: route options modified
2023-05-10T16:31:13.670513016Z 2023-05-10 16:31:13 OPTIONS IMPORT: route-related options modified
2023-05-10T16:31:13.670523267Z 2023-05-10 16:31:13 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
2023-05-10T16:31:13.670533183Z 2023-05-10 16:31:13 OPTIONS IMPORT: peer-id set
2023-05-10T16:31:13.670611928Z 2023-05-10 16:31:13 OPTIONS IMPORT: adjusting link_mtu to 1656
2023-05-10T16:31:13.670626763Z 2023-05-10 16:31:13 OPTIONS IMPORT: data channel crypto options modified
2023-05-10T16:31:13.670636613Z 2023-05-10 16:31:13 Data Channel: using negotiated cipher 'AES-256-GCM'
2023-05-10T16:31:13.670800370Z 2023-05-10 16:31:13 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
2023-05-10T16:31:13.670867143Z 2023-05-10 16:31:13 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
2023-05-10T16:31:13.670881116Z 2023-05-10 16:31:13 net_route_v4_best_gw query: dst 0.0.0.0
2023-05-10T16:31:13.671061353Z 2023-05-10 16:31:13 net_route_v4_best_gw result: via 172.18.0.1 dev eth0
2023-05-10T16:31:13.671130885Z 2023-05-10 16:31:13 ROUTE_GATEWAY 172.18.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:12:00:05
2023-05-10T16:31:13.671456760Z 2023-05-10 16:31:13 TUN/TAP device tun0 opened
2023-05-10T16:31:13.671493809Z 2023-05-10 16:31:13 net_iface_mtu_set: mtu 1500 for tun0
2023-05-10T16:31:13.671567248Z 2023-05-10 16:31:13 net_iface_up: set tun0 up
2023-05-10T16:31:13.671716448Z 2023-05-10 16:31:13 net_addr_v4_add: 10.28.0.4/16 dev tun0
2023-05-10T16:31:13.671896578Z 2023-05-10 16:31:13 net_route_v4_add: 217.138.220.194/32 via 172.18.0.1 dev [NULL] table 0 metric -1
2023-05-10T16:31:13.671965361Z 2023-05-10 16:31:13 net_route_v4_add: 0.0.0.0/1 via 10.28.0.1 dev [NULL] table 0 metric -1
2023-05-10T16:31:13.671980330Z 2023-05-10 16:31:13 net_route_v4_add: 128.0.0.0/1 via 10.28.0.1 dev [NULL] table 0 metric -1
2023-05-10T16:31:13.706737274Z Up script executed with device=tun0 ifconfig_local=10.28.0.4
2023-05-10T16:31:13.706905282Z Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.28.0.4
2023-05-10T16:31:13.716361117Z 
2023-05-10T16:31:13.716501406Z -------------------------------------
2023-05-10T16:31:13.716514059Z Transmission will run as
2023-05-10T16:31:13.716524154Z -------------------------------------
2023-05-10T16:31:13.716533546Z User name:   root
2023-05-10T16:31:13.716542904Z User uid:    0
2023-05-10T16:31:13.716552231Z User gid:    0
2023-05-10T16:31:13.716561587Z -------------------------------------
2023-05-10T16:31:13.716571160Z 
2023-05-10T16:31:13.716588092Z Updating Transmission settings.json with values from env variables
2023-05-10T16:31:13.779835456Z Attempting to use existing settings.json for Transmission
2023-05-10T16:31:13.779892284Z Successfully used existing settings.json /data/transmission-home/settings.json
2023-05-10T16:31:13.779904317Z Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.28.0.4
2023-05-10T16:31:13.779914533Z Overriding blocklist-url because TRANSMISSION_BLOCKLIST_URL is set to http://list.iblocklist.com/?list=xxx&fileformat=p2p&archiveformat=gz&username=xxx&pin=xxx
2023-05-10T16:31:13.779925869Z Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
2023-05-10T16:31:13.779935905Z Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
2023-05-10T16:31:13.779945861Z Overriding ratio-limit because TRANSMISSION_RATIO_LIMIT is set to 2
2023-05-10T16:31:13.779955867Z Overriding ratio-limit-enabled because TRANSMISSION_RATIO_LIMIT_ENABLED is set to true
2023-05-10T16:31:13.779966815Z Overriding rpc-authentication-required because TRANSMISSION_RPC_AUTHENTICATION_REQUIRED is set to true
2023-05-10T16:31:13.779976827Z Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
2023-05-10T16:31:13.779986643Z Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
2023-05-10T16:31:13.779996444Z Overriding rpc-username because TRANSMISSION_RPC_USERNAME is set to xxx
2023-05-10T16:31:13.780006266Z Overriding speed-limit-up because TRANSMISSION_SPEED_LIMIT_UP is set to 200
2023-05-10T16:31:13.780016704Z Overriding speed-limit-up-enabled because TRANSMISSION_SPEED_LIMIT_UP_ENABLED is set to true
2023-05-10T16:31:13.780026876Z Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
2023-05-10T16:31:13.790312669Z sed'ing True to true
2023-05-10T16:31:13.793523754Z STARTING TRANSMISSION
2023-05-10T16:31:13.793813343Z Transmission startup script complete.
2023-05-10T16:31:13.798254709Z 2023-05-10 16:31:13 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
2023-05-10T16:31:13.798322068Z 2023-05-10 16:31:13 Initialization Sequence Completed
```

Docker Compose:

```
version: '3.8'
services:
  transmission-openvpn:
    container_name: 'haugene'
    cap_add:
      - NET_ADMIN
    devices:
      - '/dev/net/tun'
    volumes:
      - /volume1/data/:/data
      - /volume1/docker/haugene/resolv.conf:/etc/resolv.conf
      - /volume1/docker/haugene/:/config
    environment:
      - OPENVPN_PROVIDER=PROTONVPN
      - OPENVPN_CONFIG=cz.protonvpn.net.udp
      - OPENVPN_USERNAME=**None**
      - OPENVPN_PASSWORD=**None**
      - LOCAL_NETWORK=192.168.1.0/24
      - OVERRIDE_DNS_1=9.9.9.9
      - OVERRIDE_DNS_2=149.112.112.112
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_RATIO_LIMIT=2
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=200
      - TRANSMISSION_BLOCKLIST_URL=http://list.iblocklist.com/?list=xxx&fileformat=p2p&archiveformat=gz&username=xxx&pin=xxx
      - TRANSMISSION_RPC_USERNAME=xxx
      - TRANSMISSION_RPC_PASSWORD=xxx
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
    logging:
      driver: json-file
      options:
        max-size: 10m
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - '9091:9091'
    image: haugene/transmission-openvpn:latest

networks:
  default:
    external:
      name: mybridge
```

I can see all torrents listed, they are just all greyed out and complain they cannot find the data. It seems the issue is specific to the /data folder in my case, which I don't understand. Why would the other folders be mapped correctly and only this one not?

If I try to add a new torrent, it will be listed in the web GUI, but it will greyed out and show "permission denied (13)".

Is there any logs I can pull that would help here?

**Comment by hobbes444** [comment] 2023-05-11 05:53
issue is related to this specific folder on DSM. I moved to another, it works fine. I don't know what the root cause is yet, but it might be related to DSM encryption.

In summary, in my case it's definitely not an issue with the container.

**Comment by pkishino** [comment] 2023-05-11 09:28
Hello, thanks for the update, feel free to post the eventual solution if you find one.
I’ll close this for now

**Closed by pkishino** 2023-05-11 09:28 UTC
