### ISSUE TITLE
Docker Restarting (Possibly a QNAP Bug)

### ISSUE THREAD

**Issue by kylecribbs** [haugene/docker-transmission-openvpn#564] opened 2018-07-21 23:10 UTC
Is this container suppose to restart every 30 seconds? Not sure why it would, but as the container is up i can curl ifconfig.co and get a different IP than mine. Here is my docker compose let me know if you see anything wrong?

```
  transmission-pia:
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    logging:
      driver: json-file
      options: 
        max-size: "10m"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /share/Container/transmission/data:/data
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=CA Toronto,CA Montreal,CA Vancouver
      - OPENVPN_USERNAME=x
      - OPENVPN_PASSWORD=x
      - WEBPROXY_ENABLED=true
      - LOCAL_NETWORK=192.168.168.0/24
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping
```

Right after port is open: yes, it restarts 
```
STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Wait for tunnel to be fully initialized and PIA is ready to give us a port
STARTING TINYPROXY
Setting tinyproxy port to 8888
Starting tinyproxy: tinyproxy.
Tinyproxy startup script complete.
Sat Jul 21 23:24:35 2018 Initialization Sequence Completed
Got new port 29309 from PIA
transmission auth not required
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Port is open: Yes
```

**Comment by coolboiime** [comment] 2018-07-24 03:09
The `LOCAL_NETWORK` variable looks a little off to me. Can you confirm that's your DHCP?

**Comment by kylecribbs** [comment] 2018-07-24 03:13
Yeah thats right I created that subnet. I kind of found the reason. When i run this docker-compose on my mac, it works with no issues.. I think it has to do with my QNAP NAS. There is probably some setting that isn't namespaced that the container is erroring out from.

**Comment by coolboiime** [comment] 2018-07-24 03:14
Could it be your OpenVPN config? There are spaces not wrapped around quotes.

**Comment by kylecribbs** [comment] 2018-07-24 03:18
I dont think so.. Like I said the same docker-compose worked on my mac. I was reading somewhere that it you had to have qvpn installed on the qnap.. idk.. lol

**Comment by coolboiime** [comment] 2018-07-24 03:20
Wish I could help more, I use Synology at the moment.

**Comment by kylecribbs** [comment] 2018-07-24 03:20
I appreciate it brother!

**Comment by mariusasirum** [comment] 2018-07-31 13:10
I've got the same issue.

I used the following: 

 docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d \
              -v /your/storage/path/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e OPENVPN_PROVIDER=PIA \
              -e OPENVPN_CONFIG=CA\ Toronto \
              -e OPENVPN_USERNAME=x \
              -e OPENVPN_PASSWORD=x \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=192.168.80.0/24 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn

**Comment by mariusasirum** [comment] 2018-08-01 06:49
I had the same issue with my QNAP. After I updated it to the latest version it started working properly.

I have a TS-253A running V 4.3.4.0644

**Comment by coolboiime** [comment] 2018-08-03 14:22
@kylecribbs Have you tried updating your QNAP? Seems like the issue is resolved by @mariusasirum! Closing for now until there are more issues arising! Thanks!

**Closed by coolboiime** 2018-08-03 14:22 UTC
Labels: help wanted
