### ISSUE TITLE
Restart loop: Error opening configuration file: /etc/openvpn/nordvpn/default.ovpn

### ISSUE THREAD

**Issue by Bidley** [haugene/docker-transmission-openvpn#1192] opened 2020-05-19 23:37 UTC
I'm running OMV5 with Portainer, and the transmission container is suddenly in a restart loop and unable to open the config file. This has been running fine for months - latest version of the image.

Logs: https://pastebin.com/8gXNNtMJ

Portainer config: https://pastebin.com/ehZQfCcV

**Comment by SaltyPaws** [comment] 2020-05-20 02:27
This is a duplicate of issue #1173

**Comment by Bidley** [comment] 2020-05-20 10:51
Closed because of duplicity.

**Closed** 2020-05-20 10:51 UTC
