### ISSUE TITLE
Synology 918+ and V3 not working V2.14 OK

### ISSUE THREAD

**Issue by juliemars** [haugene/docker-transmission-openvpn#1496] opened 2020-11-11 10:43 UTC
**Describe the problem**
Hi I pulled the latest image on my Synology 918+ and it will no longer start fully. The logs are not telling me much looking at the issues page I have tried removing the OPENVPN_CONFIG and LOCAL_NETWORK from the environment variable without success.

I have left it running for 60 minutes and it never starts, if I check the processes I can see it going through downloads:
![image](https://user-images.githubusercontent.com/17718528/98800002-bd0c4100-2407-11eb-9d8b-f2333c64f7c3.png)

but the same ones keep showing if I roll back to 2.14 it works fine for me. 

I don't use torrents that often maybe a couple of times a year so the container isn't running 24/7 normally

**Add your docker run command**

![image](https://user-images.githubusercontent.com/17718528/98801618-f47bed00-2409-11eb-8998-00a62e0ad751.png)

I have followed comments on this page and removed all the transmission options without success.

**Logs**
Starting container with revision: 05f657435af4ca118b8cdf6a03f5ce895149cbc8
mknod: /dev/net/tun: File exists
Using OpenVPN provider: IPVANISH
Provider ipvanish has a custom startup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.MPNHLI
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
Modify configs for this container

**Host system:**

Synology Docker Standalone 18.09.8

**Comment by resuarez** [comment] 2020-11-11 12:07
I have the same problem today, but running in UnRaid.  I cannot connect, but changing the repo haugene/transmission-openvpn:2.14, everything starts to work.

I've tried to get any log, but I just get the same already reported.

**Comment by haugene** [comment] 2020-11-11 20:04
Oh yeah. Had the same for PIA. I think I know what the problem is. Just a sec.

**Comment by haugene** [comment] 2020-11-11 21:24
Allright. Pushed an update to dev now. Try pulling and running the `dev` tag of the image? :crossed_fingers:

**Comment by juliemars** [comment] 2020-11-12 07:59
@haugene great thanks - just pulled dev and the container started fine! I will leave it on Dev for now until it hits latest, thanks for the quick fix.

**Comment by razer86** [comment] 2020-11-21 22:08
I was having the same issues on unRaid using any v3 build until I removed the LocalNetwork variable from the run command.

**Comment by haugene** [comment] 2020-12-10 00:00
This fix is merged to master now and I'll close this for now. Re-open if you've had or still having any issues @juliemars

**Closed by haugene** 2020-12-10 00:00 UTC
