### ISSUE TITLE
Running speedtest-cli within the container?

### ISSUE THREAD

**Issue by Celoxocis** [haugene/docker-transmission-openvpn#702] opened 2019-02-09 12:10 UTC
this might not be an container issue at all.
somehow I'm unable to run the speedtest-cli within the container.

this is as far as i get:

```
docker cp speedtest.py transmission-openvpn:/root/speedtest.py
docker exec -it transmission-openvpn /bin/bash

root@60fe1fd573fd:~# ./speedtest.py
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: <urlopen error ('_ssl.c:574: The handshake operation timed out',)>

```

running latest release. i have UFW disabled and DNS is properly setup.
transmission and the tunnel itself work fine.
am I missing something? =)

**Comment by haugene** [comment] 2019-02-09 16:41
Can't seem to reproduce this. Ran a fresh container, exec'ed in and ran:
```
wget -O speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
chmod +x speedtest-cli
./speedtest-cli
```

That worked fine for me in both the ubuntu and alpine image.

**Comment by Celoxocis** [comment] 2019-02-09 17:09
it is strange. it works on the host (ubuntu 16.04 LTS) but not in the container.

i tried downloading it in the container and it just hangs while connecting to github.
after i cancel it. the file is created but empty. just if you would run "touch speedtest-cli".
```
wget -O speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
--2019-02-09 17:58:30--  https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
```
this is how my setup looks like (left out the transmission configuration). i use systemd integration.

```
[Unit]
Description=haugene/transmission-openvpn docker container
After=docker.service
Requires=docker.service

[Service]
User=user
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill transmission-openvpn
ExecStartPre=-/usr/bin/docker rm transmission-openvpn
ExecStartPre=/usr/bin/docker pull haugene/transmission-openvpn:dev
ExecStart=/usr/bin/docker run \
        --name transmission-openvpn \
        --cap-add=NET_ADMIN \
        --device=/dev/net/tun \
        -v /mnt/Downloads/Torrents:/data \
        -v /etc/localtime:/etc/localtime:ro \
        -e "OPENVPN_PROVIDER=PIA" \
        -e "OPENVPN_CONFIG=SERVER" \
        -e "OPENVPN_USERNAME=XXXXXXXX" \
        -e "OPENVPN_PASSWORD=YYYYYYYY" \
        -e "LOCAL_NETWORK=192.168.X.Y/24" \
        -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings" \
        -e "TRANSMISSION_RPC_HOST_WHITELIST=127.0.0.1" \
        -e "TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=true" \
        -e "ENABLE_UFW=false" \
        -e "GLOBAL_APPLY_PERMISSIONS=false" \
        -p 9091:9091 \
        --dns 8.8.8.8 \
        --dns 8.8.4.4 \
        -e "PGID=1005" \
        -e "PUID=1000" \
        haugene/transmission-openvpn:dev
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```
nothing out of the ordinary that would break a simply wget download or running the script.

**Comment by haugene** [comment] 2019-02-09 18:00
Not seeing anything that should break a simple wget here either. You could try to debug a couple of options. First one being if it works in a regular ubuntu container, it could be docker daemon or networking issues maybe. Then, if that works you could try in the transmission-openvpn image withouth the vpn. Just override cmd and exec in like `docker run --rm -it haugene/transmission-openvpn bash`. I assume they will both work fine, but then at least we know it has to do with VPN. Maybe run it without LOCAL_NETWORK option, not sure. But need to narrow it down.

**Comment by h45rd** [comment] 2019-02-10 09:04
Maybe a certificate / SSL issue?
Do non-https wget downloads work?
What's the output of the following command (within the container)?
`openssl s_client -connect speedtest.net:443`

**Comment by Celoxocis** [comment] 2019-02-11 13:33
when i run h45rd's test i get:
```
root@60fe1fd573fd:/# openssl s_client -connect speedtest.net:443
CONNECTED(00000003)
```
i will run some debugging when i get home.

**Comment by Celoxocis** [comment] 2019-02-11 14:47
**Some debug results with fresh image**

> First one being if it works in a regular ubuntu container, it could be docker daemon or networking issues maybe.

**Result:** It works in a regular ubuntu container. I doubt its a docker daemon issue. Other containers don't have any issues. My version is:
```
~$ docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

> Then, if that works you could try in the transmission-openvpn image withouth the vpn. Just override cmd and exec in like `docker run --rm -it haugene/transmission-openvpn bash.
> I assume they will both work fine, but then at least we know it has to do with VPN.

**Result:** Works fine and can run wget and speedtest-cli without any issues.

> Maybe run it without LOCAL_NETWORK option, not sure. But need to narrow it down.

**Not yet tested**: Will test tonight after work.

**Comment by h45rd** [comment] 2019-02-11 17:05
Would need the full output of the command in order to analyze what's going on with the SSL handshake when the VPN is active.
The last line should be:
`Verify return code: 0 (ok)`

**Comment by Celoxocis** [comment] 2019-02-13 08:54
this is the full output of the ssl test command:
```
user@host:~$ docker exec -it transmission-openvpn /bin/bash
root@b0b0a864a45d:/# openssl s_client -connect speedtest.net:443
CONNECTED(00000003)
```
i just run it in the host and it's way more output. in the container the output doesn't get past the "CONNECTED(00000003)" line.

**Comment by h45rd** [comment] 2019-02-13 09:09
Ah, okay.
So there is no (complete) handshake taking place.
Maye your VPN provider is filtering encrypted traffic?

Try upping verbosity in order to see what's going on:
`openssl s_client -debug -msg -security_debug_verbose -connect speedtest.net:443`

**Comment by Celoxocis** [comment] 2019-02-16 11:26
i don't seem to have "_-security_debug_verbose_" so i run it without:
```
root@0dd3b1cc065a:/# openssl s_client -debug -msg -connect speedtest.net:443
CONNECTED(00000003)
write to 0x116b110 [0x116b190] (305 bytes => 305 (0x131))
0000 - 16 03 01 01 2c 01 00 01-28 03 03 8e b0 50 b2 6b   ....,...(....P.k
0010 - 55 27 a3 a0 f8 91 6e a4-b9 5c a4 ca 87 0d 3c 34   U'....n..\....<4
0020 - d8 b4 23 9d 6c db 59 cb-32 86 fc 00 00 aa c0 30   ..#.l.Y.2......0
0030 - c0 2c c0 28 c0 24 c0 14-c0 0a 00 a5 00 a3 00 a1   .,.(.$..........
0040 - 00 9f 00 6b 00 6a 00 69-00 68 00 39 00 38 00 37   ...k.j.i.h.9.8.7
0050 - 00 36 00 88 00 87 00 86-00 85 c0 32 c0 2e c0 2a   .6.........2...*
0060 - c0 26 c0 0f c0 05 00 9d-00 3d 00 35 00 84 c0 2f   .&.......=.5.../
0070 - c0 2b c0 27 c0 23 c0 13-c0 09 00 a4 00 a2 00 a0   .+.'.#..........
0080 - 00 9e 00 67 00 40 00 3f-00 3e 00 33 00 32 00 31   ...g.@.?.>.3.2.1
0090 - 00 30 00 9a 00 99 00 98-00 97 00 45 00 44 00 43   .0.........E.D.C
00a0 - 00 42 c0 31 c0 2d c0 29-c0 25 c0 0e c0 04 00 9c   .B.1.-.).%......
00b0 - 00 3c 00 2f 00 96 00 41-c0 11 c0 07 c0 0c c0 02   .<./...A........
00c0 - 00 05 00 04 c0 12 c0 08-00 16 00 13 00 10 00 0d   ................
00d0 - c0 0d c0 03 00 0a 00 ff-01 00 00 55 00 0b 00 04   ...........U....
00e0 - 03 00 01 02 00 0a 00 1c-00 1a 00 17 00 19 00 1c   ................
00f0 - 00 1b 00 18 00 1a 00 16-00 0e 00 0d 00 0b 00 0c   ................
0100 - 00 09 00 0a 00 23 00 00-00 0d 00 20 00 1e 06 01   .....#..... ....
0110 - 06 02 06 03 05 01 05 02-05 03 04 01 04 02 04 03   ................
0120 - 03 01 03 02 03 03 02 01-02 02 02 03 00 0f 00 01   ................
0130 - 01                                                .
>>> TLS 1.2  [length 0005]
    16 03 01 01 2c
>>> TLS 1.2 Handshake [length 012c], ClientHello
    01 00 01 28 03 03 8e b0 50 b2 6b 55 27 a3 a0 f8
    91 6e a4 b9 5c a4 ca 87 0d 3c 34 d8 b4 23 9d 6c
    db 59 cb 32 86 fc 00 00 aa c0 30 c0 2c c0 28 c0
    24 c0 14 c0 0a 00 a5 00 a3 00 a1 00 9f 00 6b 00
    6a 00 69 00 68 00 39 00 38 00 37 00 36 00 88 00
    87 00 86 00 85 c0 32 c0 2e c0 2a c0 26 c0 0f c0
    05 00 9d 00 3d 00 35 00 84 c0 2f c0 2b c0 27 c0
    23 c0 13 c0 09 00 a4 00 a2 00 a0 00 9e 00 67 00
    40 00 3f 00 3e 00 33 00 32 00 31 00 30 00 9a 00
    99 00 98 00 97 00 45 00 44 00 43 00 42 c0 31 c0
    2d c0 29 c0 25 c0 0e c0 04 00 9c 00 3c 00 2f 00
    96 00 41 c0 11 c0 07 c0 0c c0 02 00 05 00 04 c0
    12 c0 08 00 16 00 13 00 10 00 0d c0 0d c0 03 00
    0a 00 ff 01 00 00 55 00 0b 00 04 03 00 01 02 00
    0a 00 1c 00 1a 00 17 00 19 00 1c 00 1b 00 18 00
    1a 00 16 00 0e 00 0d 00 0b 00 0c 00 09 00 0a 00
    23 00 00 00 0d 00 20 00 1e 06 01 06 02 06 03 05
    01 05 02 05 03 04 01 04 02 04 03 03 01 03 02 03
    03 02 01 02 02 02 03 00 0f 00 01 01


```
I'm not aware that PIA filters encrypted traffic?
Pinging speedtest.net works fine.

**Comment by h45rd** [comment] 2019-02-16 18:43
Hmm.. this is very strange indeed.
You never hear back from the server after your ClientHello.
But why? I have no idea. So let's go fishing :)

Maybe it is the other way around and speedtest.net filters encrypted traffic from certain sources?
Do you get a complete handshake from within the container when trying another server? E.g. google.com:443

Does an SSL enabled curl on speedtest.net work from within the container?

Does speedtest-cli work if you run it through the VPN but outside of the container? E.g. via the webproxy or by using the network stack of the connected VPN docker on another container.

**Comment by Celoxocis** [comment] 2019-02-17 12:38
just tested with google.com:443 and with the same result.

> Does an SSL enabled curl on speedtest.net work from within the container?

How do i run such a test?

> Does speedtest-cli work if you run it through the VPN but outside of the container? E.g. via the webproxy or by using the network stack of the connected VPN docker on another container.

Speedtest-cli works without the container through PIA VPN.
Not sure what you mean by "_by using the network stack of the connected VPN docker on another container._"

**Comment by h45rd** [comment] 2019-02-18 17:20
>How do i run such a test?

`curl -v https://speedtest.net`
See `man curl` for further options.

>Not sure what you mean by "_by using the network stack of the connected VPN docker on another container._"

See **--network=container:** in [docker run reference](https://docs.docker.com/engine/reference/run/#network-settings)

**Comment by Celoxocis** [comment] 2019-02-26 13:42
got some time to continue this debugging.
when i run `curl -v https://speedtest.net`
i get:
```
root@3fe3f27ec511:/# curl -v https://speedtest.net
* Rebuilt URL to: https://speedtest.net/
*   Trying 151.101.194.219...
* Connected to speedtest.net (151.101.194.219) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1

```
it doesn't get past the last line which it should...

i tried running a simply ubuntu container via `--network=transmission-openvpn` which is the name of my container but it ends up entering the failed state.  also tried using the unique ID and including NET_ADMIN. all end up in the same result.

before i continue further debugging. i plan to dist-upgrade to 18.04 LTS in the next week or so. maybe the issue will solve itself after the upgrade.

the issue is really strange. it's only affecting the transmission-openvpn container.
when i run the speedtest script within any other container on the same bridged network. it just works.

is it possible that `-e "ENABLE_UFW=false" \` is being ignored somehow?

**Comment by h45rd** [comment] 2019-02-27 11:51
I tried to explain my thought process in brackets, so you can follow where this is going and don't have to blindly paste commands.

>it doesn't get past the last line which it should...

How far do you get when curling e.g. Google via SSL? [general SSL issue, or host-specific?]
When I re-read the thread I noticed that you did not reply to this question:
>Do non-https wget downloads work?

Alternatively just curl some URL that still offers plain HTTP. [SSL issue or HTTP issue?]
I also mentioned the webproxy before. Does regular surfing via the webproxy work?

>i tried running a simply ubuntu container via `--network=transmission-openvpn` which is the name of my container but it ends up entering the failed state.

The syntax is `--network=container:$containername`, so in your case `--network=container:transmission-openvpn` [general VPN issue?]

Are you always using the same PIA server/location? [server-specific VPN issue?]

>before i continue further debugging. i plan to dist-upgrade to 18.04 LTS in the next week or so. maybe the issue will solve itself after the upgrade.

Would not bet on it. Don't think this is a host OS issue.

>is it possible that `-e "ENABLE_UFW=false" \` is being ignored somehow?

I don't see how UFW would play a role in any of this.

**Comment by haugene** [comment] 2019-03-09 20:40
Starting to think that this issue has run its course? Seems to be a local issue somehow seeing as none of us can reproduce it. Ok if we close this, @Celoxocis?

**Comment by Celoxocis** [comment] 2019-03-14 10:00
yeah it's fine with me. it's really weird but it doesn't affect the main usage of the container at all. to bad i wasn't able to narrow it down. i simply lack the time. thanks guys for your help. if i discover the cause of the issue one day i will let you know.

**Comment by haugene** [comment] 2019-03-14 10:20
Great, let us know if you do 😄

**Comment by Celoxocis** [comment] 2019-03-31 13:13
okay guys. i figured it out!

it was nothing wrong with the container itself. i was able to isolate the issue to the MTU size.
My provider uses RFC 8157 (GRE tunnel bonding) for bonding 4G and DSL line into one line.
I've noticed that while using PIA TCP connections it worked flawless but on UDP i had the above issue.

**The solution** for those running across this issue (or related) was to look into what MTU size my ISP uses.
Using: https://www.speedguide.net/analyzer.php
Look at the very top at "MTU = XXXX".

_The UDP header has a size of 8 bytes and the IPv4 header a size of 20 Bytes which together equals 28 bytes. So take the reported MTU size "XXXX" and subtract the 28 bytes. In my case 1440-28=1412. You now simply include that value into the OpenVPN config:_

`In short: MTU XXX - (UDP header 8 bytes + IP header 20 bytes) = Your "mssfix value"`
`-e "OPENVPN_OPTS=--mssfix 1412" `

Should you use a TCP connection. The calculation is slightly different.
The TCP header has a size of 20 bytes (it can go up to max 60 bytes), here again we add the 20 bytes IPv4 header, which together equals 40-60 byte.

`In short: MTU XXXS - (TCP header 20(optionally 40) byte + IP header 20 Byte) = Your "mssfix value"`

**Closed** 2019-03-31 13:14 UTC
