### ISSUE TITLE
Speeds very slow

### ISSUE THREAD

**Issue by merqwury** [haugene/docker-transmission-openvpn#188] opened 2017-01-18 21:51 UTC
While using the VPN without Docker, speeds are up to 4-5MB/s. However, running it through Docker, I'm only getting 100-200KBs MAX. Any ideas?

**Comment by merqwury** [comment] 2017-01-19 08:41
I've also tried testing speed via wget from the container and that seems awfully slow as well.

**Comment by pkishino** [comment] 2017-01-19 11:31
are you using same server? have you checked if same settings? port forwarding etc? 
Cause with my provider I get roughly same speeds inside and outside docker running same server and same settings

**Comment by merqwury** [comment] 2017-01-19 19:39
- Same Server
- Same Settings
- I've run torrent client outside of Docker with VPN ON and I get full speed
- I've run (another) torrent + vpn (delugevpn) Docker container with VPN OFF and I get full speed
- Running in Docker with VPN ON, I get the speeds noted above.

**Comment by cocokola** [comment] 2017-05-08 05:00
I have the same issue; did you come up with any solutions or ideas what to check?

**Comment by cocokola** [comment] 2017-05-10 22:33
I'm too new at all this to be much help, but I will say I am SO frustrated that I have everything seeming to be working but the slow throughput is making this unusable.  I've disabled everything that could be in the way, and all testing concludes it is "working" to pull files, but the slowness makes this unusable. Anyone with some know-how willing to work with me?

**Comment by cocokola** [comment] 2017-05-13 23:45
Is this container dead?

**Comment by jmandawg** [comment] 2017-06-20 03:25
Disable the firewall:

-e ENABLE_UFW=false

**Comment by Aivean** [comment] 2017-08-20 04:43
I'm having the same issue on Windows host only. Mac is fine.

I've tried doing the following test:

`wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip`

Results:

host | Image | speed
--- | --- | ---
Windows 10 | haugene/transmission-openvpn | ≈350 Kb/s
Windows 10 | ubuntu:14.04 | ≈3.5 Mb/s
Mac | haugene/transmission-openvpn | ≈3.5 Mb/s

Note: `ubuntu:14.04` is base image for `haugene/transmission-openvpn`.

Disabling firewall (`-e ENABLE_UFW=false`) as suggested above doesn't seem to help. 

As the issue is happening only on Windows host and is specific to `haugene/transmission-openvpn`, could it be related to the `/dev/net/tun` implementation on Windows?

**Comment by arontx** [comment] 2017-08-30 20:40
I'm having the same issue however running on Debian. Disabling the firewall did not help.

**Comment by haugene** [comment] 2018-03-16 10:43
Not sure what we'll do with this. If it's platform specific, than it's more of a Docker issue than this container. Closing this for now. Can follow up in #285 and see if we get anywhere.

**Closed by haugene** 2018-03-16 10:43 UTC
