### ISSUE TITLE
Windscribe: TLS handshake error

### ISSUE THREAD

**Issue by madnlooney** [haugene/docker-transmission-openvpn#1055] opened 2020-02-19 18:24 UTC
Pulled new image and I seem to get a TLS handshake error..
Using Windscribe static ip but not sure if anything has changed.  I tested config with openvpn away from docker which connects fine

`Using OpenVPN provider: CUSTOM
Starting OpenVPN using config config.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0
Wed Feb 19 18:22:46 2020 WARNING: file '/etc/openvpn/custom/auth.txt' is group or others accessible

Wed Feb 19 18:22:46 2020 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019

Wed Feb 19 18:22:46 2020 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08

Wed Feb 19 18:22:46 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts

Wed Feb 19 18:22:46 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication

Wed Feb 19 18:22:46 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication

Wed Feb 19 18:22:46 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]37.120.141.131:443

Wed Feb 19 18:22:46 2020 UDP link local: (not bound)

Wed Feb 19 18:22:46 2020 UDP link remote: [AF_INET]37.120.141.131:443

Wed Feb 19 18:23:46 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)

Wed Feb 19 18:23:46 2020 TLS Error: TLS handshake failed

Wed Feb 19 18:23:46 2020 SIGUSR1[soft,tls-error] received, process restarting

Wed Feb 19 18:23:51 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Feb 19 18:23:51 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]37.120.141.131:443
Wed Feb 19 18:23:51 2020 UDP link local: (not bound)
Wed Feb 19 18:23:51 2020 UDP link remote: [AF_INET]37.120.141.131:443
Wed Feb 19 18:24:51 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Feb 19 18:24:51 2020 TLS Error: TLS handshake failed
Wed Feb 19 18:24:51 2020 SIGUSR1[soft,tls-error] received, process restarting
Wed Feb 19 18:24:56 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Feb 19 18:24:56 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]37.120.141.131:443
Wed Feb 19 18:24:56 2020 UDP link local: (not bound)
Wed Feb 19 18:24:56 2020 UDP link remote: [AF_INET]37.120.141.131:443`

**Comment by haugene** [comment] 2020-03-29 14:16
So the issue is that Windscribe configs should be updated? Or that some key that works outside the container don't work inside the container?

Can you provide the config you're using here?

**Comment by haugene** [comment] 2020-03-29 14:20
Update. Just connected some dots now. From #1043 

> On Feb 19, the Newshosting VPN will be discontinued in favor of the new replacement, Privado. 

That's the same date as you posted here. I'm going to close this now under the assumption that they invalidated old config files and that you need to grab new configs from Privado to get it working again.

Please re-open if you have other issues.

**Comment by pkishino** [comment] 2020-05-29 00:43
please provide updated configs as a PR

**Closed by pkishino** 2020-05-29 00:43 UTC
Labels: inactivity

**Comment by Pandalism** [comment] 2021-05-22 00:56
I can provide configs if required, ran into the same TLS handshake issue.

**Comment by nibrwr** [comment] 2021-07-22 21:45
I uploaded a opvn config file from today, 7/22/21 (renamed to .txt for upload). Errors I'm getting in my Docker log:

VERIFY ERROR: depth=1, error=unable to get local issuer certificate: C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Systems, CN=Windscribe Node CA X2, serial=1

OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

TLS_ERROR: BIO read tls_read_plaintext error
TLS Error: TLS object -> incoming plaintext read error
TLS Error: TLS handshake failed

[Windscribe-Atlanta-Mountain.txt](https://github.com/haugene/docker-transmission-openvpn/files/6865368/Windscribe-Atlanta-Mountain.txt)
