### ISSUE TITLE
Very slow speeds (PIA)

### ISSUE THREAD

**Issue by Grygon** [haugene/docker-transmission-openvpn#285] opened 2017-08-04 19:05 UTC
Hi, I'm trying to set this up with PIA, but while I can get it to work I'm unable to get it above ~200kb/s which doesn't work for me. Here's an image of three tests I performed, the top left is with this container, the bottom left is with a different (non-VPN) container, and the right is through a VPN on the host system. 

![image](https://user-images.githubusercontent.com/647846/28983083-14823a60-7926-11e7-8967-eec0b32ba4db.png)

This is the command I'm using to setup the container:

docker run --cap-add=NET_ADMIN --device=/dev/net/tun --name=transmission -d -v '/r/Downloads:/data' -v /etc/localtime:/etc/localtime:ro -e "OPENVPN_PROVIDER=PIA" -e "OPENVPN_CONFIG=Netherlands" -e "OPENVPN_USERNAME=..." -e "OPENVPN_PASSWORD=..." -e "ENABLE_UFW=false" -e "LOCAL_NETWORK=192.168.0.0/24" -p 9091:9091 --dns=8.8.8.8 haugene/transmission-openvpn

Is there anything else I can try to improve speeds? Thanks.

**Comment by Aivean** [comment] 2017-08-20 08:17
It seems that this issue is specific to Windows host. Check also [this thread](https://github.com/haugene/docker-transmission-openvpn/issues/188#issuecomment-323563294).

**Comment by arontx** [comment] 2017-08-30 20:44
+1, same issue running on Debian

**Comment by benmooney92** [comment] 2017-09-05 14:19
Same issue here on Docker for windows.

**Comment by bduisenov** [comment] 2017-10-31 19:15
I have the same issue with 'docker for mac'

**Comment by haugene** [comment] 2018-04-08 19:53
Closing this as it's too general. Hopefully the issues are related to ports not being opened, and a fix that's been merged to master now tries to make this solution more stable.

If it's not a port opening issue then we need more information on how to reproduce it. I'm running the container with PIA at good speeds, and so are a lot of others. Give us the steps to reproduce it in a clean ubuntu vm or other environment.

If it's still an issue you're welcome to +1 this issue or report a new one with more specifics. But as it seems to be working for most users, I think this is a local problem and not an issue with the container.

**Closed by haugene** 2018-04-08 19:53 UTC

**Comment by moh-Brent** [comment] 2020-09-07 09:27
+1 same issue, LinuxMint, I have tried RPi, NUC (current) windows 10 all work at top speeds except when using Docker

**Comment by martdj** [comment] 2022-02-14 07:50
I can +1 this as well. CentOS 8 Stream, Podman. If I exec into this container and do a wget, I also get very slow speeds (just like when torrenting). I downloaded a 20MB file at 166 KB/s. Interestingly enough, it started out ok. Speed went up to 900 KB/s and then it dropped down to 20 KB/s to get to the 166 KB/s average.

**Comment by martdj** [comment] 2022-02-14 08:00
Found the problem. The magic was in the setting (in Transmission itself Network - Options - Enable uTP for peer communication. This setting was "On" and it should be "Off" for proper speed!
