### ISSUE TITLE
Wrong URLs created by dynamic script for NordVPN

### ISSUE THREAD

**Issue by anderssv** [haugene/docker-transmission-openvpn#1332] opened 2020-08-18 20:48 UTC
**Which provider?**
NordVPN

**Where are the configs?**
The dynamic script makes assumptions of URLs that doesn't work anymore.

Not working (from script): https://downloads.nordcdn.com/configs/filesse410.nordvpn.com
Working: https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/se410.nordvpn.com.tcp443.ovpn

**Comment by edgd1er** [comment] 2020-08-19 06:30
as per doc: https://haugene.github.io/docker-transmission-openvpn/nordvpn-script/, three env are needed, I guess NORDVPN_CATEGORY,NORDVPN_PROTOCOL are not defined or invalid in your container config.

**Comment by schwukas** [comment] 2020-08-19 08:48
I don't think those environment variables are _needed_ as they have defaults [here](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/start.sh#L32). I noticed problems with the script as well. For now, I'd guess some variables are ignored, but I'll dig a little deeper and verify my assumption.

**Comment by thundergreen** [comment] 2020-08-19 11:45
Hello I am using your HassIO addon and this is my config:

```
PUID: 1000
PGID: 1000
OPENVPN_PROVIDER: NORDVPN
OPENVPN_CONFIG: se449.nordvpn.com
OPENVPN_USERNAME: xxxxxxxxxxxxxxxx
OPENVPN_PASSWORD: 'xxxxxxxxxxx'
LOCAL_NETWORK: 192.168.0.0/16
WEBPROXY_ENABLED: 'false'
CREATE_TUN_DEVICE: 'true'
```

But i Get this error: 

```
Using OpenVPN provider: NORDVPN
Setting NORDVPN_PROTOCOL to: COM
2020-08-19 13:41:33 Checking curl installation
2020-08-19 13:41:33 Removing existing configs
2020-08-19 13:41:33 Selecting the best server...
2020-08-19 13:41:33 Searching for group: legacy_p2p
2020-08-19 13:41:33 Best server : fr537.nordvpn.com
2020-08-19 13:41:33 Downloading config: default.ovpn
2020-08-19 13:41:33 Downloading from: https://downloads.nordcdn.com/config-internals/filesfr537.nordvpn.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    252      0 --:--:-- --:--:-- --:--:--   252
100   162  100   162    0     0    252      0 --:--:-- --:--:-- --:--:--   252
2020-08-19 13:41:33 Using OpenVPN CONFIG :: se449.nordvpn.com
2020-08-19 13:41:33 Downloading config: se449.nordvpn.com.ovpn
2020-08-19 13:41:33 Downloading from: https://downloads.nordcdn.com/config-internals/filesse449.nordvpn.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    315      0 --:--:-- --:--:-- --:--:--   315
2020-08-19 13:41:33 Checking line endings
2020-08-19 13:41:33 Updating configs for docker-transmission-openvpn
Starting OpenVPN using config se449.nordvpn.com.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/16 via 172.30.32.1 dev eth0
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/se449.nordvpn.com.ovpn:1: html (2.4.8)
Use --help for more information.
```


I also run the docker image from haugene with this config and it works pretty well:

```
sudo docker run --cap-add=NET_ADMIN -d \
              -v /usr/share/hassio/share/Storage/USB2/Downloads:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true  \
              -e OPENVPN_PROVIDER=NORDVPN \
              -e OPENVPN_USERNAME=xxxxxxxxx \
              -e OPENVPN_PASSWORD=xxxxxxx \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=192.168.0.0/16 \
              -e TRANSMISSION_WEB_UI=kettu \
              -e NORDVPN_CATEGORY=legacy_p2p \
              -e NORDVPN_COUNTRY=SE \
              -e PUID=1000 \
              -e PGID=1000 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn

```

any idea what's going wrong here?

**Comment by edgd1er** [comment] 2020-08-19 12:36
@thundergreen

Well, COM is not a valid NORDVPN_PROTOCOL: tcp or udp is expected.
as not written in docs ;) , OPENVPN_CONFIG must be empty as it interfere in scripts: https://github.com/haugene/docker-transmission-openvpn/issues/1145#issuecomment-615550966

**Comment by thundergreen** [comment] 2020-08-19 14:04
Still same issue with config: 

```
PUID: 1000
PGID: 1000
OPENVPN_PROVIDER: NORDVPN
OPENVPN_CONFIG: ''
OPENVPN_USERNAME: xxxxxxxxx
OPENVPN_PASSWORD: xxxxxxxxxxxxxxxxx
LOCAL_NETWORK: 192.168.0.0/16
WEBPROXY_ENABLED: 'false'
CREATE_TUN_DEVICE: 'true'

```

I get still:

```
Using OpenVPN provider: NORDVPN
2020-08-19 16:01:47 Checking curl installation
2020-08-19 16:01:47 Removing existing configs
2020-08-19 16:01:47 Selecting the best server...
2020-08-19 16:01:47 Searching for group: legacy_p2p
2020-08-19 16:01:47 Searching for technology: openvpn_udp
2020-08-19 16:01:47 Best server : fr552.nordvpn.com
2020-08-19 16:01:47 Downloading config: default.ovpn
2020-08-19 16:01:47 Downloading from: https://downloads.nordcdn.com/config-internals/files/ovpn_udp/servers/fr552.nordvpn.com.udp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    284      0 --:--:-- --:--:-- --:--:--   283
100   162  100   162    0     0    284      0 --:--:-- --:--:-- --:--:--   283
2020-08-19 16:01:47 Checking line endings
2020-08-19 16:01:47 Updating configs for docker-transmission-openvpn
Starting OpenVPN using config default.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/16 via 172.30.32.1 dev eth0
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/default.ovpn:1: html (2.4.8)
Use --help for more information.
```
How is it supposed to be configured to get it run ? :(

**Comment by thundergreen** [comment] 2020-08-19 14:05
Also I MUST NOT USE french server as they are oblidged to give any data if requested from the goverment :)

**Comment by edgd1er** [comment] 2020-08-19 17:41
When I use nordvpn I set all three ENV NORDVPN_{PROTOCOL,COUNTRY,CATEGORY}, and never had a problem.
Here, the country is not set so "guessed" by the script, may not be the one you want.
You may wish tio define NORDVPN_COUNTRY also.

a default config file is downloaded but never used. At least, nver seen it used as a config for open_vpn.

**Comment by thundergreen** [comment] 2020-08-19 17:52
@edgd1er If I add thise values in the confug it throws error like unknown options.. would you mind posting your complete config for this addon ??

**Comment by edgd1er** [comment] 2020-08-19 20:07
@thundergreen ,  Well, I use docker-compose to run the container but the interesting part for you is:
```
NORDVPN_CATEGORY=legacy_p2p
NORDVPN_COUNTRY=EE
NORDVPN_PROTOCOL=tcp
OPENVPN_PASSWORD=******
OPENVPN_PROVIDER=NORDVPN
OPENVPN_USERNAME=user@domain.com
```

then in the logs I have: 
```
Using OpenVPN provider: NORDVPN
2020-08-19 00:00:27 Checking curl installation
2020-08-19 00:00:27 Removing existing configs
2020-08-19 00:00:27 Selecting the best server...
2020-08-19 00:00:27 Searching for technology: openvpn_tcp
2020-08-19 00:00:27 Best server : fr574.nordvpn.com
2020-08-19 00:00:27 Downloading config: default.ovpn
2020-08-19 00:00:27 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/fr574.nordvpn.com.tcp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
100  2807  100  2807    0     0    665      0  0:00:04  0:00:04 --:--:--   665
100  2807  100  2807    0     0    665      0  0:00:04  0:00:04 --:--:--   701
2020-08-19 00:00:27 Selecting the best server...
2020-08-19 00:00:27 Searching for country : EE (68)
2020-08-19 00:00:27 Searching for technology: openvpn_tcp
2020-08-19 00:00:27 Best server : ee47.nordvpn.com
2020-08-19 00:00:27 Downloading config: ee47.nordvpn.com.ovpn
2020-08-19 00:00:27 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/ee47.nordvpn.com.tcp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current Dload  Upload   Total   Spent    Left  Speed  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2808  100  2808    0     0   5142      0 --:--:-- --:--:-- --:--:--  5152
2020-08-19 00:00:27 Checking line endings
2020-08-19 00:00:27 Updating configs for docker-transmission-openvpn
Starting OpenVPN using config ee47.nordvpn.com.ovpn
Setting OPENVPN credentials...
```
I hope it helps

**Comment by thundergreen** [comment] 2020-08-19 21:16
@edgd1er The problem is that with the hassio addon you cannot set things like
```
NORDVPN_CATEGORY=legacy_p2p
NORDVPN_COUNTRY=EE
NORDVPN_PROTOCOL=tcp```
It will throw an error of wrong config... it is nt supported by the hassio addon. I am already running this as docker but wanted to change to hassio addon

**Comment by edgd1er** [comment] 2020-08-20 00:10
ok, so the problem is with Home assistant plugin and not haugene's container. I'm not using HA so can't help.
You may have more answers in home assistant forums.

**Comment by haugene** [comment] 2020-08-23 18:23
Tested a couple of config combinations now. And I see the issue in some of them.

Using this docker-compose.yml it works as it should, gets the recommended server and downloads the file correctly:
```
version: '3.3'
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    environment:
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=NORDVPN
        - OPENVPN_USERNAME=username
        - OPENVPN_PASSWORD=password
    cap_add:
        - NET_ADMIN

```

But if I add `OPENVPN_CONFIG=no195.nordvpn.com` which was what I got as recommendation on the first run I get the same URL issues as described here. The container logs `Setting NORDVPN_PROTOCOL to: COM` which should be a hint that something is not right. As you also point out @edgd1er, it is not a valid protocol.

But the script grabs the protocol from the last part of the config name. I tried to add .udp to the config name and setting `OPENVPN_CONFIG=no195.nordvpn.com.udp` and then it sets the protocol correctly. I do get another invalid url though: `https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/no195.nordvpn.com.udp.udp.ovpn` with a duplicate .udp.udp and it fails.

I believe that this would all work better without the automatic detection of protocol from the server name. We have the `NORDVPN_PROTOCOL` environment variable that can be set and it defaults to UDP which is good for most people.

I'll push a small PR for this. If there are some drawbacks to this that I'm not seeing - let me know 😄

**Comment by haugene** [comment] 2020-08-24 13:07
GitHub closes issues when a PR that says it will fix it is merged. A bit optimistic default behaviour if you ask me. Anyways!

Merged what I believe to be a fix. It is now available on the `latest` tag.
@thundergreen @anderssv: Test it and let me know?

**Comment by thundergreen** [comment] 2020-08-25 17:00
@haugene I use hassio Addon with config:

```
PUID: 1001
PGID: 1001
OPENVPN_PROVIDER: NORDVPN
OPENVPN_CONFIG: se449.nordvpn.com
OPENVPN_USERNAME: xxxxxxxxxxxxxxxxx
OPENVPN_PASSWORD: 'xxxxxxxxxxxxxxxxx'
LOCAL_NETWORK: 192.168.0.0/16
WEBPROXY_ENABLED: 'false'
CREATE_TUN_DEVICE: 'true'
```

and still 

```
Using OpenVPN provider: NORDVPN
Setting NORDVPN_PROTOCOL to: COM
2020-08-25 18:58:42 Checking curl installation
2020-08-25 18:58:42 Removing existing configs
2020-08-25 18:58:42 Selecting the best server...
2020-08-25 18:58:42 Searching for group: legacy_p2p
2020-08-25 18:58:42 Best server : fr573.nordvpn.com
2020-08-25 18:58:42 Downloading config: default.ovpn
2020-08-25 18:58:42 Downloading from: https://downloads.nordcdn.com/config-internals/filesfr573.nordvpn.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    287      0 --:--:-- --:--:-- --:--:--   287
100   162  100   162    0     0    287      0 --:--:-- --:--:-- --:--:--   286
2020-08-25 18:58:42 Using OpenVPN CONFIG :: se449.nordvpn.com
2020-08-25 18:58:42 Downloading config: se449.nordvpn.com.ovpn
2020-08-25 18:58:42 Downloading from: https://downloads.nordcdn.com/config-internals/filesse449.nordvpn.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    292      0 --:--:-- --:--:-- --:--:--   292
2020-08-25 18:58:42 Checking line endings
2020-08-25 18:58:42 Updating configs for docker-transmission-openvpn
Starting OpenVPN using config se449.nordvpn.com.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/16 via 172.30.32.1 dev eth0
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/se449.nordvpn.com.ovpn:1: html (2.4.9)
Use --help for more information.
```

**Comment by haugene** [comment] 2020-08-25 20:53
@thundergreen Doesn't look like you've got the new image with my changes. It is still printing "Setting NORDVPN_PROTOCOL to: COM" and I removed that log line in my fix. You need to pull the latest image.

**Comment by thundergreen** [comment] 2020-08-25 20:53
then i guess the hassio addn is not updated yet :(

**Comment by haugene** [comment] 2020-08-25 21:30
Yeah, possibly. But I guess that just points to the latest image. But latest then is not the same as latest now. So you need to refresh/pull the update somehow.

**Closed** 2020-11-01 01:22 UTC
Labels: inactivity
