### ISSUE TITLE
Unable to access web portal now after months of success

### ISSUE THREAD

**Issue by connorjbeatty** [haugene/docker-transmission-openvpn#2728] opened 2023-09-27 22:03 UTC
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

transmission-vpn:
    image: haugene/transmission-openvpn
    container_name: transmission-vpn
    cap_add:
      - ALL
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ${DOCKERDIR}/transmission-vpn:/data
      - ${DOCKERDIR}/shared:/shared
      - ${USERDIR}/torrents:/data/torrents
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    hostname: transmission
    devices:
      - /dev/net/tun
    restart: always
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=sweden, finland, netherlands
      - OVPN_PROTOCOL=tcp
      - OPENVPN_USERNAME=${PIAUSER}
      - OPENVPN_PASSWORD=${PIAPASS}
      - LOCAL_NETWORK=10.0.0.0/24
      - DISABLE_PORT_UPDATER=yes
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,10.0.*.*"
      - TRANSMISSION_RPC_PASSWORD=${UIPASS}
      - TRANSMISSION_RPC_USERNAME=${UIUSER}
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=0.05
      - TRANSMISSION_ALT_SPEED_DOWN=300000
      - TRANSMISSION_ALT_SPEED_ENABLED=true
      - TRANSMISSION_ALT_SPEED_UP=100000
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10
      - TRANSMISSION_PEER_LIMIT_GLOBAL=300
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=100
      - TRANSMISSION_SPEED_LIMIT_DOWN=600000
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=300000
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR=/data/torrents/incomplete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/data/torrents
      - TRANSMISSION_WATCH_DIR_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=/data/torrents/completed

### Current Behavior

Not sure what changed other than unplugging and plugging my ethernet back in.

I'm able to get the container running, but if I look up the IP using this command I got this IP: (172.20.0.6)

`docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' transmission-vpn
`
Unable to reach the web portal despite using local IPs and the IP of my server

### Expected Behavior

Expected it to run same as always, no changes were made to docker compose file

### How have you tried to solve the problem?

1. Tried changing the local network settings
2. Tried changing DNS settings
3. Tried different ports
4. Tried different openvpn config locations
5. Tried different CAP_ADD configs
6. 

### Log output

Starting container with revision: 81277fb6f8ae6aeb57f913172d4d45c7af8c0b31
TRANSMISSION_HOME is currently set to: /config/transmission-home
Creating TUN device /dev/net/tun
Using OpenVPN provider: PIA
Running with VPN_CONFIG_SOURCE auto
Provider PIA has a bundled setup script. Defaulting to internal config
Executing setup script for PIA
Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.vnZ252ERT2
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
3 servers found in OPENVPN_CONFIG, sweden chosen randomly
Starting OpenVPN using config sweden.ovpn
Modifying /etc/openvpn/pia/sweden.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Modification: Updating status for config failure detection
Setting OpenVPN credentials...
adding route to local network 10.0.0.0/24 via 172.20.0.1 dev eth0
2023-09-27 14:53:39 DEPRECATED OPTION: --cipher set to 'aes-128-cbc' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'aes-128-cbc' to --data-ciphers or change --cipher 'aes-128-cbc' to --data-ciphers-fallback 'aes-128-cbc' to silence this warning.
2023-09-27 14:53:39 OpenVPN 2.5.5 aarch64-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 14 2022
2023-09-27 14:53:39 library versions: OpenSSL 3.0.2 15 Mar 2022, LZO 2.10
2023-09-27 14:53:39 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2023-09-27 14:53:39 CRL: loaded 1 CRLs from file -----BEGIN X509 CRL-----
MIICWDCCAUAwDQYJKoZIhvcNAQENBQAwgegxCzAJBgNVBAYTAlVTMQswCQYDVQQI
EwJDQTETMBEGA1UEBxMKTG9zQW5nZWxlczEgMB4GA1UEChMXUHJpdmF0ZSBJbnRl
cm5ldCBBY2Nlc3MxIDAeBgNVBAsTF1ByaXZhdGUgSW50ZXJuZXQgQWNjZXNzMSAw
HgYDVQQDExdQcml2YXRlIEludGVybmV0IEFjY2VzczEgMB4GA1UEKRMXUHJpdmF0
ZSBJbnRlcm5ldCBBY2Nlc3MxLzAtBgkqhkiG9w0BCQEWIHNlY3VyZUBwcml2YXRl
aW50ZXJuZXRhY2Nlc3MuY29tFw0xNjA3MDgxOTAwNDZaFw0zNjA3MDMxOTAwNDZa
MCYwEQIBARcMMTYwNzA4MTkwMDQ2MBECAQYXDDE2MDcwODE5MDA0NjANBgkqhkiG
9w0BAQ0FAAOCAQEAQZo9X97ci8EcPYu/uK2HB152OZbeZCINmYyluLDOdcSvg6B5
jI+ffKN3laDvczsG6CxmY3jNyc79XVpEYUnq4rT3FfveW1+Ralf+Vf38HdpwB8EW
B4hZlQ205+21CALLvZvR8HcPxC9KEnev1mU46wkTiov0EKc+EdRxkj5yMgv0V2Re
ze7AP+NQ9ykvDScH4eYCsmufNpIjBLhpLE2cuZZXBLcPhuRzVoU3l7A9lvzG9mjA
5YijHJGHNjlWFqyrn1CfYS6koa4TGEPngBoAziWRbDGdhEgJABHrpoaFYaL61zqy
MR6jC0K2ps9qyZAN74LEBedEfK7tBOzWMwr58A==
-----END X509 CRL-----
2023-09-27 14:53:39 TCP/UDP: Preserving recently used remote address: [AF_INET]46.246.41.172:1198
2023-09-27 14:53:39 Socket Buffers: R=[212992->212992] S=[212992->212992]
2023-09-27 14:53:39 UDP link local: (not bound)
2023-09-27 14:53:39 UDP link remote: [AF_INET]46.246.41.172:1198
2023-09-27 14:53:39 TLS: Initial packet from [AF_INET]46.246.41.172:1198, sid=8eb230ff 01c75a48
2023-09-27 14:53:39 VERIFY OK: depth=1, C=US, ST=CA, L=LosAngeles, O=Private Internet Access, OU=Private Internet Access, CN=Private Internet Access, name=Private Internet Access, emailAddress=secure@privateinternetaccess.com
2023-09-27 14:53:39 VERIFY KU OK
2023-09-27 14:53:39 Validating certificate extended key usage
2023-09-27 14:53:39 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2023-09-27 14:53:39 VERIFY EKU OK
2023-09-27 14:53:39 VERIFY OK: depth=0, C=US, ST=CA, L=LosAngeles, O=Private Internet Access, OU=Private Internet Access, CN=stockholm407, name=stockholm407
2023-09-27 14:53:39 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 2048 bit RSA, signature: RSA-SHA512
2023-09-27 14:53:39 [stockholm407] Peer Connection Initiated with [AF_INET]46.246.41.172:1198
2023-09-27 14:53:40 SENT CONTROL [stockholm407]: 'PUSH_REQUEST' (status=1)
2023-09-27 14:53:40 PUSH: Received control message: 'PUSH_REPLY,comp-lzo no,redirect-gateway def1,route-ipv6 2000::/3,dhcp-option DNS 10.0.0.243,route-gateway 10.8.112.1,topology subnet,ping 10,ping-restart 60,ifconfig 10.8.112.134 255.255.255.0,peer-id 9,cipher AES-128-GCM'
2023-09-27 14:53:40 OPTIONS IMPORT: timers and/or timeouts modified
2023-09-27 14:53:40 OPTIONS IMPORT: compression parms modified
2023-09-27 14:53:40 OPTIONS IMPORT: --ifconfig/up options modified
2023-09-27 14:53:40 OPTIONS IMPORT: route options modified
2023-09-27 14:53:40 OPTIONS IMPORT: route-related options modified
2023-09-27 14:53:40 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
2023-09-27 14:53:40 OPTIONS IMPORT: peer-id set
2023-09-27 14:53:40 OPTIONS IMPORT: adjusting link_mtu to 1625
2023-09-27 14:53:40 OPTIONS IMPORT: data channel crypto options modified
2023-09-27 14:53:40 Data Channel: using negotiated cipher 'AES-128-GCM'
2023-09-27 14:53:40 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
2023-09-27 14:53:40 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
2023-09-27 14:53:40 net_route_v4_best_gw query: dst 0.0.0.0
2023-09-27 14:53:40 net_route_v4_best_gw result: via 172.20.0.1 dev eth0
2023-09-27 14:53:40 ROUTE_GATEWAY 172.20.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:14:00:06
2023-09-27 14:53:40 GDG6: remote_host_ipv6=n/a
2023-09-27 14:53:40 net_route_v6_best_gw query: dst ::
2023-09-27 14:53:40 sitnl_send: rtnl: generic error (-101): Network is unreachable
2023-09-27 14:53:40 ROUTE6: default_gateway=UNDEF
2023-09-27 14:53:40 TUN/TAP device tun0 opened
2023-09-27 14:53:40 net_iface_mtu_set: mtu 1500 for tun0
2023-09-27 14:53:40 net_iface_up: set tun0 up
2023-09-27 14:53:40 net_addr_v4_add: 10.8.112.134/24 dev tun0
2023-09-27 14:53:40 net_route_v4_add: 46.246.41.172/32 via 172.20.0.1 dev [NULL] table 0 metric -1
2023-09-27 14:53:40 net_route_v4_add: 0.0.0.0/1 via 10.8.112.1 dev [NULL] table 0 metric -1
2023-09-27 14:53:40 net_route_v4_add: 128.0.0.0/1 via 10.8.112.1 dev [NULL] table 0 metric -1
2023-09-27 14:53:40 WARNING: OpenVPN was configured to add an IPv6 route. However, no IPv6 has been configured for tun0, therefore the route installation may fail or may not work as expected.
2023-09-27 14:53:40 add_route_ipv6(2000::/3 -> :: metric -1) dev tun0
2023-09-27 14:53:40 net_route_v6_add: 2000::/3 via :: dev tun0 table 0 metric -1
2023-09-27 14:53:40 sitnl_send: rtnl: generic error (-13): Permission denied
2023-09-27 14:53:40 ERROR: Linux IPv6 route can't be added
Up script executed with device=tun0 ifconfig_local=10.8.112.134
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.8.112.134
Enforcing ownership on transmission directories
Applying permissions to transmission directories
Setting owner for transmission paths to 1000:1000
Setting permissions for download and incomplete directories
umask: 2
Directories: 775
Files: 664
Setting permission for watch directory (775) and its files (664)
-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    1000
-------------------------------------
Updating Transmission settings.json with values from env variables
Attempting to use existing settings.json for Transmission
Successfully used existing settings.json /config/transmission-home/settings.json
Overriding alt-speed-down because TRANSMISSION_ALT_SPEED_DOWN is set to 300000
Overriding alt-speed-enabled because TRANSMISSION_ALT_SPEED_ENABLED is set to true
Overriding alt-speed-up because TRANSMISSION_ALT_SPEED_UP is set to 100000
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.8.112.134
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/torrents/completed
Overriding download-queue-enabled because TRANSMISSION_DOWNLOAD_QUEUE_ENABLED is set to true
Overriding download-queue-size because TRANSMISSION_DOWNLOAD_QUEUE_SIZE is set to 10
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/torrents/incomplete
Overriding incomplete-dir-enabled because TRANSMISSION_INCOMPLETE_DIR_ENABLED is set to true
Overriding peer-limit-global because TRANSMISSION_PEER_LIMIT_GLOBAL is set to 300
Overriding peer-limit-per-torrent because TRANSMISSION_PEER_LIMIT_PER_TORRENT is set to 100
Overriding ratio-limit because TRANSMISSION_RATIO_LIMIT is set to 0.05
Overriding ratio-limit-enabled because TRANSMISSION_RATIO_LIMIT_ENABLED is set to true
Overriding rpc-authentication-required because TRANSMISSION_RPC_AUTHENTICATION_REQUIRED is set to true
Overriding rpc-host-whitelist because TRANSMISSION_RPC_HOST_WHITELIST is set to 127.0.0.1,10.0.*.*
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding rpc-username because TRANSMISSION_RPC_USERNAME is set to connorbeatty
Overriding speed-limit-down because TRANSMISSION_SPEED_LIMIT_DOWN is set to 600000
Overriding speed-limit-down-enabled because TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED is set to true
Overriding speed-limit-up because TRANSMISSION_SPEED_LIMIT_UP is set to 300000
Overriding speed-limit-up-enabled because TRANSMISSION_SPEED_LIMIT_UP_ENABLED is set to true
Overriding umask because TRANSMISSION_UMASK is set to 002
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/torrents
Overriding watch-dir-enabled because TRANSMISSION_WATCH_DIR_ENABLED is set to true
sed'ing True to true
STARTING TRANSMISSION
Transmission startup script complete.
2023-09-27 14:53:40 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
2023-09-27 14:53:40 Initialization Sequence Completed

### HW/SW Environment

```markdown
- OS: MacOS 13.6 Ventura
- Docker: 4.23.0
```

### Anything else?

Without changes made in my docker compose file, I'm stumped as to what the issue could be...

**Comment by pkishino** [comment] 2023-09-28 01:49
duplicate of #2723 
downgrade to 4.22.0 docker for now seems to work, this is a docker issue and not a container issue..

**Closed by pkishino** 2023-09-28 01:49 UTC

**Comment by connorjbeatty** [comment] 2023-12-20 22:20
@pkishino This issue is ongoing and the latest Docker updates have not changed anything.

Not sure if this helps, but I'm having issues on an M1 Mac whilst my friend has this working with an Intel based Mac.

**Comment by pkishino** [comment] 2023-12-20 22:59
This issue is on both Intel and M series Macs, all your friends to check their docker version, I remember looking into it a while back but no progress.
