### ISSUE TITLE
PIA Port Forwarding is broken

### ISSUE THREAD

**Issue by bonez56** [haugene/docker-transmission-openvpn#1399] opened 2020-10-14 00:46 UTC
**Describe the problem**
PIA has a new API for port forwarding, and the script no longer successfully obtains a port forward and passes it through to Transmission

**Logs**
```
STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Wait for tunnel to be fully initialized and PIA is ready to give us a port
Wed Oct 14 04:59:37 2020 Initialization Sequence Completed
Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding
curl encountered an error looking up new port: 7
```

**Host system:**
Debian 10.5, Docker Docker version 19.03.12, build 48a66213fe

There is some information here: https://www.privateinternetaccess.com/forum/discussion/comment/57849/#Comment_57849

Also, port forwarding is now available worldwide on all PIA servers _excluding_ those based in the USA.

**Comment by haugene** [comment] 2020-10-14 08:30
Hey. Yeah, we're aware and working towards a fix :+1: 
The curl error code is different but this is basically a duplicate of #1364 which is being followed up in #1334 that takes on both updating to the nextgen servers and getting a working port update script again.

Closing this.

**Closed by haugene** 2020-10-14 08:30 UTC
