### ISSUE TITLE
Web UI not loading

### ISSUE THREAD

**Issue by MartenvanWezel** [haugene/docker-transmission-openvpn#1556] opened 2020-11-26 16:15 UTC
my TRANSMISSION_HOME variable is pointing to /data/transmission-home (which is outside the container)
Then going to http://192.168.1.10:9091/transmission/web/ used to work. 

Now, I get:
`Couldn't find Transmission's web interface files!
Users: to tell Transmission where to look, set the TRANSMISSION_WEB_HOME environment variable to the folder where the web interface's index.html is located.`

And indeed fair enough, /data/transmission-home does not contain an index.html

If instead I point TRANSMISSION_HOME to /opt/transmission-ui/transmission-web-control  - where the files actually seem to be - I get:

`Unauthorized IP Address.
Either disable the IP address whitelist or add your address to it.
If you're editing settings.json, see the 'rpc-whitelist' and 'rpc-whitelist-enabled' entries`

Deleting transmission_home altogether also didn't work.

Halp? My suspicion is that transmission used to ignore the home directive, and now it's not.. but not finding them in the right place..  I could just manually copy the web UI files into my /data/transmission-home folder but that's not an elegant fix.

**Comment by haugene** [comment] 2020-11-26 16:19
I've written this in some other issue, but I can't seem to find it now. My guess is that this is happening because you have set a lot of the TRANSMISSION_ environment variables that used to be default but now are removed. Especially TRANSMISSION_WEB_HOME that has to be unset to have the default UI. If it's set to a blank value that will cause the error.
The rpc-whitelist stuff should be fixed by the default settings.json. Try deleting your settings.json in transmission_home and restart.

Either way. Please post your container config and logs. It's very hard to guess at what's wrong without having that.

**Comment by phil-hudson** [comment] 2020-12-01 14:53
@MartenvanWezel did you make any progress with this? did you resolve?

**Comment by MartenvanWezel** [comment] 2020-12-01 14:54
Yes, but my main strategy was to start from scratch :)

**Comment by Hanyoro** [comment] 2020-12-07 05:42
@MartenvanWezel Can you please tell me what you did exactly? Does it keep all your torrents?

**Comment by haugene** [comment] 2020-12-09 23:13
@MartenvanWezel So this issue is solved and can be closed?

If you're still having issues @phil-hudson I've started on a debug-guide to pinpoint where in the setup stuff fails. Run through it and create a new issue with a description on how far you came and what errors you got. Any suggestions for improvements on the guide itself is also appreciated.

**Comment by add-zero** [comment] 2021-01-11 08:01
As a small, late contribution, I had the same problem, but following what @haugene said earlier, just removing (not leaving blank) the TRANSMISSION_WEB_HOME variable worked for me.

**Comment by haugene** [comment] 2021-02-24 21:47
It sounds like the issue is resolved. I'll close it for now. For anyone reading this later, the debug guide I was mentioning is here: https://haugene.github.io/docker-transmission-openvpn/debug/

If you face the same issue, please try the guide before opening a new issue.

**Closed** 2021-02-24 21:48 UTC
