### ISSUE TITLE
Preference settings in webui don't work

### ISSUE THREAD

**Issue by farika** [haugene/docker-transmission-openvpn#1404] opened 2020-10-18 14:41 UTC
Hi,
When i change some settings in webui it's uneffective (like numbers of peers or encryption). It is normal ? Does i need to change my docker compose every time ? 
Thanks

**Comment by haugene** [comment] 2020-10-19 20:42
Hi. Yes, as of now you have to change in docker-compose every time. It was implemented like this by design but we have since seen that people prefer to be able to change it from the WebUI and I understand that.

Change is coming. If you run the image with the `dev` tag you will get the version with persistent settings. There might be more bugs on the dev branch so shout out if you find one. Hoping to have it stable and ready for new release and `latest` tag soon.

This issue is a duplicate of #1130 and I will close it now. Watch for the 3.0 release, that will bring this to master branch. Give us some weeks ;)

**Closed by haugene** 2020-10-19 20:42 UTC
