### ISSUE TITLE
VPN server DNS name resolution problem when UFW enabled

### ISSUE THREAD

**Issue by polachz** [haugene/docker-transmission-openvpn#1817] opened 2021-04-24 17:25 UTC
## Before creating this issue I have:

**REQUIRED**
- [X] Read through the pinned issues for related problems
- [X] Searched for similar [provider issues][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible
- [X] Verified I have tried using newest release as well
- [X] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release

**haugene/transmission-openvpn:latest (digest: a9038a56727f  linux/amd64)** 
 
```digest: a9038a56727f  linux/amd64```

*If possible, last working version:* 
 
```
```

### Describe the problem

**REQUIRED**
```txt
If the UFW is enabled, the container is not able to resolve DNS 
name of the VPN server during start and then container start failed. 
When UFW is disabled, container starts correctly
```
### Describe the steps you have tried to solve the problem

**REQUIRED**
```txt
1) Tried to add UFW_EXTRA_PORTS=53
2) Tried UFW_ALLOW_GW_NET=true
3) Tried specify DNS servers to docker compose - see the content below
4) Tried to specify DNS server on the local subnet

```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```txt
version: '3'
services:
     transmission:
         container_name: transmission
         image: haugene/transmission-openvpn
         restart: always
         cap_add: 
           - NET_ADMIN
         dns:
           - 1.1.1.1
           - 1.0.0.1 
         ports:
           - '9091:9091'
           - '8888:8888'
         volumes:
           - /xxxx/config:/config
           - /xxxx:/data
           - /xxxx/config/ovpn:/etc/openvpn/custom    
         environment:
            - OPENVPN_PROVIDER=CUSTOM
            - OPENVPN_CONFIG=location_1
            - OPENVPN_USERNAME=user
            - OPENVPN_PASSWORD=pass
            - LOCAL_NETWORK=XXXXXX/22 ##!!Must be subnet (has 0 in ip) otherwise it fails
            - ENABLE_UFW=true
            - UFW_ALLOW_GW_NET=false
            #- UFW_EXTRA_PORTS=53
            - TZ=CZ
            - TRANSMISSION_WEB_UI=transmission-web-control
            - WEBPROXY_ENABLED=true
            - WEBPROXY_PORT=8888
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
```

### Logs

 

**REQUIRED**
```txt
Starting container with revision: e775d4cf7b4ca3ba660805617ee1fe14afb5252c,
Creating TUN device /dev/net/tun,
Using OpenVPN provider: CUSTOM,
Starting OpenVPN using config location_1.ovpn,
Setting OpenVPN credentials...,
enabling firewall,
ERROR: problem running ufw-init,
modprobe: can't change directory to '/lib/modules': No such file or directory,
modprobe: can't change directory to '/lib/modules': No such file or directory,
modprobe: can't change directory to '/lib/modules': No such file or directory,
iptables-restore v1.8.6 (legacy): Couldn't load match `limit':No such file or directory,
,
ror occurred at line: 63,
Try `iptables-restore -h' or 'iptables-restore --help' for more information.,
iptables-restore v1.8.6 (legacy): Couldn't load match `limit':No such file or directory,
,
Error occurred at line: 8,
Try `iptables-restore -h' or 'iptables-restore --help' for more information.,
sysctl: error setting key 'net.ipv4.conf.default.rp_filter': Read-only file system,
sysctl: error setting key 'net.ipv4.conf.all.rp_filter': Read-only file system,
sysctl: error setting key 'net.ipv4.conf.default.accept_source_route': Read-only file system,
sysctl: error setting key 'net.ipv4.conf.all.accept_source_route': Read-only file system,
sysctl: error setting key 'net.ipv6.conf.default.accept_source_route': Read-only file system,
sysctl: error setting key 'net.ipv6.conf.all.accept_source_route': Read-only file system,
sysctl: error setting key 'net.ipv4.conf.default.accept_redirects': Read-only file system,
sysctl: error setting key 'net.ipv4.conf.all.accept_redirects': Read-only file system,
sysctl: error setting key 'net.ipv6.conf.default.accept_redirects': Read-only file system,
sysctl: error setting key 'net.ipv6.conf.all.accept_redirects': Read-only file system,
sysctl: error setting key 'net.ipv4.icmp_echo_ignore_broadcasts': Read-only file system,
sysctl: error setting key 'net.ipv4.icmp_ignore_bogus_error_responses': Read-only file system,
sysctl: error setting key 'net.ipv4.icmp_echo_ignore_all': Read-only file system,
sysctl: error setting key 'net.ipv4.conf.default.log_martians': Read-only file system,
sysctl: error setting key 'net.ipv4.conf.all.log_martians': Read-only file system,
sysctl: error setting key 'net.ipv4.tcp_sack': Read-only file system,
,
Problem running '/etc/ufw/before.rules',
Problem running '/etc/ufw/user.rules',
,
allowing 8888 through the firewall,
Rules updated,
allowing 172.29.88.1 through the firewall to port 9091,
Rules updated,
adding route to local network XXXXXX/22 via 172.29.88.1 dev eth0,
allowing XXXXXXX/22 through the firewall to port 9091,
Rules updated,
2021-04-24 16:57:17 Multiple --up scripts defined.  The previously configured script is overridden.,
2021-04-24 16:57:17 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.,
2021-04-24 16:57:17 WARNING: file '/etc/openvpn/custom/prv.pem' is group or others accessible,
2021-04-24 16:57:17 WARNING: file '/etc/openvpn/custom/auth' is group or others accessible,
2021-04-24 16:57:17 OpenVPN 2.5.1 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 16 2021,
2021-04-24 16:57:17 library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10,
2021-04-24 16:57:17 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.,
2021-04-24 16:57:17 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
2021-04-24 16:57:22 RESOLVE: Cannot resolve host address: prg-cz.prcdn.net:553 (Try again),
2021-04-24 16:57:27 RESOLVE: Cannot resolve host address: prg-cz.prcdn.net:553 (Try again),
2021-04-24 16:57:27 Could not determine IPv4/IPv6 protocol,
2021-04-24 16:57:27 SIGUSR1[soft,init_instance] received, process restarting,
2021-04-24 16:57:27 Restart pause, 5 second(s),
2021-04-24 16:57:32 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.,
2021-04-24 16:57:32 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
2021-04-24 16:57:37 RESOLVE: Cannot resolve host address: prg-cz.prcdn.net:553 (Try again),
2021-04-24 16:57:42 RESOLVE: Cannot resolve host address: prg-cz.prcdn.net:553 (Try again),
2021-04-24 16:57:42 Could not determine IPv4/IPv6 protocol,
2021-04-24 16:57:42 SIGUSR1[soft,init_instance] received, process restarting,
2021-04-24 16:57:42 Restart pause, 5 second(s),
2021-04-24 16:57:47 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.,
2021-04-24 16:57:47 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
2021-04-24 16:57:52 RESOLVE: Cannot resolve host address: prg-cz.prcdn.net:553 (Try again),
2021-04-24 16:57:57 RESOLVE: Cannot resolve host address: prg-cz.prcdn.net:553 (Try again),
2021-04-24 16:57:57 Could not determine IPv4/IPv6 protocol,
2021-04-24 16:57:57 SIGUSR1[soft,init_instance] received, process restarting,
2021-04-24 16:57:57 Restart pause, 5 second(s),
```

### Host system

**REQUIRED**
```txt
QNAP Container Staton
```

**Comment by pkishino** [comment] 2021-04-25 04:15
Hmm, this looks quite strange, I wonder if this is related to the QNAP platform..
I created a new container based on your env variables and it ran fine for me..
I did see you are using an unusual subnet range for the LOCAL_NETWORK param..
see below for the basic config I used to test:
```
OPENVPN_PROVIDER=CUSTOM
OPENVPN_USERNAME=xxxxx
OPENVPN_PASSWORD=xxxxx
LOCAL_NETWORK=10.1.125.0/24, 172.20.10.0/24
OPENVPN_OPTS=--mute-replay-warnings
TZ=Asia/Tokyo
ENABLE_UFW=true
UFW_ALLOW_GW_NET=false
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DROP_DEFAULT_ROUTE=true
GLOBAL_APPLY_PERMISSIONS=true
TRANSMISSION_HOME=/data/transmission-home
TRANSMISSION_RPC_PORT=9091
TRANSMISSION_DOWNLOAD_DIR=/data/completed
TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
TRANSMISSION_WATCH_DIR=/data/watch
CREATE_TUN_DEVICE=true
UFW_EXTRA_PORTS=
UFW_DISABLE_IPTABLES_REJECT=false
PUID=
PGID=
WEBPROXY_ENABLED=true
WEBPROXY_PORT=8888
WEBPROXY_USERNAME=
WEBPROXY_PASSWORD=
LOG_TO_STDOUT=false
HEALTH_CHECK_HOST=google.com
REVISION=e775d4cf7b4ca3ba660805617ee1fe14afb5252c
```

**Comment by polachz** [comment] 2021-04-26 13:12
I think that main problem here is that in my config file is FQDN for remote serverm not IP:

```
#####################
client

remote prg-cz.prcdn.net 553
proto udp
config /etc/openvpn/custom/common.ovpn

#####################
```

When UFW is enabled, from log it seems that it's fired before tunnel establishing process. And then DNS query or reply is blocked here. Due this resolution of the **prg-cz.prcdn.net** failed, I think.

When tunnel is established, all DNS goes through the tunnel and it's allowed by UFW. But scenario when DNS is required before the tunnel is established is the problem, I think

**Comment by ksurl** [comment] 2021-05-23 21:57
You need to add a custom script to add allow ufw rule for the external dns before tunnel is up.

**Comment by pkishino** [comment] 2021-05-23 23:16
> You need to add a custom script to add allow ufw rule for the external dns before tunnel is up.

Let me look into adding this, I thought this was already sorted..

**Comment by ksurl** [comment] 2021-05-23 23:19
I don't think it should be broken out of box but I do have one since I first reset all rules and then add deny in and out by default and explicitly allow dns and vpn and transmission ports. Just a little extra paranoid config on top of the builtin iptables rules from the image

**Comment by pkishino** [comment] 2021-05-23 23:31
> I don't think it should be broken out of box but I do have one since I first reset all rules and then add deny in and out by default and explicitly allow dns and vpn and transmission ports. Just a little extra paranoid config on top of the builtin iptables rules from the image

Can I ask why you are doing this ? Not satisfied with the builtin rules? suggestions worth adding?

@polachz your logs show a number of errors related to ufw at the top which I suspect is causing this.. because this should be fine with the current setup..

**Comment by ksurl** [comment] 2021-05-23 23:34
I set it up a while ago, and don't remember the issue I was having. I guess I can try it again without it but it is currently working for me.

**Comment by pkishino** [comment] 2021-05-24 00:10
Ok, if you want to share your script/mods feel free :)

**Comment by ksurl** [comment] 2021-05-24 03:20
`openvpn-pre-start.sh`

```
#!/bin/bash

# reset
ufw --force reset

# default
ufw default deny incoming
ufw default deny outgoing

# localhost
# allow local lan to web ui
ufw allow in on eth0 from 127.0.0.1 port 9091 proto tcp

# dns
ufw allow out 53

# openvpn
# repeat as needed for additional servers
ufw allow out to <VPN_SERVER_IP> port 1194 proto udp

# tunnel
# set incoming port if different from default
ufw allow out on tun0
ufw allow in on tun0 to any port 51413 proto tcp


```

**Comment by polachz** [comment] 2021-05-24 05:43
> 
> 
> > I don't think it should be broken out of box but I do have one since I first reset all rules and then add deny in and out by default and explicitly allow dns and vpn and transmission ports. Just a little extra paranoid config on top of the builtin iptables rules from the image
> 
> Can I ask why you are doing this ? Not satisfied with the builtin rules? suggestions worth adding?
> 
> @polachz your logs show a number of errors related to ufw at the top which I suspect is causing this.. because this should be fine with the current setup..

Why I do thjis? Because the VPN provider use DNS name for VPN server instead of IP address -> and time to time the IP of the VPN server is changed, due some complains... So, IP is changing, DNS still works and it's a reason why DNS is necessary to setablish VPN tunnel.

**Comment by pkishino** [comment] 2021-05-24 07:46
sorry, first part was for @ksurl .. anyway, if you look at the start of your log it complains about ufw-init failed.. 
because for me when I test with a dns name and ufw it works fine without any further steps.. I suspect that it not working for you, neither with 53 and GW allow is because of ufw-init failure at the start..

**Comment by pkishino** [comment] 2021-09-09 06:14
@haugene any chance to take a quick look at this please?
@polachz have you tried with release 4.0 yet?

**Comment by pkishino** [comment] 2021-09-29 00:55
I tested this again now on dev branch and it seems to work, all I did was add the vpn provider config port (1195) to allowed ports and it came up
```txt
Setting OpenVPN credentials...
enabling firewall
Firewall is active and enabled on system startup
allowing 1080 through the firewall
Rule added
allowing 172.20.10.1 through the firewall to port 9091
Rule added
allowing 172.20.10.1 through the firewall to port 1195
Rule added
adding route to local network 10.1.125.0/24 via 172.20.10.1 dev eth0
allowing 10.1.125.0/24 through the firewall to port 9091
Rule added
allowing 10.1.125.0/24 through the firewall to port 1195
Rule added
adding route to local network 172.20.10.0/24 via 172.20.10.1 dev eth0
RTNETLINK answers: File exists
allowing 172.20.10.0/24 through the firewall to port 9091
Rule added
allowing 172.20.10.0/24 through the firewall to port 1195
Rule added
Wed Sep 29 09:49:10 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
Wed Sep 29 09:49:10 2021 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Wed Sep 29 09:49:10 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Sep 29 09:49:10 2021 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Sep 29 09:49:10 2021 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Sep 29 09:49:10 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]89.187.160.154:1195
Wed Sep 29 09:49:10 2021 Socket Buffers: R=[212992->212992] S=[212992->212992]
Wed Sep 29 09:49:10 2021 UDP link local: (not bound)
Wed Sep 29 09:49:10 2021 UDP link remote: [AF_INET]89.187.160.154:1195
Wed Sep 29 09:49:10 2021 TLS: Initial packet from [AF_INET]89.187.160.154:1195, sid=029d3b5f 417590c8
Wed Sep 29 09:49:10 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Sep 29 09:49:10 2021 VERIFY OK: depth=1, C=SE, ST=CA, L=Stockholm, O=PrivateVPN, CN=PrivateVPN CA, name=PrivateVPN, emailAddress=support@privatvpn.se
Wed Sep 29 09:49:10 2021 VERIFY KU OK
Wed Sep 29 09:49:10 2021 Validating certificate extended key usage
Wed Sep 29 09:49:10 2021 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Wed Sep 29 09:49:10 2021 VERIFY EKU OK
Wed Sep 29 09:49:10 2021 VERIFY OK: depth=0, C=SE, ST=CA, L=Stockholm, O=PrivateVPN, CN=PrivateVPN, name=PrivateVPN, emailAddress=support@privatvpn.se
Wed Sep 29 09:49:11 2021 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 2048 bit RSA
Wed Sep 29 09:49:11 2021 [PrivateVPN] Peer Connection Initiated with [AF_INET]89.187.160.154:1195
Wed Sep 29 09:49:12 2021 SENT CONTROL [PrivateVPN]: 'PUSH_REQUEST' (status=1)
Wed Sep 29 09:49:12 2021 PUSH: Received control message: 'PUSH_REPLY,explicit-exit-notify 2,comp-lzo no,sndbuf 524288,rcvbuf 524288,redirect-gateway def1,dhcp-option DISABLE-NBT,dhcp-option DNS 10.35.53.1,dhcp-option DNS 10.35.53.2,route-gateway xxxxxx,topology subnet,ping 20,ping-restart 60,ifconfig xxxxxx 255.255.255.192,peer-id 2,cipher AES-256-GCM'
Wed Sep 29 09:49:12 2021 Pushed option removed by filter: 'ping 20'
Wed Sep 29 09:49:12 2021 Pushed option removed by filter: 'ping-restart 60'
Wed Sep 29 09:49:12 2021 OPTIONS IMPORT: explicit notify parm(s) modified
Wed Sep 29 09:49:12 2021 OPTIONS IMPORT: compression parms modified
Wed Sep 29 09:49:12 2021 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Wed Sep 29 09:49:12 2021 Socket Buffers: R=[212992->425984] S=[212992->425984]
Wed Sep 29 09:49:12 2021 OPTIONS IMPORT: --ifconfig/up options modified
Wed Sep 29 09:49:12 2021 OPTIONS IMPORT: route options modified
Wed Sep 29 09:49:12 2021 OPTIONS IMPORT: route-related options modified
Wed Sep 29 09:49:12 2021 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Wed Sep 29 09:49:12 2021 OPTIONS IMPORT: peer-id set
Wed Sep 29 09:49:12 2021 OPTIONS IMPORT: adjusting link_mtu to 1625
Wed Sep 29 09:49:12 2021 OPTIONS IMPORT: data channel crypto options modified
Wed Sep 29 09:49:12 2021 Data Channel: using negotiated cipher 'AES-256-GCM'
Wed Sep 29 09:49:12 2021 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Wed Sep 29 09:49:12 2021 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Wed Sep 29 09:49:12 2021 ROUTE_GATEWAY 172.20.10.1/255.255.255.0 IFACE=eth0 HWADDR=02:42:ac:14:0a:0b
Wed Sep 29 09:49:12 2021 TUN/TAP device tun0 opened
Wed Sep 29 09:49:12 2021 TUN/TAP TX queue length set to 100
Wed Sep 29 09:49:12 2021 /sbin/ip link set dev tun0 up mtu 1500
Wed Sep 29 09:49:12 2021 /sbin/ip addr add dev tun0 xxxxx broadcast xxxxxx
Wed Sep 29 09:49:12 2021 /etc/openvpn/tunnelUp.sh tun0 1500 1553 xxxxxx 255.255.255.192 init
Up script executed with tun0 1500 1553 xxxxxxx 255.255.255.192 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : xxxxxx
Using Flood for Transmission UI, overriding TRANSMISSION_WEB_HOME
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to xxxxx
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding peer-port because TRANSMISSION_PEER_PORT is set to 1080
Overriding rpc-authentication-required because TRANSMISSION_RPC_AUTHENTICATION_REQUIRED is set to true
Overriding rpc-enabled because TRANSMISSION_RPC_ENABLED is set to true
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding rpc-whitelist because TRANSMISSION_RPC_WHITELIST is set to 10.1.125.*, 127.0.0.1, 172.20.10.*
sed'ing True to true

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

DROPPING DEFAULT ROUTE
STARTING TRANSMISSION
Transmission startup script complete.
Wed Sep 29 09:49:12 2021 /sbin/ip route add 89.187.160.154/32 via 172.20.10.1
Wed Sep 29 09:49:12 2021 /sbin/ip route add 0.0.0.0/1 via xxxxxx
Wed Sep 29 09:49:12 2021 /sbin/ip route add 128.0.0.0/1 via xxxxx
Wed Sep 29 09:49:12 2021 Initialization Sequence Completed
```

**Comment by pkishino** [comment] 2021-10-01 01:26
I can confirm that latest seems to have fixed this.
closing for now

**Closed by pkishino** 2021-10-01 01:26 UTC
Labels: bug
