### ISSUE TITLE
Container up & running. Transmission just stops

### ISSUE THREAD

**Issue by Djangox** [haugene/docker-transmission-openvpn#1303] opened 2020-07-27 22:14 UTC
This has persisted over the last two-three container updates. Using "latest" tag.

**Describe the problem**
Having same problem as issue #1035 . everything is fine, but at some point, transmission just dies. all processes are still in memory, just all torrents stop and cannot connect to webui. from inside transmission-remote -l times out. VPN is still connected. I can verify active IP address and ping internet. I did the curl command from the other issue and received..
```
root@trans:/# ps aux                                                                                                                                        
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND                                                                                    
root         1  0.0  0.0    196     0 ?        SNs  01:48   0:00 dumb-init /etc/openvpn/start.sh                                                            
root         6  6.7  0.0  12132  3088 pts/0    SNs+ 01:48  82:59 openvpn --script-security 2 --up-delay --up /etc/openvpn/tunnelUp.sh --down /etc/openvpn/tu
abc         59 11.5 13.5 4286744 2224156 ?     SNsl 01:48 141:06 /usr/bin/transmission-daemon -g /data/transmission-home --logfile /data/transmission-home/t
root      7625  0.0  0.0   4204  2328 pts/1    SNs  21:06   0:00 /bin/bash                                                                                  
root      7812  0.0  0.0   5844  1504 pts/1    RN+  22:12   0:00 ps aux                                                                           

root@trans:/# transmission-remote -l                                                                             
[2020-07-27 21:07:41.368] transmission-remote:  (http://localhost:9091/transmission/rpc/) Timeout was reached  

root@trans:/# curl localhost:9091                                                                                
curl: (56) Recv failure: Connection reset by peer
```
in docker log I recieve vpn notifications once an hour. no error messages.

**Add your docker run command**
Using Synology GUI w/ high privilege (fails to run without this option) & currently PrivateVPN

**Logs**
Every hour:
2020-07-27T21:48:25.107718430Z  Mon Jul 27 21:48:25 2020 TLS: soft reset sec=0 bytes=4965758/-1 pkts=38818/0
2020-07-27T21:48:25.119011421Z  Mon Jul 27 21:48:25 2020 VERIFY OK: depth=1, C=SE, ST=CA, L=Stockholm, O=PrivateVPN, CN=PrivateVPN CA, name=PrivateVPN, emailAddress=support@privatvpn.se
2020-07-27T21:48:25.120018414Z  Mon Jul 27 21:48:25 2020 VERIFY KU OK
2020-07-27T21:48:25.120156052Z  Mon Jul 27 21:48:25 2020 Validating certificate extended key usage
2020-07-27T21:48:25.120385228Z  Mon Jul 27 21:48:25 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2020-07-27T21:48:25.120481206Z  Mon Jul 27 21:48:25 2020 VERIFY EKU OK
2020-07-27T21:48:25.120547135Z  Mon Jul 27 21:48:25 2020 VERIFY OK: depth=0, C=SE, ST=CA, L=Stockholm, O=PrivateVPN, CN=PrivateVPN, name=PrivateVPN, emailAddress=support@privatvpn.se
2020-07-27T21:48:25.130298662Z  Mon Jul 27 21:48:25 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
2020-07-27T21:48:25.130463319Z  Mon Jul 27 21:48:25 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
2020-07-27T21:48:25.130611327Z  Mon Jul 27 21:48:25 2020 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 2048 bit RSA

**Host system:**Synology 6.2.3

Which version of Docker are you using? -->  18.09

**Comment by Hedrik** [comment] 2020-08-19 03:01
I am also encounter this issue of transmission not running.  It was all working fine (for over a year) then today stopped.  It appears to die as soon as it is started.  I do not know where to find the transmission logs to see if it is logging any messages during startup that might help.  I am using a Synology and PIA.

I know there was (still is?) an issue with transmission where it would die if there were 'too many' torrents active (I think including being seeded but not uploading to anyone) at once - I doubt that is the issue since I have had far more seeded torrents running without issue in the past... but I thought I'd mention it just in case.  (I had less than ~50 seeded torrents when this issue started)


Logged in to the Synology:

$ sudo more /etc/VERSION 
majorversion="6"
minorversion="2"
productversion="6.2.3"
buildphase="GM"
buildnumber="25426"
smallfixnumber="2"
builddate="2020/07/08"
buildtime="06:20:24"


I use:

docker run --privileged -d \
  --cap-add=NET_ADMIN \
  --device=/dev/net/tun \
  -v /volume1/Plex/Library/Movies/:/Movies \
  -v /volume1/Plex/resolv.conf:/etc/resolv.conf \
  -v /volume1/Plex/Library/Downloads/:/data \
  -v /volume1/Plex/setTransmissionRemotePort.sh:/root/setTransmissionRemotePort.sh \
  -v /volume1/Plex/pia-port.service:/etc/systemd/system/pia-port.service \
  -e "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false" \
  -e "TRANSMISSION_RATIO_LIMIT=0" \
  -e "TRANSMISSION_RATION_LIMIT_ENABLED=true" \
  -e "TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=false" \
  -e "TRANSMISSION_UMASK=0" \
  -e "TRANSMISSION_DOWNLOAD_DIR=/data" \
  -e "TRANSMISSION_PEER_CONGESTION_ALGORITHM=\"\"" \
  -e "OPENVPN_PROVIDER=PIA" \
  -e "OPENVPN_CONFIG=Israel" \
  -e "OPENVPN_USERNAME=*****" \
  -e "OPENVPN_PASSWORD=*****" \
  -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
  --restart=no \
  -p 9091:9091 \
  -p 8080:8080 \
  --name=TransmissionVPN \
  haugene/transmission-openvpn

**Comment by schwukas** [comment] 2020-08-19 05:59
You should find your transmission.log in your data-volume (Downloads) under `transmission-home/transmission.log`.

**Comment by Hedrik** [comment] 2020-08-19 18:55
Thanks for the pointer to the transmission log file - unfortunately there
is nothing in it to indicate why it is dying.  The last few lines are just
'retrying scrape in XX seconds' messages.

**Comment by Hedrik** [comment] 2020-08-20 15:13
This one is really quite an issue for me - does anyone have thoughts on how to troubleshoot it?  I tried moving all the file out of the 'resume' directory (into a new one name 'resume-temp') and restarted the docker container without appearing to have made a difference...

**Comment by DrMacinyasha** [comment] 2020-08-21 05:04
Interestingly, I've had this issue as well and have been troubleshooting it all day. I've gone as far as completely rebuilding my container from the ground up. Abandoning the Synology web UI entirely, I've switched to creating the container using the following command: 

```
docker run \
    --cap-add=NET_ADMIN \
    --device=/dev/net/tun \
    -d \
    -v /volume1/[REMOVED]/Downloading/resolv.conf:/etc/resolv.conf \
    -v /volume1/[REMOVED]/transmission:/data \
    -v /volume1/[REMOVED]/[REMOVED]/:/data/watch \
    -v /volume1/[REMOVED]/Downloading/incomplete:/data/incomplete \
    -v /volume1/[REMOVED]/Complete:/data/completed \
    -p 8888:8888 \
    -p 9091:9091 \
    --env-file /volume1/[REMOVED]/Downloading/transmission-openvpn-syno.dockerenv \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    --log-driver json-file \
    --log-opt max-size=10m \
    --restart unless-stopped \
    --name "[REMOVED]" \
    haugene/transmission-openvpn:latest
```

Digging through the Docker logs for a bit, I found something interesting: `Couldn't (re)open log file "/data/transmission-home/transmission.log": Permission denied`. I decided to look into it a little more. The permissions on the entire /data/transmission-home directory (and all contents) have the owner and group set to the UID and GID that Transmission's running as, and that particular file is chmod'd to 0755 (have also tried 0777). A bit of poking around and I found that the directory which mounted as `/data` had the owner and permissions set too restrictively. I chown'd  it to the UID/GID that I'd told Transmission to use, and chmod'd to 0755, and rm'd the `/data/transmission-home/transmission.log` file. A few updates to my env-file later to deal with some RPC whitelist features resulted in a recreate of the Docker container... And it works!

Hopefully this winds up helping someone somewhere. I wish I had more info on the *why* this broke today for myself and others, but unfortunately I do not. Here's my env-file's relevant lines: 

```
PGID=[REMOVED]
PUID=[REMOVED]
OPENVPN_PROVIDER=PIA
OPENVPN_CONFIG=CA Toronto,CA Montreal,CA Vancouver
OPENVPN_USERNAME=[REMOVED]
OPENVPN_PASSWORD=[REMOVED]
OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
LOCAL_NETWORK=[REMOVED]
ENABLE_UFW=false
GLOBAL_APPLY_PERMISSIONS=true
DROP_DEFAULT_ROUTE=false
HEALTH_CHECK_HOST=ipv4.icanhazip.com
TRANSMISSION_RPC_BIND_ADDRESS=0.0.0.0
TRANSMISSION_RPC_ENABLED=true
TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=false
TRANSMISSION_RPC_WHITELIST=172.17.*.*,[REMOVED],127.*.*.*
TRANSMISSION_RPC_WHITELIST_ENABLED=true
TRANSMISSION_WEB_UI=kettu
TRANSMISSION_HOME=/data/transmission-home
TRANSMISSION_WATCH_DIR_FORCE_GENERIC=false
WEBPROXY_ENABLED=false
```

Replace `[REMOVED]` with your appropriate values; path to your Syno's volume where you've got the files stashed, subnet of your LAN (e.g., if your computer's IP is `192.168.0.2` then you probably want `192.168.0.0/24`), and so on. Note that the TRANSMISSION_RPC_WHITELIST is a comma-separated list with no "wrappings;" the list doesn't have any quotes around it, and unlike the LOCAL_NETWORK variable, it uses asterisk wildcards instead of standard CIDR notation. Make sure you're following the setup instructions here, with exceptions for the environment variables being passed via the `--env-file` flag instead of multiple `-e` flags, your bind paths, etc..

**Comment by Hedrik** [comment] 2020-08-23 23:54
Anyone have ideas regarding the self-signed certificate?  Perhaps a way to allow them, or perhaps someone knows where to get a PIA certificate (and verification .pem, presumably) that is not self-signed and is not expired?  :-)

**Comment by haugene** [comment] 2020-08-24 19:18
I'm not exactly sure what about the dev image I though would do the trick. I just know that it has been working the last couple of days as I've been developing on the dev branch. So I figured it was worth a shot.

As of now, there is not many benefits to using URL vs local file. It is a convenience option for many users that have been submitting issues trying to mount their own configs. Using the URL approach it will automatically substitute the`auth-user-pass` line that needs to point to the username/password supplied. Planning to extend it later to address some best practices like removing ping-restart and adding ping-exit instead and push filter for ignoring ping options etc.
Also turns out that I hadn't merged my latest changes to dev. Did that now, and a new image was just pushed.

I did some testing now and I see that I can't connect to Sweden, but it works for Denmark and also Israel like your config says. That being with the old configs. Pulled both the latest and dev images now and compared OpenVPN version:

```
docker run --rm -it haugene/transmission-openvpn bash -c "openvpn --version"                                                                                               
OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 27 2020
```
```
docker run --rm -it haugene/transmission-openvpn:dev bash -c "openvpn --version"                                                                                        
OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
```

So it might be the OpenVPN version, but it's only a couple of patch versions away. What do you think?

**Comment by Hedrik** [comment] 2020-08-24 20:00
Interesting the PKCS11 is missing in the newer version of OpenVPN...

When you say "old configs" did they have embedded certificates or was the cert a separate file from the .ovpn?

**Comment by haugene** [comment] 2020-08-24 21:11
Old is probably misleading. Current would be more correct. I was running with the configs that are embedded in the image. So that means [this config](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/pia/Denmark.ovpn) for example for Denmark. The configs are not embedded, but separate.

**Comment by Hedrik** [comment] 2020-08-25 00:25
Hmmm...  Perhaps I will try just using a certificate and .pem from one of the 'next-gen' config .zips then, (from [newest config bundles from PIA](https://www.privateinternetaccess.com/helpdesk/news/posts/august-19th-2020-important-updated-server-changes-and-related-issues) that you pointed me to - thanks) since the issue is apparently that the certificate I have has expired...

I'll also look into trying out the 'dev' tagged version.

**Comment by Hedrik** [comment] 2020-08-25 00:53
Still getting the self-signed cert error:

`Tue Aug 25 00:46:57 2020 VERIFY ERROR: depth=1, error=self signed certificate in certificate chain: C=US, ST=OH, L=Columbus, O=Private Internet Access, CN=Private Internet Access CA, emailAddress=secure@privateinternetaccess.com`

using the file overlay method:

```
  -v /***/PIA_New_ca.crt:/etc/openvpn/pia/ca.crt \
  -v /***/PIA_New_crl.pem:/etc/openvpn/pia/crl.pem \
```

**Comment by Hedrik** [comment] 2020-08-26 19:12
Switching to :dev and using the :dev .ovpn config, certificate and .pem files works...

**Comment by haugene** [comment] 2020-08-27 08:12
Glad you got it working @Hedrik, but I'm interested in figuring out why.
Are you using the OPENVPN_CONFIG_URL option? Or mounting your own files? Because the .ovpn files that are bundled in the :dev image are the same as those bundled in the :latest image. Maybe it's the newer OpenVPN version in that case. Had you pulled the :latest image relatively recently when you were running that?

**Comment by Hedrik** [comment] 2020-08-27 10:31
@haugene, No to OPENVPN_CONFIG_URL, no to mounting files, and yes to having downloaded :latest relatively recently (during the this last week)

**Comment by haugene** [comment] 2020-08-27 11:29
Good to know. So it's something with the OpenVPN installation, or the base OS then. The dev branch is based on alpine.

**Comment by Hedrik** [comment] 2020-08-27 15:19
So it would appear @haugene - though I would expect that if it is OpenVPN there is a flag for allowing self-signed certificates that maybe has a different default value in the two versions?  I wouldn't think it to be the OS...

**Closed** 2020-11-02 18:22 UTC
Labels: inactivity
