### ISSUE TITLE
Privado

### ISSUE THREAD

**Issue by mlcarson** [haugene/docker-transmission-openvpn#1039] opened 2020-02-06 12:03 UTC
**Which provider?**
Privado
Newshosting is in the process of switching to this VPN provider.

**Where are the configs?**
https://privado.io/apps/ovpn_configs.zip

**Comment by mlcarson** [comment] 2020-02-06 19:30
Tried doing a custom provider option with this and am getting this in the container log:
```
OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019
library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08
neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Auth Username:'.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work, and you can not use --auth-nocache.
Exiting due to fatal error
```

**Comment by muddybulldog** [comment] 2020-02-06 20:09
See [Add ExpressVPN to list of VPN providers #293](https://github.com/haugene/docker-transmission-openvpn/issues/293) for guidance on modifying your ovpn profile.

**Comment by mlcarson** [comment] 2020-02-06 20:12
I got the custom provider option to work but had to modify the ovpn file:
"auth-user-pass"
to
"auth-user-pass"  /config/openvpn-credentials.txt"

This was not intuitive and I don't see it documented anywhere on the custom provider web page:
https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_custom_provider
I found the answer in issue #831.

**Comment by jpoggi** [comment] 2020-02-09 15:49
Hi @mlcarson 

Can you provide a copy without any credentials of your working configuration of ovpn file ?

I must switch to Privado VPN to, the previous VPN service is shutting down on 18/02/2020.

Regards.

**Comment by jpoggi** [comment] 2020-02-09 15:56
> Hi @mlcarson
> 
> Can you provide a copy without any credentials of your working configuration of ovpn file ?
> 
> I must switch to Privado VPN to, the previous VPN service is shutting down on 18/02/2020.
> 
> Regards.

Forget my question, I just saw that Privado VPN provide this file.

**Comment by Czpb9h** [comment] 2020-02-20 23:01
Please consider this a Public Service Announcement, as of this date 02/20/20 the issue is not resolved nor has PRIVADO provided a resolution or explanation as to why this is occurring. 

The sequence of responses to my trouble ticket appears below
:
to Privado, bcc: Newshosting

Your service is not working... When I set the choice to the United States and choose New York, then click on connect, I check my current IP prior and then... after clicking on the PRIVADO Connect, the PRIVADO VPN then states it is retrieving my Ip...(I presumed this would be a Different IP!) then I get a system notice that my IP location has changed... when I check using the site (https://www.whatismyip.com/)What is my IPv4 address it reports my ISP Issued IP... My Origin IP... this shows the "SAME" in the PRIVADO VPN Window???? it never changed??? I then have to disconnect choose manually another site then click on connect to get my IP to change???  your telling me this is Better than the one click VPN I had before???

I now have to check and recheck to make sure my IP is changed or hidden and if I forget and trust my VPN service to do what they claim they do I'm at risk, even the System(Window10 Pro) tells the user your Location has changed??? WTF!!!

So tell me what type of Coverage is this and when I get Sued how to include this information to your subscribers???
*
Privado via mysupporthosting.happyfox.com 
Fri, Feb 14, 8:26 AM (6 days ago)
to Czp

New reply for the ticket #PV00011186
 
Hello,

We can check to see if your logs indicate anything that might cause the discrepancy in IP address your seeing.

Please export the log from our client by going to Settings - > Logs -> Export all and attach it to your next reply.

This might only be happening on one server, so I'd recommend in the interim to choose a different server in a different location and see if that resolves the problem.

Regards,
Privado Support 
*

CZP 
Attachments
Fri, Feb 14, 8:45 AM (6 days ago)
to Privado, bcc: Newshosting

I note that I went to bed with the connection (VPN) on when I checked this morning it was and is still showing "Connected' and is now displaying my ISP issued IP address while "United States" Washington DC is my Choose Virtual Location setting, so I'm exposed and there is/ was no 'KILL Switch' action associated with your VPN Service???:
find attached the requested Log, I look thru it and note the date and events are only for 02/14/20?
*
New reply for the ticket #PV00011186
 
Hello,

Our service only operates using IPv4, so if you submit a request for a website that has an IPv6 address, it will resolve using an IPv6 DNS server and transfer the information outside of our VPN network. This means you will need to disable IPv6 to prevent DNS leaks.

We are currently are working on an internet killswitch feature to be added to our Privado client. 

Regards,
Privado Support
*
CZP
Attachments
Feb 16, 2020, 2:34 PM (4 days ago)
to Newshosting, Privado

This is so sad, Your service is TOTALLY flawed, I will have to find a VPN that works without me guessing if I'm protected or not, this is not what I expect for what I paid for with my Newshosting subscription, The PRIVIDO VPN service is unreliable and places me at risk. tricking me to NOT trust what my own eyes and other services are showing me that my ISP issued IPv4 address IS VISIBLE when your service shows me as having established a different one .

I have attached screenshots of what I am seeing when your service shows Connected via Washington DC IP 85.12.61.14 I will not shutdown , disconnect(Your VPN service) until TUESDAY 1: P.M..
Note in the WhatIsMyIP.com screenshot, my Real IP is visible and in the What Time is it(Screenshot) and Actual Location of NEW YORK!

What you provide is a degrade of my service and agreement.. 

Whomever vetted PRIVADO as a replacement obviously did not do any research Or TESTING of the product and how it would affect the client base.  This is clearly seen in the screenshots provided, if I see this as a user how could the vetting process have missed it????

Simple, they did not TEST or Care!

I will check my recourse to this issue, and begin to see if there are others experiencing what I am reporting.

Regards

Very disappointed
CZP

**Comment by jpoggi** [comment] 2020-02-22 10:20
@Czpb9h 

It seems that I'm having some trouble to start torrent as well, tracker are unreachable. I've restart the container but there is no improvement.

`
[2020-02-22 10:15:31.620] ubuntu-18.04.4-live-server-amd64.iso Scrape error: Could not connect to tracker (announcer.c:1279)
`
`[2020-02-22 10:19:39.650] ubuntu-18.04.4-live-server-amd64.iso IPv4 DHT not ready (broken, 0 nodes) (tr-dht.c:592)`

I will open a case too at Privado Support.

**Comment by mlcarson** [comment] 2020-02-26 17:41
My experience has been different.  I was able to get Privado working even before it was made an official provider and finally changed my setup over the weekend to use it as an official provider.  It works as expected in both Windows and Debian Linux.    Torrents were not working with the LAX endpoint -- I assumed that Privado just doesn't support them in the USA so switched to one of the endpoints that I thought would work (Zurich or the Netherlands -- don't remember) with Torrents and it did.   I don't see this situation as too much different than Newshosting as the provider.

**Comment by haugene** [comment] 2020-03-29 14:29
As Privado was added as a provider through #1043 I think it might be time to close this issue.
Feel free to re-open if there are still any issues.

PS: @mlcarson I agree with you on your previous comment that the change from `auth-user-pass` to `auth-user-pass /config/openvpn-credentials.txt` is not intuitive. I thought it was in there 🤔 Will add it now.

**Closed by haugene** 2020-03-29 14:29 UTC

**Comment by KPreston2900050** [comment] 2020-03-31 22:30
If someone can comment...
What is the sense of when Your ISP shuts down the Privado software not only displays the can not contact message but ALSO pops up a window saying that with the cannot contact message.
But you have to physically close that window leaving all your data exposed if you are not monitoring it 24/7.

Instead of reconnecting once the ISP provider goes back online the VPN remains off and life goes on as normal.

The opposite side of this is I can turn security on 100% which locks down all network access if the internet drops but that works dandy if I am trying to access from a remote office on our network.
I have to physically walk down to office and manually access the PC.

AVG allowed me to configure ports to allow remote access in case of failure but Privado is crap.

Since this virus scare the internet has been on maximum use and my ISP has crashed several times leaving me to monitor my VPN on a constant basis because I can not trust Privado with my security.

Now THAT is what I call data security especially when Usenet Server forced me to use this service.
