### ISSUE TITLE
Latest update gives no connection

### ISSUE THREAD

**Issue by b055k060644** [haugene/docker-transmission-openvpn#1670] opened 2021-01-19 11:34 UTC
**Before creating this issue I have:**

- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [X] Tried to add as much relevant information to the issue as possible

**Describe the problem**
Watchtower updated the container last night - using the 'Latest' tag on DSM Docker. Web UI won't open, when opening I see:
```
This page isn’t working
192.168.1.149 didn’t send any data.
ERR_EMPTY_RESPONSE
```

**Add your docker run command or docker-compose file (please paste into a code block using "\`")**
docker run \
    --cap-add=NET_ADMIN \
    --device=/dev/net/tun \
    -d \
    -v /volume1/docker/transmission/resolv.conf:/etc/resolv.conf \
    -v /volume1/docker/transmission/:/data \
    -e "OPENVPN_PROVIDER=MULLVAD" \
    -e "OPENVPN_CONFIG=gb_all" \
    -e "OPENVPN_USERNAME=******" \
    -e "OPENVPN_PASSWORD=m" \
    -e "LOCAL_NETWORK=192.168.1.0/24" \
    -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
    -e "PGID=1035" \
    -e "PUID=65538" \
    -e "TRANSMISSION_WATCH_DIR=/Data/Downloads/Torrents/ToFetch" \
    -e "TRANSMISSION_WATCH_DIR_ENABLED=true" \
    -e "TRANSMISSION_UMASK=2" \
    -e "TRANSMISSION_INCOMPLETE_DIR=/Data/Downloads/Torrents/InProgress" \
    -e "TRANSMISSION_DOWNLOAD_DIR=/Data/Downloads/Torrents/Movies" \
    -e "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true" \
    -e "TRANSMISSION_RPC_ENABLED=true" \
    -e "TRANSMISSION_RPC_PASSWORD=******" \
    -e "TRANSMISSION_RPC_USERNAME=******" \
    -p 9091:9091 \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    --name "transmission-openvpn" \
    haugene/transmission-openvpn:latest

**Logs (please paste into a code block using "\`")**

```
```
2021-01-19 11:22:43 | stdout | Tue Jan 19 11:22:43 2021 Restart pause, 5 second(s)
-- | -- | --
2021-01-19 11:22:43 | stdout | Tue Jan 19 11:22:43 2021 SIGUSR1[soft,init_instance] received, process restarting
2021-01-19 11:22:43 | stdout | Tue Jan 19 11:22:43 2021 Could not determine IPv4/IPv6 protocol
2021-01-19 11:22:43 | stdout | Tue Jan 19 11:22:43 2021 RESOLVE: Cannot resolve host address: gb-lon-003.mullvad.net:1196 (Try again)
2021-01-19 11:22:38 | stdout | Tue Jan 19 11:22:38 2021 RESOLVE: Cannot resolve host address: gb-lon-003.mullvad.net:1196 (Try again)
2021-01-19 11:22:33 | stdout | Tue Jan 19 11:22:33 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2021-01-19 11:22:28 | stdout | Tue Jan 19 11:22:28 2021 Restart pause, 5 second(s)
2021-01-19 11:22:28 | stdout | Tue Jan 19 11:22:28 2021 SIGUSR1[soft,init_instance] received, process restarting
2021-01-19 11:22:28 | stdout | Tue Jan 19 11:22:28 2021 Could not determine IPv4/IPv6 protocol
2021-01-19 11:22:28 | stdout | Tue Jan 19 11:22:28 2021 RESOLVE: Cannot resolve host address: gb-lon-005.mullvad.net:1196 (Try again)
2021-01-19 11:22:23 | stdout | Tue Jan 19 11:22:23 2021 RESOLVE: Cannot resolve host address: gb-lon-005.mullvad.net:1196 (Try again)
2021-01-19 11:22:18 | stdout | Tue Jan 19 11:22:18 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2021-01-19 11:22:13 | stdout | Tue Jan 19 11:22:13 2021 Restart pause, 5 second(s)
2021-01-19 11:22:13 | stdout | Tue Jan 19 11:22:13 2021 SIGUSR1[soft,init_instance] received, process restarting
2021-01-19 11:22:13 | stdout | Tue Jan 19 11:22:13 2021 Could not determine IPv4/IPv6 protocol
2021-01-19 11:22:13 | stdout | Tue Jan 19 11:22:13 2021 RESOLVE: Cannot resolve host address: gb-mnc-103.mullvad.net:1196 (Try again)
2021-01-19 11:22:08 | stdout | Tue Jan 19 11:22:08 2021 RESOLVE: Cannot resolve host address: gb-mnc-103.mullvad.net:1196 (Try again)
2021-01-19 11:22:03 | stdout | Tue Jan 19 11:22:03 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2021-01-19 11:21:58 | stdout | Tue Jan 19 11:21:58 2021 Restart pause, 5 second(s)
2021-01-19 11:21:58 | stdout | Tue Jan 19 11:21:58 2021 SIGUSR1[soft,init_instance] received, process restarting
2021-01-19 11:21:58 | stdout | Tue Jan 19 11:21:58 2021 Could not determine IPv4/IPv6 protocol
2021-01-19 11:21:58 | stdout | Tue Jan 19 11:21:58 2021 RESOLVE: Cannot resolve host address: gb-lon-010.mullvad.net:1196 (Try again)
2021-01-19 11:21:53 | stdout | Tue Jan 19 11:21:53 2021 RESOLVE: Cannot resolve host address: gb-lon-010.mullvad.net:1196 (Try again)
2021-01-19 11:21:48 | stdout | Tue Jan 19 11:21:48 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2021-01-19 11:21:43 | stdout | Tue Jan 19 11:21:43 2021 Restart pause, 5 second(s)
2021-01-19 11:21:43 | stdout | Tue Jan 19 11:21:43 2021 SIGUSR1[soft,init_instance] received, process restarting
2021-01-19 11:21:43 | stdout | Tue Jan 19 11:21:43 2021 Could not determine IPv4/IPv6 protocol
2021-01-19 11:21:43 | stdout | Tue Jan 19 11:21:43 2021 RESOLVE: Cannot resolve host address: gb-lon-102.mullvad.net:1196 (Try again)
2021-01-19 11:21:38 | stdout | Tue Jan 19 11:21:38 2021 RESOLVE: Cannot resolve host address: gb-lon-102.mullvad.net:1196 (Try again)
2021-01-19 11:21:33 | stdout | Tue Jan 19 11:21:33 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2021-01-19 11:21:28 | stdout | Tue Jan 19 11:21:28 2021 Restart pause, 5 second(s)
2021-01-19 11:21:28 | stdout | Tue Jan 19 11:21:28 2021 SIGUSR1[soft,init_instance] received, process restarting
2021-01-19 11:21:28 | stdout | Tue Jan 19 11:21:28 2021 Could not determine IPv4/IPv6 protocol
2021-01-19 11:21:28 | stdout | Tue Jan 19 11:21:28 2021 RESOLVE: Cannot resolve host address: gb-mnc-102.mullvad.net:1196 (Try again)
2021-01-19 11:21:23 | stdout | Tue Jan 19 11:21:23 2021 RESOLVE: Cannot resolve host address: gb-mnc-102.mullvad.net:1196 (Try again)
2021-01-19 11:21:18 | stdout | Tue Jan 19 11:21:18 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2021-01-19 11:21:18 | stdout | Tue Jan 19 11:21:18 2021 library versions: OpenSSL 1.1.1i  8 Dec 2020, LZO 2.10
2021-01-19 11:21:18 | stdout | Tue Jan 19 11:21:18 2021 OpenVPN 2.4.10 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jan  4 2021
2021-01-19 11:21:18 | stdout | Tue Jan 19 11:21:18 2021 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
2021-01-19 11:21:18 | stdout | adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
2021-01-19 11:21:18 | stdout | Setting OpenVPN credentials...
2021-01-19 11:21:18 | stdout | Starting OpenVPN using config gb_all.ovpn
2021-01-19 11:21:18 | stdout | Using OpenVPN provider: MULLVAD
2021-01-19 11:21:18 | stderr | mknod: /dev/net/tun: File exists
2021-01-19 11:21:18 | stdout | Creating TUN device /dev/net/tun
2021-01-19 11:21:18 | stdout | Starting container with revision: 00e8b6f6994ff4d286f8337cdb6e2320d7e2d865

Watchtower Log

2021-01-19 09:47:32 | stderr | time="2021-01-19T09:47:32Z" level=info msg="Creating /transmission-openvpn"
-- | -- | --
2021-01-19 09:47:02 | stderr | time="2021-01-19T09:47:02Z" level=info msg="Stopping /transmission-openvpn (a727a2b22bfb1e7efe11f0f382c7319f6763d498bf7cbec91ed34a7d66dae4bc) with SIGTERM"
2021-01-19 09:46:23 | stderr | time="2021-01-19T09:46:23Z" level=info msg="Found new haugene/transmission-openvpn:latest image (sha256:789434d4dd94eda22f7687f805348699e4bb58e283ac1e84c47ed592dd35e09c)"
2021-01-19 03:47:05 | stderr | time="2021-01-19T03:47:05Z" level=info msg="Creating /transmission-openvpn"
2021-01-19 03:46:54 | stderr | time="2021-01-19T03:46:54Z" level=info msg="Stopping /transmission-openvpn (267eec15aaf4ba111bb66a5934a9cdaf1d6a78cd25e5499fac4f916a5a238cc8) with SIGTERM"
2021-01-19 03:46:45 | stderr | time="2021-01-19T03:46:45Z" level=info msg="Found new haugene/transmission-openvpn:latest image (sha256:878c2ca730bee878beabf164d3e660ba423edd4bcdf361307bacc6e9f262ed70)"
2021-01-19 03:46:10 | stderr | time="2021-01-

```

```

**Host system:**
Synology DSM - up to date
Docker

**Comment by b055k060644** [comment] 2021-01-19 11:46
I have a feeling its the OPENVPN Config that's causing the issues but I don't know enough to diagnose.

**Comment by huntastikus** [comment] 2021-01-19 18:50
I get the following in the logs:

{ "status": "", "message": "bad signature" }
the has been a fatal_error
transmission auth not required
waiting for transmission to become responsive
transmission became responsive
66 100% 339.1 MB Done 0.0 0.0 0.0 Idle *Name of torrent here*
Sum: 1.56 TB 0.0 0.0
setting transmission port to
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Error: portTested: http error 0: No Response
date: invalid date '@'
#######################
SUCCESS
#######################
Port:
Expiration
#######################
Entering infinite while loop
Every 15 minutes, check port status
60 day port reservation reached
Getting a new one
curl: (6) Could not resolve host: www.privateinternetaccess.com

Seems the openDNS is setting 10.0.0.249 as the DNS server in /etc/resolv.conf

**Comment by pkishino** [comment] 2021-01-19 23:51
thinks this is a duplicate of #1667

**Closed by pkishino** 2021-01-19 23:51 UTC
Labels: bug
