### ISSUE TITLE
Files not in completed folder

### ISSUE THREAD

**Issue by tstewart65** [haugene/docker-transmission-openvpn#266] opened 2017-07-01 04:45 UTC
If a torrent is sent it using RPC the file are not ending up in the completed folder.  I can seem them in the incomplete folder while they are downloading though.  The files are somewhere since the uploads still continue and I can have transmission verify local data and everything is fine.

If I add a torrent to the watch folder or load a torrent file using the web interface the files end up in the completed folder.

This is running on a Synology Diskstation.

**Comment by haugene** [comment] 2017-07-06 13:13
It's possible to set the download location when adding a torrent, can the RPC approach end up setting another completed location? You should be able to see the location of the file in the information panel in the web ui, what does it say? This seems to be a duplicate of #265 right? If so, please close this issue and follow up there.

**Comment by tstewart65** [comment] 2017-07-06 15:36
It shows up in the incomplete folder while downloading.  After it is done downloading it states it is in the completed folder but it is not there.  This could be the same as #265 if only the RPC method is causing the problem.  If I add a torrent or add a torrent through the watch folder then everything works fine.

**Comment by kronnnnnn** [comment] 2017-07-29 01:53
If your setting the download location in your RPC then it's being passed to transmission. Not sure if there is an option to disable this (never found one)

**Comment by haugene** [comment] 2018-03-18 19:00
Closing this. As I wrote in #265, I don't think there's anything wrong with the container.
The path set by the RPC method "has" to be different than the default one where the stuff from the watch folder ends up.

If you're still having problems, I think the [chat](https://gitter.im/docker-transmission-openvpn) is a better forum for this. If you do re-open this issue, please provide enough information for us to reproduce it. Setup of mounts, information of torrent download paths, etc etc. This has something to do with your setup and can't be reproduced if we don't know what you've done.

**Closed by haugene** 2018-03-18 19:00 UTC
