### ISSUE TITLE
Disable VPN altogether.

### ISSUE THREAD

**Issue by winneon** [haugene/docker-transmission-openvpn#515] opened 2018-05-20 12:21 UTC
Hello,

I absolutely love the idea of this container and have been using it with the PIA provider for a few days now. However, the speeds at which I'm getting, on a seedbox no less, are absolutely abysmal (5MB/s tops). Would it be possible to completely disable the VPN altogether for those who don't really need it, but want to use this amazing container anyway?

**Comment by coolboiime** [comment] 2018-05-20 17:55
If you’re experiencing slow speeds, check if you’re connecting through TCP. TCP tends to slow things down because of all the verification going on.

Not sure what you meant my disabling the VPN altogether

**Comment by winneon** [comment] 2018-05-20 18:02
TCP is disabled, I'm using UDP.

I mean cut out the VPN middleman in an option so the container doesn't have tunneled traffic to other peers.

**Comment by winneon** [comment] 2018-05-20 18:30
Exactly, that's what I'm asking for. This container supports a lot of other options and configurations other than a VPN setup, and I don't want to lose that.

I can submit a pull request later on in the day that will implement such an option (key word, being option, with the VPN being on by default), but I at least wanted feedback.

There are other `docker-transmission` containers without the VPN element but they're not as well developed or maintained, so I would prefer to use this one, albeit without the slow speeds I'm getting.

**Comment by niXta1** [comment] 2018-05-31 22:12
I'm not sure why you get so low speed, I can max out 100mbit easy on a Synology NAS... Maybe tinker around with the settings and ask the seedbox company if they have any recommendations.

If you really want to run it without a VPN, I would start by poking around in the start.sh script.

**Comment by niXta1** [comment] 2018-06-11 15:25
I can confirm that PIA can do 100mbit on this container.

**Comment by plantsandbinary** [comment] 2018-06-25 18:44
If you don't want to use the VPN you could just install the original Transmission docker container.

**Comment by coolboiime** [comment] 2018-06-25 20:28
It's difficult trying to add features in a docker image that wasn't designed for this. I suppose you can fork the docker image, and make those changes that way.

Feel free to share your forked repository here, but since it's a request beyond purpose I will respectfully close this issue for now.

**Closed by coolboiime** 2018-06-25 20:28 UTC
Labels: wontfix
