### ISSUE TITLE
slow speeds on PIA inside container

### ISSUE THREAD

**Issue by MartinWall** [haugene/docker-transmission-openvpn#1643] opened 2021-01-03 18:59 UTC
I am getting slow speeds <2000k inside the container and via transmission. 

When I run curl --output /dev/null http://speedtest.atlanta.linode.com/100MB-atlanta.bin inside the container it's under 2000k and I've tried about ten different PIA servers. 

If I run the same command outside the container I get 20Mb+.

Running debian on a raspberry pi 4 - cpu is only around 10% while downloading so it's not a cpu issue. 

Is there a way to force tcp for PIA? or anything else I can do to test and narrow down what's happening? Can I force a certain type of encryption? (per this link? https://forums.unraid.net/topic/78228-super-slow-vpn-speed-in-dockers-and-vms/)

#######################,
Sun Jan  3 12:48:41 2021 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10,
Sun Jan  3 12:48:41 2021 OpenVPN 2.4.9 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020

**Comment by MartinWall** [comment] 2021-01-04 00:36
Update - if I use a custom config and force tcp gcm it gets up to about 6000k. Still about 1/5 the speed of doing the same test outside the container, but much better than UDP.
If I try UDP gcm it is just as slow as the default crt encryption.

**Comment by burdenc** [comment] 2021-01-10 03:30
Hitting this issue as well (also on RPi 4). I can at least confirm it's not a docker bottleneck because I see ~70 MB/s from the proxy container. Switching to TCP (I believe setting `PIA_OPENVPN_CONFIG_BUNDLE=openvpn-tcp` should do this?) I also see a boost to ~6 MB/s.

The only thing in my logs that seems to stand out to me is this:
> WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.

Though I will say I'm not sure these curl speed tests will be entirely representative of the speeds you would see in transmission because it's one connection versus potentially dozens. 

(BTW I found http://speedtest.wdc01.softlayer.com/downloads/test500.zip to be a little faster for speed tests)

**Comment by burdenc** [comment] 2021-01-10 04:31
As far as I can tell using a wireguard implementation ([thrnz/docker-wireguard-pia](https://hub.docker.com/r/thrnz/docker-wireguard-pia)) gives me expected speeds of 20 MB/s. Leaning towards this being an OpenVPN issue then?

**Comment by TopCheddar27** [comment] 2021-02-15 07:25
@MartinWall @burdenc This is absolutely happening. I have ruled out encryption throughput (processor can reliably transmit 100 Megabit through OpenVPN), connection throughput (running 500 megabit connection, and connected to a PIA server which I can get 60-100 megabit from reliably on other instances), and disk throughput (on a 4 disk ZFS mirror pool with write cache to NVME). 

Something is OFF with the implementation. I have seen the finger pointed at transmission itself, next gen servers etc... Im just not sure anymore. I have looked into MTU fragmentation but all seems auto configured well for that via PIA. All I know is that manually passing qbittorrent through wiregaurd-PIA with a forwarded port works absolutely fine on the same hardware and network path. I may just maintain my own image for that. If anybody reads this I am begging for another set of eyes on this, because it seems like its just too hard to track down. Hell, it does not even seem that common.

**Comment by pkishino** [comment] 2021-03-09 01:17
I've looked at this before and for me (running docker on macmini, privatevpn) I don't see much speed difference inside and outside, also in my own build I don't see much difference so I would have so say this very much looks like a PIA/VPN provider issue related to openvpn config.
@haugene I don't think there is so much we can really do with this..
I will close this for now but keep discussion open

**Closed by pkishino** 2021-03-09 01:17 UTC
Labels: help wanted

**Comment by haugene** [comment] 2021-03-13 21:57
No, I'm not sure what can be done. We've had a ton of these over the years. Some seem to be related to providers, others have been solved by changing VPN server. Then we changed the default setting for UTP in #978 and that has given some results for some. I really don't know of any good tricks here. It's important to remember that all the code in this container runs before OpenVPN starts. Then we `exec` to the OpenVPN process and we're out. So at runtime this container is running a clean OpenVPN process and is fed with an openvpn config that we've tweaked.

So this has to be due to OpenVPN, the base image, docker, the host or some specific option in the configs (which may vary between providers). I'm all for an open discussion on this - but from a "support" point of view I think we should say that if you can download then it works as intended. Then we can use our maintenance time on pushing the new config repo and finally implementing support for Wireguard. Maybe that will the final fix. Will gladly accept PRs with good global improvements though :smile:

**Comment by martdj** [comment] 2022-02-14 07:59
Fixed it on my end here. The magic was in the setting (in Transmission itself Network - Options - Enable uTP for peer communication. This setting was "On" and it should be "Off" for proper speed!
